### ISSUE TITLE
Slider inside a repeater issue

### ISSUE THREAD

**Issue by ziga-miklic** [siteorigin/so-widgets-bundle#1]
When you put a slider input inside a repeater, it does not work properly. You either get the issue where all slider values are set to 0 and 1 additional repeater element is inserted after saving or the repeater item cannot get any new items - they disappear once the page is saved.

Also tested on a fresh WordPress site using your so-dev-examples (where I just move a slider inside a repeater) and the latest versions of Page Builder and Widgets Bundle.

Hopefully this is enough information to find what is causing the issue.

**Comment by braamgenis** [comment]
Hi Žiga

Thanks for reporting this. I've found the issue and it's been fixed in the develop branch.

Please keep reporting any other issues you find! :)
