### ISSUE TITLE
Adding hooks to custom widget

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/so-widgets-bundle#10]
Hi

I have made a bundle of custom widgets that i want to make customizable using filter and action hooks.

Im adding filters to the arrays where i define the fields. This way i can add custom fields for each theme that uses the plugin.
I also add action hooks to the frontend so i can insert the data from theme specific fields.

I have gotten the hooks to work but as soon as i add another instance of the widget i get a php error.

Im guessing that the issue is related to instancing of the widget but im not sure how to fix it. Im not sure weather this is a so-widget specific problem but i thought maby someone in here had run into the problem.

Link to widget (only the accordion widget has hooks at this point):
https://github.com/Jursdotme/secondthought-pagebuilder-bundle/tree/master/secondthought-widgets/secondthought-accordion-widget

**Comment by braamgenis** [comment]
Hi Rasmus

Awesome to see you're using the Widgets Bundle. :smiley:

Are you still having this issue? What exactly is the PHP error you get? Can you give a code sample of how you create a new instance of the widget and post some of the stack trace?
