### ISSUE TITLE
Investigate alternatives to jquery.touchSwipe.js

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1001]
@AlexGStapleton Can you perhaps suggest an alternative library to jquery.touchSwipe.js, perhaps one that's a little easier to scroll on a touch device. Perhaps also take a look at how the library is integrated to see how much time it'll take for us to make the change for the Post Carousel widget.

**Comment by AlexGStapleton** [comment]
I had a look around and I'm unable to find a viable alternative library. The only way forward is to either fork the TouchSwipe (and fix the Firefox issue) or create a slim version of it.

**Comment by Misplon** [comment]
LiveMesh looks to be using http://kenwheeler.github.io/slick/. Would that solve our issues? https://github.com/kenwheeler/slick.

**Comment by AlexGStapleton** [comment]
They're not equivalent. Slick is a complete carousel library while touchSwipe is a touch detection plugin that's used by the SO Post Carousel code. Switching to Slick would be a major change to the Post Carousel widget as it would mean an almost complete recode of the frontend of the widget.

**Comment by Misplon** [comment]
Understood, thanks.

**Comment by Misplon** [comment]
Closing until a better option becomes available.
