### ISSUE TITLE
Slider: Change "Frame" label to image title

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1002]
Currently, Slider widget frame labels don't update based on the content inserted.

![Edit_Page_‹_SiteOrigin_Premium_Demo_—_WordPress](https://user-images.githubusercontent.com/789159/77085986-c58fb180-6a09-11ea-972e-1efbb288cdf9.png)

Change the "Frame" label to match the media title from the Media Library. I think the order of priority should be:

1. Background image title.
2. Video title.
3. Foreground image title.

To confirm, by title I mean the title field in the Media Library.

@AlexGStapleton Are you happy with the above fallback order?

**Comment by AlexGStapleton** [comment]
The suggested ordering is fine.
