### ISSUE TITLE
Layout Slider: Change "Frame" label to image title

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1003]
Currently, Layout Slider widget frame labels don't update based on the content inserted.

![layout](https://user-images.githubusercontent.com/789159/77089077-04c00180-6a0e-11ea-9963-65cd613aebcc.png)

Change the "Frame" label to match the media title from the Media Library. I think the order of priority should be:

1. Background image title.
2. Video title.

To confirm, by title I mean the title field in the Media Library.

@AlexGStapleton Are you happy with the above fallback order?

**Comment by AlexGStapleton** [comment]
I'm fine with this ordering.
