### ISSUE TITLE
SO Simple Masonry Image: Add Preloader to mask images

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1023]
The SiteOrigin Simple Masonry Image widget relies heavily on JavaScript to work. Before the JavaScipt is able to display, the images are disabled at full size. We should introduce a CSS preloader to mask this.

**Comment by AlexGStapleton** [comment]
@Misplon Is there a specific design you had in mind for the preloader, or would you prefer all of the images to be hidden and only shown once the JavaScript is able to run? The latter may harm UX if the widget is using images with large file sizes and the download takes a significant amount of time.

**Comment by Misplon** [comment]
There isn't a specific design I had in mind. Do you perhaps want to try to find an example of what you're thinking design-wise? I had a look around now but nothing is jumping out at me yet.

**Comment by AlexGStapleton** [comment]
I typically use one from https://loading.io/css/ as they're quite simple to add. I think the circle (row 2 column 2) is fine. Thoughts?

**Comment by Misplon** [comment]
Row 2 column 2, agreed.

![Pure_CSS_Loader_-_Optimized_Spinners_for_Web_·_Loading_io](https://user-images.githubusercontent.com/789159/79355014-6f952780-7f3d-11ea-8d00-73109110a9ee.png)

**Comment by AlexGStapleton** [comment]
I've started work on this and I've realized a few settings need to be added. There's nowhere to really put them currently so I want to introduce a new group called Preloader (or maybe Settings) and add three settings:

- Show Preloader (certain people may not want it - up to you)
- Preloader Color
- Preloader Height
  * The size of the preloader prior to your Masonry Images showing

Are you okay with those names?

**Comment by Misplon** [comment]
Let's call the section Preloader. Otherwise sounds good.
