### ISSUE TITLE
Notice: Undefined offset: 1 

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1029]
A user reported the following notice:

`Notice: Undefined offset: 1 in /wp-content/plugins/so-widgets-bundle/so-widgets-bundle.php on line 792`

Investigate and resolve if a cause is found.

Reference: https://wordpress.org/support/topic/undefined-offset-1-8.

**Comment by AlexGStapleton** [comment]
The code around line 792 is related to loading widget assets. I suspect this user has a widget that's either outdated or poorly made and that's resulting in this issue. Can you please ask the user to run a plugin conflict test to identify what plugin is adding the widget that is causing this notice? 

Once we know what plugin is causing this I'll be able to test against that plugin and work out what's going wrong and account for it. I can preemptively account for it if you would prefer, but it's possible that it won't actually work as I don't have anything to test against.

**Comment by Misplon** [comment]
I've done so, thanks.

**Comment by Misplon** [comment]
@AlexGStapleton please see https://wordpress.org/support/topic/undefined-offset-1-8/#post-12770585. Feel free to reply. Not quite sure where to go from here.

**Comment by AlexGStapleton** [comment]
Your reply is good imo.

**Comment by Misplon** [comment]
The user has suppressed notices. The issue is located in a third-party plugin.
