### ISSUE TITLE
Slider widget frames not rendering properly once link added

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#104]
In the testing example a frame background image was used. Once a link is added to the frame the background image repeats and loses its `cover` setting.

**Comment by Misplon** [comment]
@braamgenis Any chance you might have time to check this out before next week? Alternatively, any idea on a timeline?

**Comment by braamgenis** [comment]
@Misplon I'm afraid not. IMHO this doesn't qualify as a priority 1, i.e. drop everything and fix immediately, bug (happy to discuss if you feel differently). So going by the priority 2 queue (across both Page Builder and Widgets Bundle) and anything else that might come up in between, it might be a while. :smile:
