### ISSUE TITLE
<iframe> is not getting saved in the textarea, text field and even the Code field

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#1060]
Hi,
When I was trying to build a widget for responsive iframes (video, maps, etc..), I noticed that the textarea and even the text field, are filtering out the <iframe> HTML tag.

I had to use the editor field in order to prevent escaping the content. However the solution isn't optimal from the UX perspective (a lot of controls which are useless when dealing with iframe content).

Would it be possible to loosen up the escaping on textarea and text fields? 

A possible and safe solution could be a special field option, which would escape content differently (allow more HTML tags), but  would need to be defined on the widget level. This way default escaping stays the same to prevent any backwards compatibility issues.

**Comment by AlexGStapleton** [comment]
Hi Andrejarh,

The text, tinymce, and textarea fields aren't really designed to handle HTML beyond basic formatting (em, strong, etc). I recommend either using  the [the code form field](https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/#heading-code), or you could [create a custom form field](https://siteorigin.com/docs/widgets-bundle/form-building/adding-custom-fields/) with minimal sanitization to do this

Kind regards,
Alex

**Comment by andrejarh** [comment]
I have tested the Code field, which seems like a great choice, but it also removes the <iframe> tag and doesn't save it.
