### ISSUE TITLE
unaligned elements on all resolutions

### ISSUE THREAD

**Issue by Bibi40k** [siteorigin/so-widgets-bundle#1063]
WP: Version 5.4.1
SO: 1.17.0

Hi,
elements gets unaligned on some resolutions, can you please help me solving this ?

On width 1215px it looks perfect
![image](https://user-images.githubusercontent.com/4104609/83697036-96e7a700-a606-11ea-8e7e-e6de76cd7509.png)

If i go larger, it gets unaligned and also switch elements order
![image](https://user-images.githubusercontent.com/4104609/83697162-fb0a6b00-a606-11ea-94ba-030d7029ea18.png)

**Comment by Misplon** [comment]
Hi @Bibi40k 

Thanks for reaching out. Please, send a link to the page concerned.

**Comment by Bibi40k** [comment]
Thanks

https://www.wearehr.ro/
1036px width for example.

**Comment by Misplon** [comment]
Thanks. It doesn't appear as though SiteOrigin plugins are being used for this page https://www.wearehr.ro/. The theme is handling the masonry layout.

**Comment by Bibi40k** [comment]
Homepage is build with widgets.

![image](https://user-images.githubusercontent.com/4104609/84072885-91100e00-a9d8-11ea-8e9b-769d40730f37.png)

**Comment by Misplon** [comment]
Thanks for the screenshots. The widgets shown aren't authored by SiteOrigin.

**Comment by Bibi40k** [comment]
ok, thanks.

**Comment by Misplon** [comment]
Sure, no problem.
