### ISSUE TITLE
Contact Form Widget: Print the senders email address in the notification email

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#109]
User request: Print the email address of the sender in the admin notification email. 

Here is how an admin notification email might look now:

From: Andrew (currently, this is linked mailto)

Message:
Test

Here is what user is suggesting:

From: Andrew (currently, this is linked mailto)
Email: email@email.com

Message:
Test

**Comment by Misplon** [comment]
@braamgenis Looks like you checked this one in 2016 so leaving open.

**Comment by AlexGStapleton** [comment]
This actually happens now, although not in that exact format. I'm not too sure when this was changed but it was at least six months ago.

![](https://vgy.me/8MJtZB.png)
