### ISSUE TITLE
Editor Widget: Background color not showing in preview

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#110]
There's an issue with the preview for the editor widget that prevents the background color (set via widget style) from being displayed in the preview.

**Comment by gregpriday** [comment]
This is a confusion that's going to come up, but I can't think of a good way to solve it. That preview only really deals with the widget itself, while the widget styling is Page Builder specific. So it's meant to be styling for the layout.

I personally wouldn't want to hack things and have the Widgets Bundle start taking into account widget styles. That would add a lot of complexity to the preview. The Widgets Bundle would need to start detecting, then simulating certain aspects of Page Builder.

@braamgenis, any thoughts on this?

**Comment by braamgenis** [comment]
Maybe a little far out, but would be nice to let Page Builder do previews. I can think of two benefits to doing this:

1. Allows previews for more than just our own widgets.
2. Fixes the above issue and allows previewing of all PB widget styles.

WB would probably then just need to check whether PB is installed and not show it's preview button.

**Comment by Misplon** [comment]
Covered by the Live Editor now. Closing.
