### ISSUE TITLE
New Widget: Anything Carousel

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1111]
**Item Repeater**

- Title
- Content

**Carousel Settings**

- Previous/Next navigation arrows
- Navigation dots
- Loop items. Automatically return to the first item after the last item.
- Autoplay
- Autoplay pause on hover
- Animation speed
- Timeout

**Design**

- Navigation color
- Item padding
- Item margin

**Responsive**

The same group of settings being used on the Post Carousel widget but with `Slides to show` added to each section.

**Comment by AlexGStapleton** [comment]
Do you want to add a dedicated title field for the widget (like the post carousel widget)?

**Comment by Misplon** [comment]
Yes, I think we should.

**Comment by AlexGStapleton** [comment]
We're currently using a filter for the breakpoints in the post carousel widget. Now that there's going to be two widgets that use it, I think we should set up dedicated fields global widget settings fields for them. Thoughts?

**Comment by Misplon** [comment]
Sounds good, thanks.
