### ISSUE TITLE
Contact Form: Ensure compatibility with Akismet

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1112]
Via Twitter:

@SiteOrigin
 : looks like your Contact Form plugin has a bug that impairs its spam-fighting abilities: when sending data to the Akismet API, content should be sent as `comment_content`, not `comment_text`. We've handled it, for now, so your users get better results.

**Comment by stephdau** [comment]
[There it is](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/contact/contact.php#L1232). :)

**Comment by Misplon** [comment]
Thanks for taking a look Stephane, appreciate the help. We'll get this resolved shortly and included in the next update.
