### ISSUE TITLE
[Question / Feature Request] - Build LESS on Page Load

### ISSUE THREAD

**Issue by ingageco** [siteorigin/so-widgets-bundle#1119]
Hey Team - when developing widgets, it can be a slow process to get styling just right on the frontend when using LESS. If a change is made to the LESS, I have to edit the widget so the styles are regenerated. 

I understand the LESS is likely processed on page save, but it'd be great if there was a way to have the styles build on page load for development purposes. To my knowledge, this is not currently possible, but would help speed up writing the styles. To be clear, this is ONLY a suggestion for developers - otherwise, it would be silly. 

How does SiteOrigin go about writing their widget LESS? If this is somehow already possible, let me know!

**Comment by ingageco** [comment]
"Just use Preview* 🤣

**Comment by AlexGStapleton** [comment]
Hi Ingageco,

Another option would be to make the `wp-content/uploads/siteorigin-widgets` directory unwriteable. This will prevent SIteOrigin Widgets Bundle from storing the generated CSS so it'll regenerate it every page load and output it inline. This is effectively the same as a widget preview, but it'll allow you to preview it in the wider context of the full site without.

Kind regards,
Alex
