### ISSUE TITLE
How to better differentiate widget instances in PageBuilder?

### ISSUE THREAD

**Issue by pixeline** [siteorigin/so-widgets-bundle#113]
I'm using PageBuilder, and have created a widget with several options: title, layout, posts selector and a boolean (include a media icon or not). My client will mainly use that widget. 

All is fine, except on complex pages, the Editor is not much help as all widget instances display the same generic information.  Is there a way to have the PB in post edit screen use the widget instance options in its visible information?

Here is a printscreen to better visualize the usability issue. (And this is just a part of the screen that fit my laptop's viewport).

(Titre means "title" and Vignette means "thumbnail").  Thank you!

![capture d ecran 2016-02-21 22 55 04](https://cloud.githubusercontent.com/assets/393415/13205702/3abd1ab2-d8ee-11e5-8852-0ea3dd077316.png)

**Comment by AlexGStapleton** [comment]
The easiest solution that comes to mind, albeit a non-automatic one, would be to display any custom classes attached to a widget. To avoid clutter it might be a good idea to hide this data until hover if there's too much of it - depending on available width of course.

**Comment by braamgenis** [comment]
A recent Page Builder update made it possible to set row colors and edit row and widget labels (in the corresponding 'Edit' dialogs)
