### ISSUE TITLE
Slider compatibility issue with Full Frame theme

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#114]
[Issue was reported in this thread](https://siteorigin.com/thread/site-builder-doubles-slider-page-options-on-full-frame-theme/). Slider will "repeat" initial image when the user clicks previous, or next on slider. Local testing suggests conflict stems from so-widges-bundle/js/jquery.cycle.min.js and that slider doesn't "repeat" it just moves forwards (or backwards) twice. Meaning that the event is triggering twice. The issue is resolved when slider triggers are changed from cycle-prev and or cycle-next to something else.

**Comment by AlexGStapleton** [comment]
Oh, and btw. Default theme settings, and default plugin settings will work for replicating this issue.

**Comment by Misplon** [comment]
**Alex notes:**
Very likely as a result of a theme issue with the Cycle library we're likely both using. I haven't received a report since.

Closing for the mean time.
