### ISSUE TITLE
SiteOrigin Image: Stretching in Safari

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1152]
Related: https://github.com/siteorigin/so-widgets-bundle/issues/1141.

Images are stretched in Safari due to flexbox. Adding `flex-direction: column;` resolves the issue but I haven't tested to see if that might introduce other problems.

Ref: https://stackoverflow.com/questions/57516373/image-stretching-in-flexbox-in-safari

**Comment by AlexGStapleton** [comment]
`flex-direction: column;` vertically stretches the images in IE 11. How about `flex-direction: row;`? That doesn't result in any differences in IE 11. If that doesn't work I guess we could use [something like this](https://paper-leaf.com/insights/targeting-ie-10-11-browsers-css/) to target IE 11 directly.

**Comment by Misplon** [comment]
I'd be keen to revert our IE11 fix and instead try targetting IE directly as per https://paper-leaf.com/insights/targeting-ie-10-11-browsers-css/.
