### ISSUE TITLE
Button: Add download attribute

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1156]
Add a `download` attribute option to the Button widget. Wording and location to be determined.

**Comment by AlexGStapleton** [comment]
Should this be added below the "Open in new window" checkbox, or to the Other attributes and SEO group? If the latter, are you fine with adding it to the top of the settings?

How does this sound?

**Force download on click**
If the user is using a modern browser, the browser will attempt to download the linked destination URL.

**Comment by Misplon** [comment]
The location sounds good.

Would you perhaps be ok with:

**Download**
The button destination URL will be downloaded when a user clicks on the button.

We could perhaps to see if non-modern browsers are an issue moving forward and add that if necessary.
