### ISSUE TITLE
State emitters or handlers for showing / hiding not working correctly

### ISSUE THREAD

**Issue by stentibbing** [siteorigin/so-widgets-bundle#1167]
@AlexGStapleton 

With version 1.17.8-beta showing and hiding forms are not working correctly for me. Please see the form below.

https://pastebin.com/JJNRGv96

**Comment by AlexGStapleton** [comment]
Thanks. I've been able to replicate this issue and I've come up with a fix [here](https://github.com/siteorigin/so-widgets-bundle/pull/1168).
[Here's a build of that PR](https://github.com/siteorigin/so-widgets-bundle/files/5305962/so-widgets-bundle.1.17.9-beta.zip).
