### ISSUE TITLE
Multiple actions for _else state handler

### ISSUE THREAD

**Issue by stentibbing** [siteorigin/so-widgets-bundle#1169]
Hi

I need multiple actions for _else state handlers (hiding and deselecting). As far as I understand this currently is not possible without custom callback ?

Thanks!

**Comment by AlexGStapleton** [comment]
Hi stentibbing,

Unfortunately, It's only possible to specify one else as else can't evaluate to anything else to get passed the first else - in other words, if else else isn't possible.

If you're asking how to check for multiple conditions, you can [use the conditional callback](https://siteorigin.com/docs/widgets-bundle/form-building/state-emitters/#heading-the-conditional-callback). 

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi stentibbing,

I'm closing this due to inactiveity. Let me know if you still need help with this.

Kind regards,
Alex
