### ISSUE TITLE
 Post Carousel: Add Center Items settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1172]
We should add a setting that centers all visible items if the total number of items doesn't exceed the length of the page.

**Center Items**
Center items if the total number of posts is fewer than the length of the page.

Here's some example code of how this could be done:

CSS:
```
.center-carousel .slick-track[style] {
	display: flex;
	justify-content: center;
	width: 100% !important;
	transform: none !important;
}

.center-carousel .slick-slide {
	float: none;
}
```

Javascript:
```
jQuery( function ( $ ) {
	$( window ).on( 'resize load', function() {
		$( '.sow-carousel-wrapper' ).each( function() {
			var currentCarousel = $( this ),
				$items = currentCarousel.find( '.sow-carousel-items' ),
				numVisibleItems = Math.ceil( $items.outerWidth() / $items.find( '.sow-carousel-item' ).outerWidth( true ) );

			if ( numVisibleItems >= currentCarousel.data( 'post-count' ) ) {
				currentCarousel.addClass( 'center-carousel' );
			} else if ( currentCarousel.hasClass( 'center-carousel' ) ) {
				currentCarousel.removeClass( 'center-carousel' );
			}
		} );
	} );
} );
```

**Comment by nikospapageorgiou** [comment]
Alex, if it's possible to add this as an option, not default. In pages with multiple carousels in desktop mode, the centered mode maybe looks strange.
As an example, i have a page with 15 carousels for the student activities for the last 15 years. This year till now there are only 3 posts in the first carousel, aligned to left by default, and empty space after them. The centered mode will leave blank space, left and right, something strange for the visitor.
Maybe add the setting as default but only when a single carousel appears.
Thank u.

**Comment by AlexGStapleton** [comment]
Hi @nikospapageorgiou,

This functionality would be optional, and behind a setting that would be disabled by default. Having it to default to off by default will prevent any undesired changes after updating.

Kind regards,
Alex

**Comment by nikospapageorgiou** [comment]
That's fantastic. Thanks a lot Alex!
