### ISSUE TITLE
Hero: Save button isn't working in Safari at Appearance > Widgets

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1174]
The Hero Save button isn't working in Safari at Appearance > Widgets. There aren't any console errors present.

**Comment by AlexGStapleton** [comment]
This is going to be tricky to fix. I'm going to have to send you a build to test. I have a few questions:

- Is the Save button grey or blue?
- If the button is blue, does the widget start saving (as in, an actual server request is made), or does nothing happen when you click the Save button?
- If the widget starts saving, is there a PHP error?
- Does this happen with the other slider widgets, or is only the Hero widget affected?
- Does this happen while using the last WB update, or does this only happen while using release and/or develop?

**Comment by Misplon** [comment]
> Is the Save button grey or blue?
Blue

> If the button is blue, does the widget start saving (as in, an actual server request is made), or does nothing happen when you click the Save button?
Nothing.

> If the widget starts saving, is there a PHP error?
NA

> Does this happen with the other slider widgets, or is only the Hero widget affected?
Appears just to be the Hero.

> Does this happen while using the last WB update, or does this only happen while using release and/or develop?
Seems to persist using master or develop.
