### ISSUE TITLE
Hero: Background when linked isn't always clickable.

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#120]
The Hero widget background link is sometimes not clickable. Greg mentioned the problem might lie with the JavaScript nature of the background image link. 

Here is a user provided layout with the problem: https://dl.dropboxusercontent.com/u/3072682/GitHub%20Reference%20Files/layout-16022016.json. 

We have confirmed this locally.

**Comment by gregpriday** [comment]
Pretty easy fix, I'll handle this.
