### ISSUE TITLE
Post Carousel: Add Filter that allows you to limit the total number of displayed posts

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1210]
A few users have requested the ability to be able to limit the total number of posts displayed using the Post Carousel.

**Comment by AlexGStapleton** [comment]
Follow up: https://siteorigin.com/thread/post-carousel-widget-not-working-as-intended/

**Comment by nikospapageorgiou** [comment]
Hello! The default will remain as unlimited? Because the limit many times is set by date... (from -to...). Thank you

**Comment by AlexGStapleton** [comment]
Hi @nikospapageorgiou,

The default will remain unchanged. This filter will be optional and only adjustable via PHP. We may introduce a setting in the future that will allow you to limit the total of posts that can show, and that will also be optional.

The linked thread is unrelated to time filtering. They're after a way to limit the total number of posts that can be shown using the Post Carousel, and that's what this PR aims to allow them to do.

Kind regards,
Alex

**Comment by nikospapageorgiou** [comment]
Thanks Alex
