### ISSUE TITLE
Post Carousel: Add Description to Posts Per Load setting

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1211]
The Posts Per Load setting, even after the rename, is a tad vague. We should add a description to the setting that explains that this setting is how many posts are displayed before new posts are loaded.

**Comment by AlexGStapleton** [comment]
@Misplon Do you have any suggestions?

**Comment by Misplon** [comment]
How about:

_Set the number of posts preloaded when clicking next. The default is 15._

**Comment by nikospapageorgiou** [comment]
@Misplon Andrew i have the latest version and if i'm not wrong the default is 10 posts per load

**Comment by AlexGStapleton** [comment]
I can confirm the default is actually 10 - I had misremembered when I mentioned this over Slack.

https://github.com/siteorigin/so-widgets-bundle/blob/1.17.10/base/inc/post-selector.php#L15
