### ISSUE TITLE
Contact Form: Incorrect error message conflict with WordPress SEO

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#122]
Reference thread: https://wordpress.org/support/topic/contact-form-widget-3?replies=22#post-8084360

andreadelriva reporting that the contact form in question is posting an error message despite the form successfully sending. User narrowed plugin conflict to WordPress SEO.

**Comment by Misplon** [comment]
Have confirmed in local testing. Message already sent error is produced by the form widget when WordPress SEO is activated. Thanks guys.

**Comment by AlexGStapleton** [comment]
WordPress SEO seems to work when Twitter Card and (Facebook) Open Graph are disabled in the social menu. :confused:  Both of those features use the get_the_excerpt() function (only if they're set by the user) that if removed will resolve the issue. Both are hooked to the template_redirect action. A test function mimicking said hook can cause the same issue so this isn't limited to just Yoast. With that said, it still sends the message so it's not the end of the world - just bad UX.

`function show_contact_error(){
	$excerpt = get_the_excerpt();
}
add_action( 'template_redirect', 'show_contact_error' );

`

Hopefully, this helps.

**Comment by gregpriday** [comment]
Is this not fixed in the 1.5.9 release?

**Comment by AlexGStapleton** [comment]
Issue is unrelated as I was able to duplicate it with the latest version.

**Comment by gregpriday** [comment]
Great, I'll take a look.

**Comment by gregpriday** [comment]
For some reason, Yoast SEO being active causes the sending action to be called multiple times. So this is more than likely what was causing the issue we saw where people complained about not getting the email. So in this case, the hash is actually doing its job. The message is sent on the first try, and then all the subsequent attempts are blocked by the hash.

No idea why Yoast is doing this. I'll investigate. But, despite the error message, the contact message is still being sent.

**Comment by gregpriday** [comment]
All fixed up. This might also fix the Recaptcha issue we've seen with Yoast. Can anyone test that?

**Comment by Misplon** [comment]
SO Contact Form widget is showing **Message already sent error** on first send due to a conflict with Yoast SEO. Confirmed this is still happening with:

Yoast SEO: Version 3.1.2
SiteOrigin Widgets Bundle: Version 1.5.9
Page Builder: Version 2.4.2

**Comment by Misplon** [comment]
@gregpriday Confirmed that the ReCaptcha issue is still occurring. 

**Error validating your Captcha response.**
