### ISSUE TITLE
Attach icons to an i element rather than a span

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#123]
For all intensive purposes, i has pretty much become the icon element. I can't think of a good way to formulate this post so I'm going to post a small list instead.
- If I need to target an icon I'm going to be looking for that over a span.
- span is used for more than just icons and with plugins like SiteOrigin CSS unfamiliar users may apply CSS to a span and unknowingly affect icons.

This thread is partly due to [this thread](https://siteorigin.com/thread/why-do-several-icons-not-load-once-i-change-the-websites-font/). The user wants to globally change the font and is having a hard time doing so due to icons not having a dedicated element.

**Comment by braamgenis** [comment]
Leaving this open, but unlikely to make this change soon. The argument of `<i>` vs `<span>` still seems open ended. We should consider this again in future when there's a stronger bias towards one of the two.

**Comment by gregpriday** [comment]
I remember changing from `i` to `span` in our themes, because an empty `i` tag gave some SEO warnings. Was probably Origami.

Not sure if that SEO analysis tool was being entirely fair, but still, strictly `i` is for italics, not icon. Span is more generic so I'd vote to stick to that.
