### ISSUE TITLE
Shortcodes Ultimate: Unable to Insert Shortcode

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1247]
A premium user has reached out about [Shortcode Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/) (800k) no longer being able to insert the shortcode in the SiteOrigin Editor widget. I've been able to verify this issue.

<img width="265" alt="2021-02-15_02-35-01-1418" src="https://user-images.githubusercontent.com/17275120/107882665-69dde900-6f36-11eb-97d5-b2d244180a46.png">

**Comment by AlexGStapleton** [comment]
This issue does not occur in the Block Editor.

I've identified the cause of this issue, and unfortunately, I'm not too sure if this is something we can fix. Shortcode Ultimate uses the following code to insert the shortcode in the Classic Editor:

```
self.state.wpActiveEditor = window.wpActiveEditor
window.wpActiveEditor = self.state.insertArgs.editorID
window.wp.media.editor.insert(shortcode)
window.wpActiveEditor = self.state.wpActiveEditor
```

The issue occurs due to **window.wpActiveEditor = self.state.insertArgs.editorID**. Specifically, **window.wpActiveEditor** at this point equals (for example): widget-sow-editor-c33-text**458** but for whatever reason **self.state.insertArgs.editorID** equals to widget-sow-editor-c33-text (no numbers). I've checked over the rest of the Shortcode Ultimates code and it's unclear where the **editorID** is coming from so I'm unsure how to correct it. Strangely, if I remove the relevant line the shortcode works as expected so it's unclear why wpActiveEditor is being overridden (although I'm sure I'm missing something obvious).

**Comment by Misplon** [comment]
We've let the author know about the issue. Shortcodes Ultimate isn't hosted on GitHub or similar so we're limited in how much we can assist at this time.

**Comment by vanokhin** [comment]
Hi @AlexGStapleton and @Misplon,

I've just fixed the issue. Thank you for pointing this out. I'll release the fixed version within a week.

> Strangely, if I remove the relevant line the shortcode works as expected so it's unclear why wpActiveEditor is being overridden (although I'm sure I'm missing something obvious).

In short, it was used for textarea fields, like in SU widget:

![13-06-2021@17-49-55](https://user-images.githubusercontent.com/1898673/121812373-41f65c00-cc70-11eb-9bff-c0ebad7175c8.png)

**Comment by AlexGStapleton** [comment]
Hi @vanokhin,

That's great to hear! :)
I'm going to close this issue as it's effectively resolved.

> In short, it was used for textarea fields, like in SU widget:
Thanks for letting me know. That does make sense.

Kind regards,
Alex

**Comment by Misplon** [comment]
Hi @vanokhin. Super, thanks for attending. If any SiteOrigin related questions or requests arise in the future, please, let us know via email or GitHub if that's better suited.

Cheers for now :)
