### ISSUE TITLE
Video widget does not add playsinline attribute when autoplay is true

### ISSUE THREAD

**Issue by frafor1988** [siteorigin/so-widgets-bundle#1248]
Hi there,

Just wanted to tell that the Video widget should add the playsinline attribute, otherwise videos won't autoplay on iPhone even if muted.

As a quick workaround, who's facing this issue can use this code in theme's functions.php

```
add_filter("siteorigin_widgets_template_html_sow-video", "sopb_video_filter", 10, 3);
function sopb_video_filter($template_html, $instance, $widget){
  $template_html = str_replace('autoplay="1"', 'autoplay="1" playsinline ', $template_html);
  return $template_html;
}
```

**Comment by AlexGStapleton** [comment]
Hi,

Thank you for reporting this issue. This issue will be fixed in an upcoming update. 

https://github.com/siteorigin/so-widgets-bundle/pull/1249

Kind regards,
Alex
