### ISSUE TITLE
Widget Block: Check that color picker is working normally

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1289]
@AlexGStapleton In Twenty Twenty One in the Icon widget is the color picker working normally for you?

<img width="1053" alt="02" src="https://user-images.githubusercontent.com/789159/116782718-16862c00-aa8b-11eb-9bf5-433b986d84ca.png">

**Comment by AlexGStapleton** [comment]
It's appearing for me. Checked Icon, Button, and Headline.

![Screenshot_2021-05-03 Edit Page ‹ SiteOrigin — WordPress](https://user-images.githubusercontent.com/17275120/116818559-6231f600-abaf-11eb-9a29-df85ae0e3ff4.png)

Are you able to replicate this on a different site?

**Comment by Misplon** [comment]
Thanks for checking, if the issue isn't presenting for you, let's leave it for now.
