### ISSUE TITLE
Contact Widget - If no subject is defined message won't send

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#129]
If no subject is set as a default, and there's no subject input - the message won't send. This would be okay if it was communicated to the admin. Right now the only way to know it's not sent is to actually fill out the form.

Either set a default subject (Sitename contact form), or make it more apparent messages can't be sent without a subject / default subject.

**Comment by gregpriday** [comment]
Nice find, my guess is this might have caused quite a few of the issues we've been seeing.
