### ISSUE TITLE
Improve Slider Background Video Autoplay Description

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#1299]
The [current description](https://github.com/siteorigin/so-widgets-bundle/blob/1.18.2/base/inc/widgets/base-slider.class.php#L161) isn't very clear that normal videos will autoplay regardless of this setting so we should mention this.

**Comment by Misplon** [comment]
@AlexGStapleton how about:

`Currently, autoplay can only be disabled for YouTube videos.`

**Comment by AlexGStapleton** [comment]
I'm not a fan of the word "currently" as this setting can't be extended to support normal videos as it's not possible to adjust autoplay on a per-source basis.
