### ISSUE TITLE
Slow Query on select

### ISSUE THREAD

**Issue by vinvin27** [siteorigin/so-widgets-bundle#1300]
Hello there,

Im facing a huge performance issue when using so-widget-bundle. I installed Debug Monitor plugin and found a slow query.
To reduce the loading time, I reduce the number of display posts. My page use "Post List Widget" 
`SELECT post_id, meta_key, meta_value
FROM wp_postmeta
WHERE post_id IN (810202,816320,818495,820987,823013,831387,833804,836133,838881,840932)
ORDER BY meta_id ASC`

`update_meta_cache()
wp-includes/meta.php:1061
update_postmeta_cache()
wp-includes/post.php:7162
update_post_caches()
wp-includes/post.php:7145
_prime_post_caches()
wp-includes/post.php:7527
WP_Query->get_posts()
wp-includes/class-wp-query.php:3029
WP_Query->query()
wp-includes/class-wp-query.php:3465
query_posts()
wp-includes/query.php:98
SiteOrigin_Widget->widget()
wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php:219
SiteOrigin_Panels_Renderer->the_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:558
SiteOrigin_Panels_Renderer->render_widget()
wp-content/plugins/siteorigin-panels/inc/renderer.php:870
SiteOrigin_Panels_Renderer->render_cell()
wp-content/plugins/siteorigin-panels/inc/renderer.php:838
SiteOrigin_Panels_Renderer->render_row()
wp-content/plugins/siteorigin-panels/inc/renderer.php:764
SiteOrigin_Panels_Renderer->render()
wp-content/plugins/siteorigin-panels/inc/renderer.php:344
SiteOrigin_Panels->generate_post_content()
wp-content/plugins/siteorigin-panels/siteorigin-panels.php:337
apply_filters('the_content')
wp-includes/plugin.php:212
the_content()
wp-includes/post-template.php:253 `

**Comment by AlexGStapleton** [comment]
Hi vinvin27,

The provided query looks to be a fairly generic query rather than something specifically linked to our plugins - we're not using `update_postmeta_cache` in the Widgets Bundle or Page Builder plugins. Does this query occur if the only widgets present are Widget Bundle widgets?

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi vinvin27,

Just reaching out to see how you're going with this. Do you still need a hand with this?

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi vinvin27,

Thanks for checking. Widgets can result in additional queries that are independent of Page Builder. This means that while the widget is being added by Page Builder, we don't really have any control or the underlying query. I recommend reaching out to the author of that widget for assistance with the slow query.

Kind regards,
Alex

**Comment by vinvin27** [comment]
Oh ok, thank you Alex I will do that ;-)

**Comment by AlexGStapleton** [comment]
Okay cool. Let me know how you go mate. :)

I'm going to close this issue as the slow query isn't linked to Page Builder.
