### ISSUE TITLE
Can't access template variables in widget template

### ISSUE THREAD

**Issue by JanNovakFRI** [siteorigin/so-widgets-bundle#1302]
Hello, I can not access returned variables from `get_template_variables` in widget template. Is there anything I am doing wrong?

In custom widget I extended `get_template_variables` method:
```

	function get_template_variables( $instance, $args ) {
		return array(
			'image' => wp_get_attachment_image_src( $instance['image'], 'large' )[0]
		);
	}

```

What I get if I var_dump `$args` in widget template:

```

  'before_widget' => string '<div id="panel-12-1-0-0" class="so-panel widget widget_tic-parallax-image panel-first-child panel-last-child" data-index="1" >' (length=126)
  'after_widget' => string '</div>' (length=6)
  'before_title' => string '<h3 class="widget-title">' (length=25)
  'after_title' => string '</h3>' (length=5)
  'widget_id' => string 'widget-1-0-0' (length=12)
```

**Comment by AlexGStapleton** [comment]
Hi,

`$Instance` contains the setting values of the current widget instance.
`$args` contains the widget args for the current widget - these are added when the widgets are inserted and typically not managed by the user.

Kind regards,
Alex
