### ISSUE TITLE
Default icon in field Icon with custom font families (without that icon) prevent init

### ISSUE THREAD

**Issue by mamarmite** [siteorigin/so-widgets-bundle#1309]
I've installed the premium widgets and accordeon have default value for headings.

My setup have the font awesome pro installed, and all the other remove.

That make the field not init for the close and open icon because the accordeon have default icon that is in the fontawesome normal.

To fix this I add that check in the icon field (Line 26, in `render_field` function)
```php
if ( ! empty( $value ) && array_key_exists( $value_parts['family'], $icon_families_styles ) ) {
```
I can make a PR .

**Comment by mamarmite** [comment]
Ok, I prepared a PR : https://github.com/mamarmite/so-widgets-bundle/tree/icon-field-default-icon-fix

**Comment by AlexGStapleton** [comment]
Hi @mamarmite,

Thanks mate. :)
Can you please submit that fork as a PR? This will allow us to test and comment on via the main repo directly before merging.

I can see the reasoning behind this change and why it would help but to really test it I need to be able to replicate the base error. Can you please provide me with the code you're using to unset icons and add the font* so I can replicate your setup more closely?

* I understand that for licensing reasons, you can't provide the font itself.

Kind regards,
Alex

**Comment by mamarmite** [comment]
Hi @AlexGStapleton ,
You're welcome!
The PR has been added : #1311 with my point of view to replicate the issue.

Let me know If I can do anything :)
