### ISSUE TITLE
Contact Widget - Hash Check always fails

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#131]
Well, this explains a lot of the issues I've been seeing lately. The contact form will only ever work once. This is due to the hash check will always fail due to the hash being overridden with an already "logged" hash. This happens [here](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/contact/contact.php#L958).

**Comment by gregpriday** [comment]
Very nicely spotted. Have a fix ready to go, just doing some testing.

**Comment by AlexGStapleton** [comment]
My precious priority one label. :sob:
