### ISSUE TITLE
Post Carousel: Automatically loop back to start when the end has been reached

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#132]
[Suggested in this thread](https://siteorigin.com/thread/posts-carousel/)

The post carousel widget doesn't loop automatically. As soon as the user has navigated to the end of the carousel you're able to keep navigating through blank "posts" until the final actual post is the last one visible. Then, nothing. Clicking the next arrow doesn't affect the widget at all.

It should loop from the start,  or transition back to the start of the loop.

**Comment by gregpriday** [comment]
Another solid enhancement.

**Comment by Misplon** [comment]
Still relevant.

**Comment by sandy2609** [comment]
Its open from last 3 years, Can you please look into this, I have no. of sites using siteorigin and this small issue causing big problems.

**Comment by gregpriday** [comment]
Thanks for bringing this up @sandy2609. I've added this enhancement in our dev version, so it'll be available in the next update.
