### ISSUE TITLE
Post Carousel Widget: Try improve next slide load time

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#133]
To replicate users setup, ensure only 6 posts are added to a Carousel widget. Click the next arrow. Ideally, the 5th thumbnail should appear as soon as there is a space available. At the moment it takes three clicks of the right arrow to load the 5th slide, ideally, it would be one, as soon as there is a space it would load.

**Comment by braamgenis** [comment]
@Misplon Sorry if I'm misunderstanding, but this sounds like an enhancement rather than a bug? Please let me know if I'm missing something.

**Comment by Misplon** [comment]
This "issue" is still present. Enhancement it is. Thanks @braamgenis.
