### ISSUE TITLE
Block Editor: Check if the accordion icons display in preview before first save

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1363]
@AlexGStapleton When able, please, try adding a Widget Block then add an Accordion with a few items. When previewing, do the plus icons display? Or do the plus icons only display in preview after saving the page?

**Comment by AlexGStapleton** [comment]
I can confirm I'm seeing the icons when previewing the Widgets Block prior to saving. Are you using a release build? I ask as if you're using an older version (or branch) that was made prior to https://github.com/siteorigin/so-widgets-bundle/pull/1284 the icons won't appear.

Can you reply with a screenshot of what you're seeing?

**Comment by Misplon** [comment]
Ahh yeah, my bad, all good in develop!
