### ISSUE TITLE
Hero: Font Color has no effect due to hero CSS being generated with color not set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#145]
If you set the font color via the widget styles options it has no effect due to another color being applied directly to the hero paragraphs. This other color isn't set anywhere in the widget itself.

![capture](https://cloud.githubusercontent.com/assets/17275120/13827138/b1ef2ec4-ec06-11e5-9369-9c95f9fed174.PNG)

**Comment by braamgenis** [comment]
@AlexGStapleton I can't remove the style being applied by the Hero widget, as that will break it for other users, so Page Builder widget styles still won't have any effect, but I've added fields in the widget form so the text and heading colors can be set.

**Comment by AlexGStapleton** [comment]
Would it be possible to hide the option in the widget styles view? That way it won't have a chance of causing confusion.

I've seen a couple of requests for separate colors / controls for headers and paragraphs, so it's a good change regardless.

**Comment by braamgenis** [comment]
I suppose we might be able to have the Hero widget filter out the font color widget style field. I'll create a separate issue to look into it. It's possible that other widgets will have the same problem, so please keep an eye out and create issues for them if they do. Thanks!
