### ISSUE TITLE
Anything Carousel - Arrows missing after recent update.

### ISSUE THREAD

**Issue by SmashBrando** [siteorigin/so-widgets-bundle#1469]
I noticed after 1.32.0 that the arrows for the Anything Carousel widget are now missing. The HTML is still there but the arrow and space for the arrow is missing. 

I've created a vanilla WordPress install here - https://telling-bead.flywheelsites.com/ for testing.

Site Health info below:

### wp-core ###

version: 5.9.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /wordpress
wordpress_size: 46.78 MB (49055520 bytes)
uploads_path: /www/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: /www/wp-content/themes
themes_size: 10.82 MB (11344731 bytes)
plugins_path: /www/wp-content/plugins
plugins_size: 8.85 MB (9281085 bytes)
database_size: 2.17 MB (2277376 bytes)
total_size: 68.63 MB (71958712 bytes)

### wp-dropins (1) ###

db-error.php: true

### wp-active-theme ###

name: SiteOrigin Corp (siteorigin-corp)
version: 1.19.0
author: SiteOrigin
author_website: https://siteorigin.com/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, title-tag, post-thumbnails, custom-logo, menus, html5, post-formats, custom-background, editor-styles, customize-selective-refresh-widgets, siteorigin-template-settings, siteorigin-premium-ajax-comments, siteorigin-premium-no-attribution, widgets
theme_path: /www/wp-content/themes/siteorigin-corp
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty: version: 1.9, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Two: version: 1.1, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (3) ###

Classic Editor: version: 1.6.2, author: WordPress Contributors, Auto-updates disabled
Page Builder by SiteOrigin: version: 2.16.6, author: SiteOrigin, Auto-updates disabled
SiteOrigin Widgets Bundle: version: 1.32.1, author: SiteOrigin, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.6.0
file_uploads: File uploads is turned off
post_max_size: 300M
upload_max_filesize: 300M
max_effective_size: 300 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 51 GB
	imagick::RESOURCETYPE_DISK: 1.844674407371E+19
	imagick::RESOURCETYPE_FILE: 786432
	imagick::RESOURCETYPE_MAP: 51 GB
	imagick::RESOURCETYPE_MEMORY: 25 GB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.0
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: unknown
httpd_software: Flywheel/5.1.0
php_version: 7.4.28 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 178
memory_limit: 256M
max_input_time: 60
upload_max_filesize: 300M
php_post_max_size: 300M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.36-google
client_version: mysqlnd 7.4.28
max_allowed_packet: 33554432
max_connections: 4030

### wp-constants ###

WP_HOME: http://telling-bead.flywheelsites.com
WP_SITEURL: http://telling-bead.flywheelsites.com
WP_CONTENT_DIR: /www/wp-content
WP_PLUGIN_DIR: /www/wp-content/plugins
WP_MEMORY_LIMIT: 256M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: not writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

**Comment by Misplon** [comment]
Hi Brandon

Thanks for the wait. The issue should be resolved by Widgets Bundle version 1.32.2. When you have a moment, perhaps try updating and let us know it goes.

https://github.com/siteorigin/so-widgets-bundle/releases/tag/1.32.2

Thanks

Andrew
