### ISSUE TITLE
Google Maps PHP notice when "Static Image" map type is selected

### ISSUE THREAD

**Issue by timeav** [siteorigin/so-widgets-bundle#1517]
Hi,
In the latest version of the Widgets Bundle (1.35.1) I'm getting this PHP notice:

```
Notice
: Trying to access array offset on value of type bool in
/wp-content/plugins/so-widgets-bundle/widgets/google-map/google-map.php
on line
794
```
I discovered this while I was trying to display a Static image instead of an interactive map. 
PHP version is 7.4.29

**Comment by AlexGStapleton** [comment]
Hi Timeav,

Thank you for the report! :)
This has been resolved by https://github.com/siteorigin/so-widgets-bundle/pull/1525 which will be included in a future SiteOrigin Widgets Bundle update.

Kind regards,
Alex
