### ISSUE TITLE
Feature: add filter to change query args in siteorigin_widget_action_search_posts query

### ISSUE THREAD

**Issue by sitoagency** [siteorigin/so-widgets-bundle#1528]
Hi!

A client of mine just noticed that the order of the posts in the content selector list was weird and I couldn't understand why. One could assume that the list comes ordered by post_date, however after a bit of digging I noticed it's ordered by post_modified in siteorigin_widget_action_search_posts.

So i had filtered the result via siteorigin_widgets_search_posts_results and re-run the query.

While this works, it is suboptimal, as it wastes 1 db call.

Couldn't you guys just add a filter for the arguments used by the query in the function, before to call $wpdb->get_results?

**Comment by frafor1988** [comment]
great & super fast, thanks!

**Comment by Misplon** [comment]
Thanks, Francesco! We'll have a SO Widgets Bundle release out before Sunday.

Cheers

Andrew
