### ISSUE TITLE
Contact: Add ability to customize email sent to contact email

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#155]
[Requested in this thread](https://siteorigin.com/thread/siteorigin-contact-form-6/)

It would be nice to have the ability to adjust the email sent to you when you receive a new contact form submission. It should be in the style of a mad lib with reference to either field labels, or an id field (which would have to be added).

**Comment by Misplon** [comment]
@AlexGStapleton Please, could you log in premium for us with type and prio labels and close here when done?
