### ISSUE TITLE
Google Maps: Can't set width of static map

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#157]
This is also very likely an issue. When using the static map, the width of the map isn't being taken into account. It's added to the URL of the static map, but the static map is displaying a 640px wide image, instead of the 800px set.

https://maps.googleapis.com/maps/api/staticmap?center=cape+town&zoom=14&size=800x455&markers=cape+town

Maybe the arguments have changed somewhere? Also possible this is a temporary Google Maps issue.

**Comment by braamgenis** [comment]
This is due to a limitation imposed by the API. Image sizes are [limited](https://developers.google.com/maps/documentation/static-maps/intro#Imagesizes) for users of the free API to `640x640`. If they want bigger images they'll have to sign up to the Google Maps APIs Premium plan.

**Comment by jserrao** [comment]
This should really be pointed out in the docs, spent quite awhile thinking I was nuts.
