### ISSUE TITLE
Anything Carousel: Navigation with arrows and drag/touch seems broken

### ISSUE THREAD

**Issue by FantasyTeddy** [siteorigin/so-widgets-bundle#1572]
With the current version of the Widget Bundle (1.38.2) I have the following behavior:

- The navigation with the dots works just fine.
- When using the arrows, the items start jumping seemingly randomly or disappear.
- When dragging or using touch input, the behavior is the same as with the arrows.

After a few random clicks in the carousel, I can even get my page to freeze.

**Comment by Misplon** [comment]
Hi, thanks for letting us know. Does the issue persist if you copy the widget and insert it into a new page as the only widget on the page?

**Comment by FantasyTeddy** [comment]
Thank you for the fast response.

I was able to narrow it down: everything works in a vanilla WordPress installation. However as soon as I install the [Sydney theme](https://athemes.com/theme/sydney/) and activate it, the problem appears.
Can I maybe deactivate something within the theme to prevent it from interfering with the carousel?

**Comment by Misplon** [comment]
Nicely done narrowing the problem down. We'll take a look ASAP tomorrow and get back to you with a solution.

**Comment by FantasyTeddy** [comment]
Thank you very much for your fast support.

Yes the issue is gone with the patched version, perfect!
