### ISSUE TITLE
'Multiple' attribute on select field (suggestion)

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/so-widgets-bundle#16]
It'd be great to be able to select multiple options on the select field.

Btw somewhat related- the docs say not to bother attempting custom fields yet, is this still the case?

**Comment by SteveS123** [comment]
I just noticed the doc update with the 'multiple' addition, very nice!

**Comment by braamgenis** [comment]
Hi Steve

There was a bit of a mix up and unfortunately the docs have been updated a bit prematurely. The Widgets Bundle containing the multiple select field option is coming soon, but has not been released yet. If you're on one of the SiteOrigin mailing lists you'll be notified when the release is ready. Sorry for the confusion.

**Comment by SteveS123** [comment]
No worries, glad to see it's on the roadmap.
