### ISSUE TITLE
Contact Form: Yoast SEO causes Captcha to not validate

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#160]
Yoast SEO is causing the captcha to not validate:

_Error validating your Captcha response._

**Comment by gregpriday** [comment]
Think the only solution to get the Contact Form widget working more consistently will be to use an `admin-ajax.php` action to handle the contact form request.

**Comment by AlexGStapleton** [comment]
Does this issue resolve itself in the most recent dev version? It's possible it's related to #122

**Comment by braamgenis** [comment]
Can anyone reproduce this? Also, can we confirm that whoever this happened to was using the latest Widgets Bundle 1.5.9?

**Comment by Misplon** [comment]
@braamgenis Confirmed with:

Yoast SEO: Version 3.1.2
SiteOrigin Widgets Bundle: Version 1.5.9
Page Builder: Version 2.4.2

**Comment by braamgenis** [comment]
Ugh. :confounded: Ok, will dig into this. Thanks @Misplon :+1:

**Comment by gregpriday** [comment]
This might be fixed in today's update. Fixed the code that was preventing
double requests to the contact form action.

**Comment by braamgenis** [comment]
That would make me so happy.
