### ISSUE TITLE
Post (query builder) UX: Add tooltip (or description) to explain what a taxonomy is

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#163]
I've noticed that a lot of people seem to ignore the taxonomies setting in the query builder, and I've realised why. Unless you're an experienced user or a developer you don't know what a taxonomy is in WordPress.

To avoid confusion, it would be a good idea to explain in simple terms what it is. Even a basic, "A taxonomy is a category, tag, etc).

Alternatively, renaming it to something more obvious, while a tad overkill, would also resolve the issue.

**Comment by Misplon** [comment]
@AlexGStapleton Do you perhaps want to submit a PR with a short description line?

**Comment by AlexGStapleton** [comment]
Before committing anything I'm going to suggest a few possible options:

Taxonomies are what WordPress uses to group things together. Posts, categories, etc, are all taxonomies.
Taxonomies are the term used by WordPress to describe a group.
Taxonomies are groups. Such as a category, tags, posts, products, etc.

I'm trying to be as brief as possible while also actually explaining it. Any thoughts?

**Comment by Misplon** [comment]
`Taxonomies are groups. Such as a category, tags, posts, products.`
