### ISSUE TITLE
Simple Masonry: Undefined array key "enabled"

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#1641]
`Warning: Undefined array key “enabled” in /wp-content/plugins/so-widgets-bundle/widgets/simple-masonry/simple-masonry.php on line 295`

A user reported warning from the forum. Thanks, mate.

https://siteorigin.com/thread/widget-mansonery/

**Comment by AlexGStapleton** [comment]
This was resolved [here](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/simple-masonry/simple-masonry.php#L404) by https://github.com/siteorigin/so-widgets-bundle/commit/2d077d4a1962c72dcd925651c3718d078f654e66. This change hasn't been released yet.
