### ISSUE TITLE
Hero Widget: When destination URL is set nested anchor images do not function

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#165]
If a user adds a basic HTML img nested in an anchor in a hero widget frame the link won't work. When clicked it won't function. This only happens when a Background Destination URL is defined.

[Reference Layout](https://u.teknik.io/tSfA6.json)

**Comment by braamgenis** [comment]
I'm guessing that's because browsers don't really like having `<a>` tags inside other `<a>` tags. I saw a nice workaround for this recently, so it's really cool to have an opportunity to try it out. Most appreciated. :+1: :smile:

**Comment by AlexGStapleton** [comment]
Oh. I thought it was an overlay rather than a full on anchor wrap. It might be a better idea to switch to an overlay as I've seen people include full on paragraphs in hero widgets. (ie. stuff that should never be nested)

**Comment by braamgenis** [comment]
It was a quick guess, without looking at the source. :stuck_out_tongue_closed_eyes:  It might well be an overlay or similar. I'll know for sure when I dig in and start work on this.

**Comment by AlexGStapleton** [comment]
ah okay then. :elephant:
