### ISSUE TITLE
Hero Widget: Maximum container width no display problem

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#167]
When the Maximum container width field is left blank, the Hero widget doesn't display. Perhaps 100% should be used in the background if this field is left blank?

**Comment by braamgenis** [comment]
@Misplon Could you provide more details on how to reproduce? I cleared all the width, height and padding fields and the widget displays fine for me. It's possible this has been fixed in the latest release.

**Comment by Misplon** [comment]
@braamgenis I was able to confirm before logging the bug. I tried again today and am unable to reproduce. Looks like we've resolved the problem. Thanks for taking a look.

**Comment by braamgenis** [comment]
Awesome. :smile:
