### ISSUE TITLE
Hero Widget: Problem with height and padding in percentage

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#168]
Set a height in the Hero widget and then add top and bottom padding in px. The height you set is respected. However, when we change to top and bottom padding in percentage, the height value is no longer respected.

**Comment by braamgenis** [comment]
@Misplon Is this still a problem for you? I can't seem to reproduce anymore.

**Comment by Misplon** [comment]
Gone! Winning.
