### ISSUE TITLE
Content disappears from Editor field when widget reordered

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/so-widgets-bundle#17]
Congrats on the 1.3 rollout!  I noticed a bug with the new Editor field-

- Drag a SiteOrigin Editor widget into a region, add content to it.
- Drag a second SiteOrigin Editor widget into the same region, add content to it.
- Drag the second widget so it's above the first.

The content should disappear from the widget you just dragged.

**Comment by gregpriday** [comment]
Nicely spotted! Yeah, I'm sure there will be a few little niggles with this new field. It really was a big one. Let's see if @braamgenis can recreate and fix this.

**Comment by braamgenis** [comment]
Fixed in 1.4 release.
