### ISSUE TITLE
Can state emitter/handler be used to update a select field's options? 

### ISSUE THREAD

**Issue by ingageco** [siteorigin/so-widgets-bundle#1702]
Hey team - can a state emitter & handler be used to update a field's options? I'm looking to use one field to filter options in another (select) field. 

Ideally the change would trigger a WP filter that would provide new options, rather than just filtering existing options. 

Thank you!

**Comment by AlexGStapleton** [comment]
Hi @ingageco,

This can be done by [creating a custom callback](https://siteorigin.com/docs/widgets-bundle/form-building/state-emitters/#heading-custom-callbacks) and [filtering the form](https://github.com/siteorigin/so-widgets-bundle/pull/1653) as needed.

Kind regards,
Alex

**Comment by ingageco** [comment]
Thank you @AlexGStapleton !
