### ISSUE TITLE
Maps: Default to a height if no height is set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#174]
When no height is set, the Map will still be output it just won't be visible. This isn't exactly clear so to some it might seem as though the widget isn't working. It might be a good idea to "default" to a height to avoid confusion.

**Comment by braamgenis** [comment]
The maps widget height field has a default value of 480px. So a user would have to clear it intentionally for it to be blank. It would be nice if we could replace that field with the measurement field to allow any units for height, but I think it's somewhat dependent on the Google Maps JS API.

**Comment by AlexGStapleton** [comment]
Yeah, that's the weird thing. A user did clear it and was wondering why it wasn't working. :confused: I think we should at least enforce a height if the field is empty.
