### ISSUE TITLE
Measurement fields result in repeater item duplication.

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#178]
This issue has come up since we added a measurement field to the button widget in https://github.com/siteorigin/so-widgets-bundle/pull/159

The Hero Image widget has buttons as part of a repeater for a frame.

Steps to recreate:
1. Create a new page and insert a Hero Image widget
2. Add a frame (no content required), then add at least one empty image to that frame.
3. Save the page

You'll see that there are now 2 frames, even though only one was added. Commenting out the new [width field](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/button/button.php#L87-L91) from the button form fixes the issue.

I came across a similar issue when working on the `builder` field. At first, it had 2 input fields like the measurement field. This caused an extra repeater item to be created if the repeater had a builder field. Eventually I got around this by making the builder field use a single input.

**Comment by gregpriday** [comment]
Same thing happens in the standard WordPress widgets interface, so it's not Page Builder specific.

**Comment by braamgenis** [comment]
When you say "empty image" I assume you mean "empty button". :stuck_out_tongue:
