### ISSUE TITLE
social media widget: add tripadvisor

### ISSUE THREAD

**Issue by platschi** [siteorigin/so-widgets-bundle#18]
Hey, it would be great to add Tripadvisor within the "Social Media" widget, and letting the user simply provide a link to his/her business or Tripadvisor. Very useful for anybody working in the touristic sector.

**Comment by braamgenis** [comment]
:boom: Wish granted. This will be included in the next Widgets Bundle release.

**Comment by platschi** [comment]
awesome, many thanks!
