### ISSUE TITLE
Hero: Unable to embed Wistia video as background video

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#183]
As the title suggests you're unable to embed a Wistia video as a background video. Obviously, that's not the best platform for video backgrounds (it's meant for content) but it's something we should really support regardless due to how popular that platform is becoming.

For an example embed URL please see ticket #3334 on Help Scout.

**Comment by braamgenis** [comment]
We're using the built-in WordPress oEmbed support for this, and unfortunately Wistia isn't supported yet. https://codex.wordpress.org/Embeds#Okay.2C_So_What_Sites_Can_I_Embed_From.3F

**Comment by AlexGStapleton** [comment]
Oh that's weird. Wista has oEmbed support in WordPress.com and not WordPress.org. How odd. :confused:

**Comment by braamgenis** [comment]
Yeah, that's especially strange... but the good news is, we won't have to do anything to include Wistia if/when they do decide to include it.
