### ISSUE TITLE
Image Grid: Default Spacing value mismatch

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/so-widgets-bundle#189]
In form option `/so-widgets-bundle/widgets/image-grid/image-grid.php`, default value is set to `10`. But in less file it is `20px`. This should be same I believe.

**Comment by braamgenis** [comment]
@ernilambar Was this causing an issue for you? The value in the LESS file is really just a placeholder to ensure the syntax is valid and can be compiled independently. The default value in the php file should override it.

**Comment by ernilambar** [comment]
Yes. May be fixing https://github.com/siteorigin/so-widgets-bundle/issues/188 will resolve this. `0` was not saved. And I was expecting `10px` in the front end but it came `20px`. This does not make sense I believe. It would be good to have same default I guess.

**Comment by braamgenis** [comment]
Ah, so it's a bit more complicated. It's not using the value in the LESS file, it's actually double the default value in the php file. It's using the 'spacing' value as padding around images, so the space between images is double whatever is set as the value for 'spacing'. Will get this and the other issue sorted for you soon. Thanks for reporting!

**Comment by Misplon** [comment]
@AlexGStapleton Are you still keen to take this on?
