### ISSUE TITLE
TinyMCE removing iframe element

### ISSUE THREAD

**Issue by ziga-miklic** [siteorigin/so-widgets-bundle#19]
Hey, in the new TinyMCE field type the `<iframe>` tag gets removed. The Black Studio TinyMCE plugin that is used in the Visual Editor element (part of PB bundle) did not remove it.

Is this intentional? Is there a way I can allow the usage of all HTML elements?

I know that providing shortcodes for embedding media such as Google Maps and videos is better, but I think that some users may want to just copy/paste an embed code.

**Comment by braamgenis** [comment]
Hi Žiga

We simply went this way because it's the default behaviour of the WordPress visual editor. I've updated it to allow any HTML tags except `<script>` for privileged users. This will be included in the next release.
