### ISSUE TITLE
Hero: Allow for fallback video background

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#190]
The hero widget should allow for a fallback video file in the case the browser doesn't support a video format.

**Comment by gregpriday** [comment]
As far as I remember, you can set multiple videos with multiple formats. The widget will use which ever one is supported.

**Comment by AlexGStapleton** [comment]
Actually, you're right. With that said, if however there are two videos - one mp4 and the other webm, and the first video is mp4 and the browser supports both then the mp4 one will be loaded if it's the first one added. Not really a major issue - just something to consider.
