### ISSUE TITLE
Video Player: Add the ability to specify multiple video sources

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#191]
It's odd that you're only able to specify one source for locally hosted videos. You should be able to specify multiple in a priority order to allow for webm over mp4.

**Comment by braamgenis** [comment]
@AlexGStapleton Did this a while ago here: b989b95899cebaa19a87dce7de789c3eb832cf1d

Can you please verify whether this works for you as expected?

**Comment by AlexGStapleton** [comment]
Completely forgot about this issue. It's definitely working as intended as I recently answered a post on how to do this.

**Comment by braamgenis** [comment]
Awesome, thanks! :+1:
