### ISSUE TITLE
Image Grid: Add fallback for image field

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/so-widgets-bundle#193]
What if we add fallback for image field? Would it be a good enhancement?

**Comment by AlexGStapleton** [comment]
Could you clarify the context for such a fallback? In what scenario would the fallback appear?

**Comment by ernilambar** [comment]
When fallback is added, users are not bound to display images from their own media uploaded in the system. They can use URL field for displaying any images from other sources.
When images are saved, attachment ID is saved. When we create builder prebuilt layout, ID is not useful in this case. If fallback URL field is available, we can use that field for adding demo images, so that when user import layout they would not have to see blank image grid.

**Comment by AlexGStapleton** [comment]
Okay, so more of external URL support instead of a fallback? Yeah, that's a decent suggestion. +1
