### ISSUE TITLE
the siteorigin_widgets_search_posts_post_types filter should provide more context

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#196]
The siteorigin_widgets_search_posts_post_types filter should provide more context to allow for more conditional filtering. For example, I may want certain post types to be filtered for X widget but not for Y widget. Currently, there is no way for me to know what widget is polling the data so I'm unable to work filter as it'll affect not only those two widgets but all widgets.

Semi related to #195 but it would be a good quality of life enchancement.

**Comment by braamgenis** [comment]
#170 has made it possible to set post types on a per field basis.
