### ISSUE TITLE
Contact Form Submit Button: Gradient Intensity set to 0 should remove gradient.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#197]
0 Intensity implies none, and thus should remove the gradient.

**Comment by braamgenis** [comment]
As far as I can tell, that is the case. It may have been fixed since you reported this issue. Could you please confirm whether or not you're still seeing it?

**Comment by AlexGStapleton** [comment]
The gradient effect is no longer visible. Oddly though the CSS for the gradient is still being output. For consistency (maybe more in terms of removing the redundant CSS) sake, would it be possible to remove that CSS if the gradient intensity is set to 0?  

![](https://i.imgur.com/qFR57SD.png)

**Comment by braamgenis** [comment]
Ok, agreed. Should definitely clean up after ourselves. :+1:
