### ISSUE TITLE
SiteOrigin Editor Widget: Investigate why Add Form button isn't present

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#200]
See if it's possible to integrate with Gravity Forms to include the Add Form button in the SO Editor widget as it appears in the regular edtitor.

**Comment by Misplon** [comment]
Let's investigate why the Add Form button isn't adding to the SiteOrigin Editor widget.

**Comment by AlexGStapleton** [comment]
These plugins don't have their buttons show up either:

https://cs.wordpress.org/plugins/google-drive-embedder/
https://cs.wordpress.org/plugins/caldera-forms/
https://cs.wordpress.org/plugins/tinymce-templates/

**Comment by AlexGStapleton** [comment]
[Yasr – Yet Another Stars Rating](https://wordpress.org/plugins/yet-another-stars-rating/) shows up for me without issue. Bringing this up purely as a plugin that can add a button without issue.


![](https://i.imgur.com/nB4IfGn.png)
