### ISSUE TITLE
Simple Masonry Widget: Title field doesn't render

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#201]
The Title field within each added frame of the Simple Masonry widget doesn't appear to be rendering at all.

**Comment by AlexGStapleton** [comment]
Was this recently fixed? I ask as the titles are HTML titles rather than actual text on the page itself.

![](https://i.imgur.com/FfXdRY6.png)

**Comment by Misplon** [comment]
@braamgenis Can you perhaps take a look for us?

**Comment by Misplon** [comment]
Ahh @AlexGStapleton this thread is about the widget tile field, not the image title attribute. Sorry for not making that clearer.

**Comment by AlexGStapleton** [comment]
Ah, makes sense - thanks for the clarification, my b. 😖

**Comment by braamgenis** [comment]
Both widget title field and individual image titles are working for me. @Misplon Mind confirming whether this has been resolved for you?
