### ISSUE TITLE
SiteOrigin Editor Inserts <br> in captions for images

### ISSUE THREAD

**Issue by eduardoarandah** [siteorigin/so-widgets-bundle#203]
**I found the bug in:**
so-widgets-bundle/widgets/editor/editor.php 

**function:**
get_template_variables inserts a `<br>` when using captions for images:

```
if( $instance['autop'] ) {
    $instance['text'] = wpautop( $instance['text'] );
}
```

How to reproduce the bug:
- Create a "SiteOrigin Editor" widget
- Insert an image with a caption
  ![caption](https://cloud.githubusercontent.com/assets/4065733/15002731/1a307294-116a-11e6-85e0-5d697f6497e0.jpg)
- Sourcecode inserts unwanted `<br>`
  ![unwanted br](https://cloud.githubusercontent.com/assets/4065733/15002743/33f415a0-116a-11e6-9aae-68c73a5361a0.png)

**Comment by braamgenis** [comment]
We had some issues previously with the Editor widget inserting `<br>`s where it shouldn't and it seems like this issue was resolved along with those.
