### ISSUE TITLE
[Feature Request] Add support for Ionicons and Bootstrap icons

### ISSUE THREAD

**Issue by ste93cry** [siteorigin/so-widgets-bundle#21]
It would be great to have support of [Ionicons](http://ionicons.com/) icons pack and [Bootstrap](http://getbootstrap.com/components/#glyphicons) icons direcly in the core. At the moment users have to add them manually using the provided `siteorigin_widgets_icon_families` filter.

**Comment by braamgenis** [comment]
Hi @ste93cry 
Cool, we'll look into adding these. Let us know if you have any more icon pack suggestions.

**Comment by gregpriday** [comment]
:+1: for Ionicons. They look great.
