### ISSUE TITLE
Features: Remove width: 100% !important; from media query

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#211]
Annoyingly at lower resolutions the features widget will make the widget responsive by forcing a full width. That seems really weird to me as the upper limit for this media query is 520px. That is absolutely _huge_.

It might be a better idea to remove the float rely on display: inline-block instead.

[Reference in code](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/features/css/style.less#L110).

**Comment by braamgenis** [comment]
I'm not following what the issue is here, but will this possibly be resolved with your change in #372 or the alternate responsive settings for the Features widget?

**Comment by AlexGStapleton** [comment]
To be honest, I don't remember but I agree that #372 is a better overall solution.
