### ISSUE TITLE
Setting post type for post selector

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/so-widgets-bundle#213]
In many cases, a widget is set to work only with specific post types. How about adding an option to set the post type and allow users to build a query around it.

**Comment by AlexGStapleton** [comment]
Are you asking for something like the change requested in #196?

**Comment by adiraomj** [comment]
It's very similar. I was thinking about adding something like `'posttype' => array('post', 'page')` to the form field descriptor. So the form field would look something like

```
$form_options = array(
    'some_posts' => array(
        'type' => 'posts',
        'label' => __('Some posts query', 'widget-form-fields-text-domain'),
        'posttype' => array( 'post' ),
    )
);
```

**Comment by AlexGStapleton** [comment]
Oh. I thought my comment was unrelated so I removed it. For reference, my original comment was something along the lines of, would your request be covered by #196.

Can't remember it exactly. :disappointed:

**Comment by AlexGStapleton** [comment]
Regardless of the above, I like this idea. It allows theme developers to provide context sensitive widgets to users while not flooding them with irrelevant ones.

**Comment by braamgenis** [comment]
The `link` field now has a `post_types` option since #170 was merged. Can add a similar thing for the `posts` field.
