### ISSUE TITLE
Social Media: Add Soundcloud

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#215]
Soundcloud is a very popular social platform for music creators so it would be a good idea to add them to the social media widget.

**Comment by braamgenis** [comment]
I'm pretty sure we already have soundcloud.

**Comment by AlexGStapleton** [comment]
:( I checked the source before I posted this and didn't see it. Apparently I'm blind though. :cry:

**Comment by braamgenis** [comment]
Haha, no worries. I do that all the time. At least I picked up a bug thanks to this report though. :+1:
