### ISSUE TITLE
Social Media: JS error when attempting to load default network colours.

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-widgets-bundle#216]
![social media js error](https://cloud.githubusercontent.com/assets/3822928/15424979/da692dda-1e85-11e6-8c20-ad875f3d8993.png)

**Comment by gregpriday** [comment]
Is this from a recent change?

**Comment by braamgenis** [comment]
No idea. Just spotted it when confirming that we had Soundcloud icon. Shouldn't cause issues though. Just slightly less convenient where users will have to select their own colours for newly created widgets.
