### ISSUE TITLE
Features widget unable to handle icons without square proportions

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#217]
Many users are using the Features widget for images only. To do so they set the icon container size and icon size to the same value. This is fine as long as the image has square dimensions that match. If the image doesn't have matching square dimensions the image repeats. Image repeat isn't the only issue. We ideally need a way to deal with this use case which is an image only without square dimensions.

![image](https://cloud.githubusercontent.com/assets/789159/15426832/611a1f8c-1e91-11e6-9b26-93afd7fba66a.png)

![one-size](https://cloud.githubusercontent.com/assets/789159/15426833/63b0516c-1e91-11e6-8667-232aa8481380.png)

![repeat](https://cloud.githubusercontent.com/assets/789159/15426835/6698a30c-1e91-11e6-914d-a59ae32e96cc.png)

**Comment by Misplon** [comment]
By image only I mean no container. Users will still insert a headline and text which I didn't display in this demo.

**Comment by braamgenis** [comment]
There have been a couple of changes to how images are handled in Features widget. The repeat issue should be fixed. I'm not following what the other issue is, but could you perhaps check the latest WB to see if it's been resolved with the other changes?
