### ISSUE TITLE
Custom Widget Image

### ISSUE THREAD

**Issue by ehrig** [siteorigin/so-widgets-bundle#22]
How can I add an image for my custom widget? I want to replace the blue "default.png" placeholder image under "Plugins > SiteOrigin Widgets" with my own image. 
I tried to copy+paste "/assets/banner.svg" within my custom widget folder, it picks it up, but somehow produces a wrong URL. I was hoping this would be possible within my custom widget class using $widget_options. Any advice is very much appreciated. Couldn't find anything in the docs.

**Comment by braamgenis** [comment]
Hi ehrig

It's not something we've documented yet, but if you have your image in your custom widget folder as `assets/banner.svg` it should just work. Alternatively, you can use the `siteorigin_widgets_widget_banner` filter to provide the src url for your image as follows:
```
function my_awesome_widget_banner_img_src( $banner_url, $widget_meta ) {
	if( $widget_meta['ID'] == 'my-awesome-widget') {
		$banner_url = plugin_dir_url(__FILE__) . 'my_banner.png';
	}
	return $banner_url;
}
add_filter( 'siteorigin_widgets_widget_banner', 'my_awesome_widget_banner_img_src', 10, 2);
```

Hope that helps.
