### ISSUE TITLE
Widget Id = Filename => id-overlap

### ISSUE THREAD

**Issue by soul-surfer-manni** [siteorigin/so-widgets-bundle#221]
Adding custom widgets works well, but if the file-names are equal every widget with the same file-name gets disables when I disable a widget via Plugins -> SiteOrigins Widgets.

Example:
My custom slider widgets collides with the one already being there with the widgets bundle plugin because the files the two widgets are located in are named “slider.php”.
If I now deactivate the siteorigin slider element, it deactivates my widget as well.
Under Plugins -> SiteOrigins Widgets, there is a data-id attribute containing the filename as the id.

I was wondering why that is and if it wouldn’t be be better to take the widget-id defined in the __construct method.

Best regards,
Michael

**Comment by braamgenis** [comment]
Thanks for reporting @soul-surfer-manni . We did notice this issue internally a while ago, so it might already have been fixed, but we'll check to make sure and fix it if not.
