### ISSUE TITLE
Video Player: Unable to use YouTube Embed URL

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#225]
[Reported in this thread](https://siteorigin.com/thread/embed-youtube-video-not-work/)

A typical YouTube URL will work as intended (https://www.youtube.com/watch?v=qttznZ7O9k4)  but an embed URL will not display a video (https://www.youtube.com/embed/qttznZ7O9k4). The embed functionality is WordPress supports both.

[Reference Layout](https://u.teknik.io/0uxPC.json)

**Comment by gregpriday** [comment]
When using an external URL, the video widget is essentially just a wrapper for the WordPress oEmbed functions. We could educate users about this works, but I feel like that could be unnecessary noise in the description for this field.

https://codex.wordpress.org/Embeds

**Comment by AlexGStapleton** [comment]
I'm aware which is why I logged this as an issue. If you use the above-mentioned embed URL outside of this widget it'll work as expected. It however won't work if you use it in the video player widget.

**Comment by gregpriday** [comment]
Aaah, right. I see what you mean now. I'll get on this.

**Comment by gregpriday** [comment]
Hrmm, this is an odd one. I can't quite track how the data flows between the function we're using ( `wp_oembed_get` ) and what the standard WordPress editor is using. The one hacky fix we could implement is just using a regex to change the embed URL into a watch URL.

I'll have another look at this later.

**Comment by AlexGStapleton** [comment]
The problem with that workaround is that the only reason someone would use the embed URL over the typical URL is because they wanted to set [player parameters](https://developers.google.com/youtube/player_parameters).

**Comment by gregpriday** [comment]
Then we're just going to have to do things that hard way and work out the whole data flow.

**Comment by gregpriday** [comment]
In the end, I just resolved this by rewriting YouTube URLs. The new core WordPress Video widget does a good job of dealing with those `embed` URLs, so if it's essential, users can just use that widget.
