### ISSUE TITLE
Price Table: Add functionality for consistent feature height across columns

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#226]
[Suggested in this thread](https://siteorigin.com/thread/dynamic-and-consistent-row-height-in-price-table/)

A really nice feature would be an option to have consistent feature row height across columns. Basically, what would happen is we would write a script to compare a feature row and the row with the highest height would be set as the height of all columns for that row. This will provide a more consistent look to the pricing widget.

![](https://i.imgur.com/8GQyUdT.png)

**Comment by Misplon** [comment]
It's been requested many times.

**Comment by braamgenis** [comment]
I've implemented this as an optional feature in #416. If you guys have a moment it would be great if you checkout the branch and see if it works as expected.

**Comment by Misplon** [comment]
Looks good to me. @AlexGStapleton All good?

**Comment by AlexGStapleton** [comment]
Sorry for the delay.

Just tried it and it looks good.

With that said, if there's an odd number of features the spacing is added via a blank space.  Is it possible to spread out the columns to fill this spacing instead? I know that's likely a big ask but it looks a tad weird when there are 3 features in one column (and a large space the size of three more) and 6 in another due to the large spacing.

![](https://i.imgur.com/HWitzJO.png)

**Comment by braamgenis** [comment]
Hmmm, if we do something like that, we might be back where we started and rows won't always align nicely. Trying to develop an algorithm to maximize used space but also minimize offsets (misalignment) between rows is likely to be hard and time consuming and will probably have mixed results.

**Comment by AlexGStapleton** [comment]
Thought so. Yeah, I would avoid it unless it becomes a widespread complaint (which is unlikely - we'll likely only hear about it once or twice).

**Comment by AlexGStapleton** [comment]
Wait. Maybe a better idea would be to add dummy features when there's an uneven feature count. By dummy features, I mean a "row" with an X or a cross or something like that to suggest that the feature isn't present for that level.

**Comment by braamgenis** [comment]
I'd guess that some users would like that and some not, besides they can already do that, by just adding empty features with an X in the text field.
