### ISSUE TITLE
panelsopen for repeater field

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/so-widgets-bundle#229]
Consider extending the `panelsopen` jQuery event to trigger when new repeater item is created.

**Comment by braamgenis** [comment]
We currently trigger `updateFieldPositions` event on the repeater items container with class `.siteorigin-widget-field-repeater-items` if that helps? That's triggered in a few different cases though, not only when a repeater item is created. Alternatively you can look at the [create event](https://api.jqueryui.com/sortable/#event-create) triggered by jQuery UI Sortable. Is that what you were after?
