### ISSUE TITLE
[Feature Request] Add option to disable theming of button widget

### ISSUE THREAD

**Issue by ste93cry** [siteorigin/so-widgets-bundle#23]
I'm trying to customize the template of the Button widget by adding custom styles to the HTML output. The widget has an option that gives user the ability to choose a theme to be applied to the button in the frontend, however, there seems no way to disable it. I tried to workaround the problem by using some creative ideas, but I always end in the same code. The function below can return `false` to prevent adding stylesheets to the frontend, but in this case the `empty` function returns `true` if `false` or `null` is passed.

```php
function get_style_name($instance) {
    if(empty($instance['design']['theme'])) return 'atom';
    return $instance['design']['theme'];
}
```

I tried to use the `siteorigin_widgets_instance_sow-button` filter to edit the `$instance` variable but even if I could set the theme to false it's useless. There seems not to be any way to workaround this, except by creating a custom widget that extends or clones somehow the original and customize it to fit my needs. Could a "No option" theme be added in the core? Or at least it would be great if the code below could be edited to skip the first `if` statement if the value is not an array. Even better, if there is no `theme` value set it should just return false. This gives developers the ability to just unset the theme option and prevent the CSS to be enqueued.

One more thing: as a user I can add an ID to the button, but not a class. The widget class is unfortunately applied to a wrapper div. A new text field for the button CSS class would be cool.

**Comment by braamgenis** [comment]
Hi @ste93cry 

You should be able to use the `siteorigin_widgets_less_sow-button` filter to either change the existing LESS or replace it with an empty string to prevent it from being applied. If you choose to return an empty string, you'll just have to make sure you also delete any CSS files already created for the button widget, under `/uploads/siteorigin-widgets/`

Hope that helps.
