### ISSUE TITLE
Template Widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#230]
A template widget would allow people to output purpose created templates (stored in the theme directory) in a similar vein to the loop widgets but much more general and static. This will obviously be more for designers and developers than a general user. It would mainly be for static templates that would otherwise be a static widget (as in no customization options).

Thoughts?

**Comment by gregpriday** [comment]
I'm not quite following what this widget would do. Can you try explaining it slightly differently or give a few examples of how it would be used?

**Comment by AlexGStapleton** [comment]
A template widget would allow theme developers to create small one of templates files rather than widgets for static widgets.

If a theme had a simple separator with no customization options creating a widget for it would be overkill. A template widget would allow the designer to create a small separate template and store it inside the theme folder.

A template widget would also allow designers to create static widget type templates without having to touch PHP.

Hm. Maybe I'm not explaining this properly or I'm overthinking it and this isn't really a good idea. :confused: Maybe snippet would be a better word than template.

**Comment by gregpriday** [comment]
Aaah, yeah, I get what you mean now. That's a very good idea. +1

**Comment by AlexGStapleton** [comment]
While this is a good idea for a widget, it really relies on a large third-party developer uptake. It can't rely on general templates like the Post Loop can so it's really limited to only a few specific themes. As such, it's really hard to justify and it's property better overall to suggest developers create custom widgets instead.
