### ISSUE TITLE
Features: Title placement (before or after icon)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#232]
You should be able to specify if you want the title to appear above or below the icon.

**Comment by gregpriday** [comment]
Yeah, this would be a nice feature.

**Comment by gregpriday** [comment]
Something I've wanted to add to the Widgets Bundle for a while is an *ordering* field. Pretty basic, it would just allow you to specify a few items, and then reorder them. So in this case, we'd have the 4 components of each feature (icon, title, text, more link) and let the user change the order to whatever they'd like.

**Comment by gregpriday** [comment]
@braamgenis implemented this at some point
