### ISSUE TITLE
UX: When connected widget plugin is enabled, display notification that user may need to activate widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#235]
This method will ensure no one misses the SiteOrigin Widgets page again. :disappointed:

**Comment by gregpriday** [comment]
Not quite following this one. Can you explain? Do you think we just need a general admin notification bar when the plugin is enabled?

**Comment by AlexGStapleton** [comment]
Yes, but as a continuation of that, we should do a reminder when we detect a third party plugin that interfaces with the widget bundle.

**Comment by gregpriday** [comment]
Aaah, there we go. Solid idea.

**Comment by gregpriday** [comment]
Closing this because of how long we've gone without it. It's a good idea, but I'm not sure it's worth the effort at the moment.
