### ISSUE TITLE
Call to Action: Add ability to change font

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#237]
You should be able to change the font in the Call to Action widget in the design settings. Ideally it would allow you to specify the fonts for all sections but at the very least there should be an option to set them for all (as in one setting).

**Comment by Misplon** [comment]
Possible in SiteOrigin Premium as part of the Call-To-Action plugin addon.
https://siteorigin.com/premium-documentation/plugin-addons/call-to-action/
