### ISSUE TITLE
LESS - CSS output class wrap on keyframes

### ISSUE THREAD

**Issue by bravebox** [siteorigin/so-widgets-bundle#242]
Im sorry if this is not the place to ask this. But im developing my own widgets and noticed when using the default LESS styles it generates a CSS file with a container inside. This is totally fine :)

````
.so-widget-my-widget-style-d75171398898 .my-widget {
 width: 100%; // fine!
}
````

But when I define keyframes it also puts a container in front of the 0% etc.

````
@keyframes load {
  .so-widget-my-widget-style-d75171398898 0% {
    transform: rotate(0deg);
  }
  .so-widget-my-widget-style-d75171398898 100% {
    transform: rotate(360deg);
  }
}
````

Which makes my animations to not work.

Thanks Mick

**Comment by gregpriday** [comment]
Hi Mick

In this case, I'd suggest having a separate CSS file with all your animations. In general, the LESS style files are best for adding custom styling into a widget.

For example, you can see how we do this in the Button widget.

https://github.com/siteorigin/so-widgets-bundle/tree/develop/widgets/button

**Comment by bravebox** [comment]
hi Greg, thanks for the reply.

So there is a difference when compiling the LESS in /styles and /css, interesting!

I will have a go at it. Thanks
