### ISSUE TITLE
Headline: Headline and sub headline are conflicting

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#244]
When headline and sub-headline are both set as the same h tag. Alignment will be ignored and defaulted to left.

![](https://i.imgur.com/WjCnT4B.png)

[Reference Layout](https://u.teknik.io/HCEX9.json)

During my tests, I was only personally able to replicate this with the headline set to h3 and the sub-headline didn't matter for me. [My test layout](https://u.teknik.io/BP7Kh.json).

**Comment by gregpriday** [comment]
Resolved with https://github.com/siteorigin/so-widgets-bundle/commit/1dd28456f3d5cad7e6e4b757e31502103d2a64df
