### ISSUE TITLE
Video: Self Hosted video plays when video widget modal closes after adding first video

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#246]
- Add SiteOrigin Video Player Widget and open it
- Set Video Location to self-hosted and add a video (only one required)
- Tick Autoplay in video playback settings
- Click done and video will start playing in background.

This only seems to happen once

**Comment by braamgenis** [comment]
This was actually a Page Builder issue. Resolved [here](https://github.com/siteorigin/siteorigin-panels/commit/8514a96c5648486c6f521feb135f8f9f52fd0f9d)
