### ISSUE TITLE
Issue on Google Map Widget

### ISSUE THREAD

**Issue by mesunil2010** [siteorigin/so-widgets-bundle#25]
Hi, I had initially set map as draggable and scrollable but later i changed checked it off and had error. I fixed it by adding !empty in related variables. Might be somtehing you might take look at. Thanks

**Comment by braamgenis** [comment]
Hi @mesunil2010 

Thanks for reporting the issue, but I'm not able to recreate this. Can you give some more information on what you did and at what point exactly you saw the error?

**Comment by mesunil2010** [comment]
It was something related to variables realted to draggable and scrollable undefined .  You can just add map, check it as draggable and scrollable . Save it and then edit the same map widget again , just uncheck them and you might see error. That is how i encountered the error. Its simple but yet good to be fixed.

**Comment by braamgenis** [comment]
Thanks for the quick response. I've tried the steps you gave to reproduce, but I'm still not seeing the error. I think we might have fixed this along the way with other work. I'm going to close this as not reproducible, but please let us know if you see this or any other issues again.

Thanks again for your contribution. :+1:
