### ISSUE TITLE
Contact: Ability to set field heigths (text input / textarea)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#250]
A design setting that will allow you to override theme styling for form text input or textarea height would allow users to do this directly via the widget rather than CSS.

**Comment by braamgenis** [comment]
Do you maybe want to add this as part of #394? Shouldn't take much to add height there.

**Comment by AlexGStapleton** [comment]
Sure.

**Comment by AlexGStapleton** [comment]
Resolved in #394
