### ISSUE TITLE
Weird height transition behaviour in slider

### ISSUE THREAD

**Issue by LuBevilacqua** [siteorigin/so-widgets-bundle#253]
Hello,
as reported on the [forum](https://siteorigin.com/thread/siteorigin-slider-widget-image-sizing-and-overlap/) there is an old bug that still shows up sometimes on the slider.
The first time it switches from 1st photo to the 2nd one, the viewport height of the slider seems to jump, because of the default padding of the ul parent element.
I would suggest to add `padding: 0;` to .sow-slider-base ul.sow-slider-images to fix it.
Keep up with your great work!
Luigi

**Comment by braamgenis** [comment]
Hi @LuBevilacqua
Thanks very much for your contribution! Unfortunately, as stated in the forum post you linked, this isn't something being controlled by the Slider widget and seems to be theme-specific. Adding `padding: 0;` might fix the issue for you, but it might also break the layout and/or position of the slider for other users. If any other users report this issue, we'll keep your suggestion in mind as a possible fix. Thanks again! :+1:
