### ISSUE TITLE
Widgets screen accessibility mode issues

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#256]
When the widgets page is set to accessibility mode (can be set via the screen options) any widget that relies on the form fields included with SiteOrigin Widgets Bundle won't work due to, what feels like, the JavaScript not loading.

![](https://i.imgur.com/Gskyc6L.gif)

If you add a layout builder widget and then try and add a widget that makes use of the widgets framework it'll display a message stating that the scripts and styles need to be loaded.
![](https://i.imgur.com/KLkNpNo.png)

These two issues are likely related.

**Comment by braamgenis** [comment]
Scripts and styles are loading fine for me. I suspect this is thanks to our recent changes to make widgets compatible with other page builders. :smile: I do, however, still see the layout builder issue.

**Comment by AlexGStapleton** [comment]
Can confirm that all widgets bar the layout builder seems to be working as intended now. 👍

**Comment by AlexGStapleton** [comment]
Layout builder works now, although it is a tad squished. I'm happy to close this if @Misplon or @braamgenis are.

![](https://vgy.me/p1VVBl.png)

**Comment by Misplon** [comment]
@AlexGStapleton Any feedback/reports from users on this particular one?

**Comment by AlexGStapleton** [comment]
Closing this for now unless there starts to be a demand for making the layout builder interface bigger in accessibility.
