### ISSUE TITLE
Image: Display HTML input into title text field (and strip it from the image alt if set)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#257]
The image title text field should allow for basic HTML for formatting reasons (strong, em, br, etc). Currently, the title text is being escaped (both on output and on save).

**Comment by braamgenis** [comment]
Seems to be working. Fixed in one of your PRs I think? :+1:

**Comment by AlexGStapleton** [comment]
Whoops! Yes, and I sadly can't seem to find the specific pr at the moment but it's definitely somewhere. :(
