### ISSUE TITLE
Enhancement: responsive video widget CSS

### ISSUE THREAD

**Issue by boquiabierto** [siteorigin/so-widgets-bundle#26]
http://alistapart.com/article/creating-intrinsic-ratios-for-video

EDIT: editor’s heaven if you include a selector in the widget editor for the aspect ratio of the video (at least 4:3 and 16:9). You could then target the padding-bottom f.e. by including a class into the sow-video-wrapper.

**Comment by Misplon** [comment]
Hi @boquiabierto. Thanks for posting this request, time sure does fly. I'm going to close this for the time being. Hopefully, FitVids.js is handling resizing adequately. If not, please, send an example link and we'll take a look. Thanks again.
