### ISSUE TITLE
Hero: When Maximum width setting is blank or set to 0 there should be no maximum width set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#260]
Currently, if you blank the maximum width field it will default to the default maximum width (which is 1280px). This should be changed so that if you blank the field (or set it to 0) it should simply not set a maximum width.

**Comment by braamgenis** [comment]
Just to clarify, this setting only affects the foreground content, not the background. Then I think setting it to 0, should set it to 0. Not sure why a user would want this, but 0 should be considered a valid entry. Secondly, I don't think we can easily change the behaviour of a leaving the field blank without affecting a bunch of existing users.

**Comment by AlexGStapleton** [comment]
In hindsight, I agree.
