### ISSUE TITLE
Editor: Hide TinyMCE "popups" on widget close.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#263]
When a user closes the widgets certain TinyMCE popups will remain on screen until scroll.

Here's a quick list of things that still show after widget close:
- [Add / Edit Link](https://i.imgur.com/OVDtG3w.png)
- [Link Preview](https://i.imgur.com/eOXZEXg.png)
- [Image presentation toolbar](https://i.imgur.com/ZuPQXYV.png) 
- [Paste as text notification](https://i.imgur.com/5QSPPS9.png), this one remains on scroll

While this isn't a major issue it would be a good idea to check for these sort of elements to avoid any potential confusion.

**Comment by gregpriday** [comment]
@AlexGStapleton can you check if this is still an issue?

I just checked and it doesn't seem to be happening anymore. Possible that we fixed this while fixing another issue somewhere along the way.

If it's still a problem, please reopen this issue.

**Comment by AlexGStapleton** [comment]
I can't replicate this anymore. This was likely indirectly fixed in a WordPress update imo.
