### ISSUE TITLE
Google Maps: Test API key on input / change

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#265]
So I've noticed that the Google Maps API requirement by Google can be confusing to certain people. Google Map error codes are only visible in the browser's console and most of the time they use complicated jargon. This forces users who have issues to come to us for support as they either don't understand the error or don't see it (don't know how to open the console). As such I think the best method of reducing the ticket amount with this issue would be to add an Ajax API check to see if the API key is valid and if any errors are present.

For a full list on error codes please refer to [this page](https://developers.google.com/maps/documentation/javascript/error-messages#errorcodes).

**Comment by braamgenis** [comment]
It seems this isn't possible. Google hasn't provided a way to test whether a key is valid before attempting to use the key. And, even worse, it doesn't seem like there's a reliable way to test that one of the listed errors has occurred. :disappointed: So at this stage I'd say we need to try make it **very** clear that an API key is required when a used creates a maps widget. It might help that soon we'll have a [global setting](https://github.com/siteorigin/so-widgets-bundle/pull/421) for the key.

**Comment by AlexGStapleton** [comment]
What a silly thing not to allow. :/

Oh well, at least the global setting should hopefully stem the number of reports.
