### ISSUE TITLE
Remove slider widget sentinel when only using one slide

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#266]
If using only one slide the slider widget is still adding a sentinel so in the source you have two list items, two slides. If possible, remove the sentinel if only one slide is added.

Reference site: http://preview.tapkey.org/en/

**Comment by braamgenis** [comment]
The fix doesn't remove the sentinel, but rather just empties it. The auto-height functionality breaks if we remove it completely.

**Comment by Misplon** [comment]
Sweet
