### ISSUE TITLE
Carousel: Add the ability to select a custom image size

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#269]
A custom request is more control over the carousel image dimensions - currently locked to 272x182 via an image size. We should allow users to select another image size, similar to that of the image widget.

This change will require that the frontend CSS for this widget not be so locked to 242px width.

**Comment by AlexGStapleton** [comment]
[Here's a solution](https://wordpress.org/support/topic/carousel-slider-image-sizes?replies=2#post-8634568) I'm currently using to work around this issue. :(

**Comment by locness3** [comment]
Sorry if this is not the best place to post, but the setting doesn't seem to have any effect for me. it seems properly saved but it looks like it does nothing

**Comment by AlexGStapleton** [comment]
Hi Locness3,

That's strange. I can't seem to replicate that locally, so we would need to try a few things to work out why it's not working for you. Would it be possible for you to create a thread on our [community forums](https://siteorigin.com/thread/)? We'll be able to help you there.

Kind regards,
Alex
