### ISSUE TITLE
Carousel: Adjust carousel output direction if locale is RTL

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#270]
We [should check](https://codex.wordpress.org/Function_Reference/is_rtl) if the website locale is RTL and then output posts right to left if required.

This shouldn't require a dedicated setting as if the website is RTL it wouldn't really make sense for the user to have the carousel LTR.

**Comment by braamgenis** [comment]
Hmmm, at first glance this made sense, but thinking about it, why would we switch the order of posts? The order should be the same, just with RTL layout instead of LTR, shouldn't it?

**Comment by AlexGStapleton** [comment]
I... I don't know what I was thinking when posting this but what you just said was the desired fix. I'm going to reword the title to reflect that.

**Comment by braamgenis** [comment]
The carousel widget has been doing this for quite a while. Since this commit 1051592d3a2ef67415c1b5807ce25ce297dc06cb. Was this not working for someone?

**Comment by AlexGStapleton** [comment]
It wasn't, no. Hm. I suspect the original title was more related than I had thought. 😕 

Sadly, I can't find the initial thread/email that this is related too and I haven't seen any other issues like this since so I think we should close this unless this comes up again. Is that okay?

**Comment by braamgenis** [comment]
Cool cool. :+1:
