### ISSUE TITLE
Headline: Remove !important from styling

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#275]
We're already using [highly specific selectors](https://i.imgur.com/Xlz9CdI.png) there's little reason to !important it. This also prevents other designers from making adjustments to the margins.

[Reference in default.less](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/headline/styles/default.less#L70)

**Comment by braamgenis** [comment]
Closing as per the related PR.
