### ISSUE TITLE
Simple Masonry: Allow users to select unit of measurement for row gutter

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#278]
This will allow the user to create more dynamic layouts without having to manually work out the width of each column as they could just use, say, %.

**Comment by braamgenis** [comment]
:+1: So we might as well change both gutter and row height to measurement fields.

**Comment by AlexGStapleton** [comment]
So I've run a few tests and the limiting factor for doing either of these appears to be the packery. It is possible, but it's not a simple change to get it working as the heights need to come from the element rather than the container. I'm going to push this back to p3 and unassign.

**Comment by Misplon** [comment]
If Packery makes this easier in the future we can attend.
