### ISSUE TITLE
Google Maps: Change Location API field to make it apparent API key is required, not optional

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#282]
The API key is required and not optional. The wording suggests otherwise. Found [here](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/google-map/google-map.php#L67).

**Comment by braamgenis** [comment]
Are you happy with the description as it is now, considering we also have the little red `required` tag?

**Comment by AlexGStapleton** [comment]
Yes, but I still don't like the "may" word as it's not optional but 100% required. It _may_ work on really old websites but it _will_ break eventually.

**Comment by braamgenis** [comment]
Ok, then. Unless there are any objections from @gregpriday, how about we change it to _'Enter your API key. Your map **will** not function correctly without one.'_ (without the emphasis etc)
