### ISSUE TITLE
Layout Export: Add ability to export images

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#286]
Users should be able to do a full export of a page which includes all media assets. This is to suggest that relying on third party images (read: external images) isn't always ideal. It works for our layout directory but it doesn't really work for a typical user.

It's quite a process to explain to a user how to move the images over manually and this will remove the need to do so.

**Comment by gregpriday** [comment]
Exporting images in a JSON file would be rather difficult. The solution might be to create a different type of ZIP export.

**Comment by gregpriday** [comment]
@AlexGStapleton just realised that this is also technically a Page Builder feature. Feel free to open it up there.

**Comment by AlexGStapleton** [comment]
Whoops. Must have been one of those days. siteorigin-panels/#278
