### ISSUE TITLE
Add Dedicated Widget Settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#287]
With the likes of the [SiteOrigin Widgets Builder](https://github.com/siteorigin/so-widgets-builder) being created it's quite likely a lot of new and exciting third party widgets will start to be created soon. Said widgets may may require specific settings and to prevent cluttering of the main SiteOrigin Page Builder settings we should add a settings interface for widgets on the widgets page.

![](https://i.imgur.com/fiXxxJA.png)

When clicked you would be able to adjust whatever settings the user has specified. For example, for the SiteOrigin Google Maps widget we could allow the user to specificity their API key, thus removing the need to set a key for each individual Google Maps widget (this will replace #249). It doesn't need to be anything fancy as a simple modal would suffice.

Said button wouldn't show if settings where empty.

**Comment by gregpriday** [comment]
Great idea.

**Comment by gregpriday** [comment]
Implemented in https://github.com/siteorigin/so-widgets-bundle/tree/feature/widget-settings - will merge after some tweaks. No widgets use the feature yet, but this is going to be hugely valuable.

**Comment by AlexGStapleton** [comment]
Awesome! :smile:
