### ISSUE TITLE
so-widgets-bundle released under GPLv3 has some files released under GPLv2

### ISSUE THREAD

**Issue by fu7mu4** [siteorigin/so-widgets-bundle#291]
widgets/google-map/js/ja-map.js is released under GPLv2 by SiteOrigine
base/inc/color.php is released under GPLv2 by Grep Priday
js/*_/jquery._.js are released under GPLv2 or MIT by jQuery (recently jQuery are re-reased under MIT License)
above files are incompatible license with GPLv3.
What should I do ?

**Comment by gregpriday** [comment]
Hi @fu7mu4 - we'll search and update the license to GPL unversioned (which defaults to the latest version of GPL). AS for jQuery - MIT is compatible with GPL.
