### ISSUE TITLE
Google Maps: Filter # from the address

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#295]
If # is added to the address, the map isn't displayed as the data sent to Google becomes invalid.

**Comment by braamgenis** [comment]
@AlexGStapleton Please give an example of a valid address containing a # which has this issue. I tried a map with the address '#23 Long Street, Cape Town, 8001' and it seems to work just fine.

**Comment by AlexGStapleton** [comment]
This actually looks to have been indirectly fixed with the recent changes with how we handle Google Maps. Don't quote me on this but, if I remember correctly, this widget use to send the actual address to Google. This isn't happening anymore and as a result, this issue isn't occurring.
