### ISSUE TITLE
Google Maps: Mention size limitation for static maps

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#296]
[The Google Static Maps API has a limit](https://developers.google.com/maps/documentation/static-maps/usage-limits) of 640x640 for the sizing of the map. We should reference this. The paid version allows for 2048x2048 but it's unlikely anyone will have that due to cost.

![](https://i.imgur.com/sVcXHBU.png)

**Comment by Misplon** [comment]
At the moment, I can't see how this will be changed from June 11 in the new pricing. I'll return to this in June, test and then add to the Maps documentation as required.

**Comment by Misplon** [comment]
@AlexGStapleton I think we can close this now as all accounts need to be linked to a billing account. I've read the new pricing table and see static maps free tier but can't find any info on limitations on size.
