### ISSUE TITLE
Programatically enable custom widgets

### ISSUE THREAD

**Issue by SteveS123** [siteorigin/so-widgets-bundle#3]
Is there a way to programatically enable my custom widgets rather than visiting the /wp-admin/plugins.php?page=so-widgets-plugins screen and enabling them there?  I'm adding these to a WordPress multisite instance and would prefer to enable them globally.

**Comment by braamgenis** [comment]
Hi SteveS123

You can activate your widgets by calling the `activate_widget()` function in the `SiteOrigin_Widgets_Bundle` class [here](https://github.com/siteorigin/so-widgets-bundle/blob/develop/so-widgets-bundle.php#L301).

We'd like to keep Github Issues to actual issues with the code, such as bugs and feature requests. So, in future, it would be very much appreciated if you could post any support questions over at the [SiteOrigin forum](https://siteorigin.com/new-thread/). Thanks!
