### ISSUE TITLE
Add Widgets UX: If the user has searched and only one widget was returned, allow enter to be pressed to insert said widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#301]
Context: If the user has searched for a widget and only one widget was returned.

If the user presses enter, the sole returned widget should be added to the page.

**Comment by gregpriday** [comment]
Technically this would be a Page Builder if you want to create it there - https://github.com/siteorigin/siteorigin-panels/issues

**Comment by AlexGStapleton** [comment]
Oh whoops - my b.
