### ISSUE TITLE
Duplicated radio fields value in child widgets are not saved.

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/so-widgets-bundle#303]
I have a repeater field containing a child widget. This child widget has a radio field inside it.
When I duplicate the repeater item, it works as expected. However once I save the post, the radio field present inside the child widget returns to its default value.

**Comment by gregpriday** [comment]
Sneaky sounding issue @adiraomj. Do you have some code I can use to test this? Much easier than writing testing code myself.

**Comment by adiraomj** [comment]
Sure. I'll send it you later tonight. ;)
