### ISSUE TITLE
Automatically migrate legacy widgets into relavent SiteOrigin Widgets Bundle widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#304]
Preface: This suggestion is going here rather than on the SiteOrigin Page Builder repo due to SiteOrgin Widgets Bundle having to be installed for this to work.

When the user installs the SiteOrigin Widgets Bundle plugin we should automatically migrate (on page edit, not automatically for all pages) legacy widgets to their newer equivalents where possible. This will lower the usage and allow for us to, hopefully, one day remove them without worrying about legacy issues.

**Comment by braamgenis** [comment]
I like this idea, but would perhaps make it opt-in via a notification rather than automatic, as it has the potential to break things and then at least the user is likely to know the cause of the breakage.

**Comment by AlexGStapleton** [comment]
While this is a good idea, there likely isn't enough of a need to justify implementation due to how few use legacy widgets at this point.
