### ISSUE TITLE
Add ability to allow widgets to exclude itself from "copy content"

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#308]
Certain widgets just shouldn't be copied over as they provide no real value in fallback situations or in situations where text needs to be analyzed.

For example a slider widget. There's no real use in having it carry over as if Page Builder falls over several images will be shown, thus making the layout look more broken than normal. The slider widget pagination is also included in excerpts which can make the excerpt look messy.

![](https://i.imgur.com/NizW5dL.png)

**Comment by AlexGStapleton** [comment]
I filed this under the widgets bundle rather than SiteOrigin Page Builder due the widgets framework being in the Widgets Bundle. Obviously changes will have to be made to SiteOrigin Page Builder but I feel like the bulk of the work would need to be done to SiteOrigin Page Builder.

**Comment by gregpriday** [comment]
I don't think the benefit of this would be enough to implement this sort of functionality. It would require a bit of setup between the Widgets Bundle and Page Builder. The additional content isn't causing much harm, so it's not a big issue.
