### ISSUE TITLE
Post Carousel: Add auto scroll

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#311]
There should be an option for the post carousel to auto scroll a set interval. This will give a much more dynamic feel to this widget.

**Comment by gregpriday** [comment]
@AlexGStapleton Can you log this as an idea on Trello? You can even reference this issue. If/when we start working on it, we can open up this issue again.

**Comment by AlexGStapleton** [comment]
[Done](https://trello.com/c/UD3IlVVa/7-post-carousel-add-auto-scroll).

**Comment by TomasHurtz** [comment]
Hello

I would like to add this feature - What's the status please.  I am more than happy to add some custom code to the template - but what code where!

Thanks
