### ISSUE TITLE
Background image for call to action widget

### ISSUE THREAD

**Issue by ScreamingDev** [siteorigin/so-widgets-bundle#312]
https://siteorigin.com/widgets-bundle/call-action-widget/

Please allow an image as background.

Would be great if the one from "Design" (right menu) would be used.
So that if an background image is set, then there will be no color set.

See also: https://github.com/siteorigin/siteorigin-panels/issues/281

**Comment by gregpriday** [comment]
Thanks for the suggestion @sourcerer-mike! This is definitely something we'll look into.

**Comment by AlexGStapleton** [comment]
I've talked to Braam about this and he's fine with leaving this as is. If you're after something like that you may be better off using a standard Page Builder row - two column row with text on the left and button on the right.

Sorry mate.

**Comment by AlexGStapleton** [comment]
Disregard my previous reply.

**Comment by Misplon** [comment]
I think this can be done as follows:

* Disable the Use default background colors settings.
* Edit the widget's Design settings on the right and add a background image there.
