### ISSUE TITLE
Google Maps: Add Mobile Zoom setting

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#313]
A semi-common complaint about the Google Maps widget is that the zoom the user is using on desktop doesn't look good on mobile due to it typically being very zoomed in. As a result, the user typically has to use a comprise setting of a good looking mobile zoom and a good looking desktop zoom. We should add a Mobile Zoom setting to prevent users from having to comprise with such an important aspect of the map.

**Comment by rtibarewala** [comment]
I wish to know the same?
Need a different zoom level for mobile urgently.
It would be great to have this feature inbuilt in SiteOrigin Maps Widget.
