### ISSUE TITLE
Link Field: "Select Content" returning string with post ID instead of permalink.

### ISSUE THREAD

**Issue by dylanjmcdonald** [siteorigin/so-widgets-bundle#314]
Is the `Select Content` option supposed to return the permalink of the selected page/post?

Currently it is returning the value shown here

![Screenshot](http://i.imgur.com/T7GDkR8.png)

If this is the intended functionality it might be easier to return the ID only, instead of the concatenated string value of "post: {{ID}}". Unless I'm missing how the returned value is supposed to be used.

**Comment by cristi-contiu** [comment]
For anybody with a similar issue, you should use this in conjunction with `sow_esc_url` : [example](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/price-table/tpl/atom.php#L50).

**Comment by braamgenis** [comment]
@dylanjmcdonald Apologies for the delay in responding. It seems @cristi-contiu has helped you find the answer.
