### ISSUE TITLE
Editor: When autop is disabled manual paragraphs are stripped

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#318]
When you disable autop in the Editor widget manual paragraphs (literally `<p>`) are removed. For example, this:

```
<p>test</p>

<p>test</p>
```

Becomes this:

```
test

test
```

This does not happen in the text widget.

[Reference layout](https://u.teknik.io/jFFJ3.json)

**Comment by braamgenis** [comment]
This seems to be working as expected for me. Are you still experiencing this issue? Is this in the 'Text' or the 'Visual' editor?
