### ISSUE TITLE
Google Maps Widget: UberMenu stops Maps widget from loading.

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#319]
Maps widget won't display a map with UberMenu activated. 

(User provided copy of UberMenu [here](https://secure.helpscout.net/conversation/249381073/5659/?folderId=472482).)

**Comment by braamgenis** [comment]
@Misplon Could you provide more detail or steps to reproduce? Simply activating UberMenu wasn't enough to cause the issue for me.
![ubermap](https://cloud.githubusercontent.com/assets/3822928/18465759/af9d6cec-7998-11e6-90e9-c0b1a449e4c1.png)

**Comment by braamgenis** [comment]
I tried using the latest release version (1.6.5) of the Widgets Bundle too and that also works for me.

**Comment by Misplon** [comment]
Sorry about that, it was for me. Let me dive in deeper now. Will revert ASAP.

**Comment by Misplon** [comment]
For anyone reading, UberMenu loads the Maps API. If you aren't using maps in your menu, go to Appearance > UberMenu > General Settings and disable the API to resolve.

![ubermenu_settings__siteorigin](https://cloud.githubusercontent.com/assets/789159/18467812/ba6ac2ec-79a1-11e6-9e48-760da25515e0.png)
