### ISSUE TITLE
Icon picker in custom widget stopped working

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#322]
After updating to 1.7 icon picker in custom widget stopped working:

Before update: 
![screen shot 2016-09-20 at 18 33 12](https://cloud.githubusercontent.com/assets/10053621/18679659/f1999a94-7f60-11e6-9943-442f6d1a17f1.png)

After update: 
![screen shot 2016-09-20 at 18 34 12](https://cloud.githubusercontent.com/assets/10053621/18679679/fd60ae6c-7f60-11e6-8d21-ea443a32be29.png)

**Comment by AlexGStapleton** [comment]
Could you please send us the code you're using for this form field so we can try and replicate it?

To clarify, is this only happening for your custom widget or is it also happening in, say, for example the icon widget?

**Comment by andrejarh** [comment]
SiteOrigin Icon widget works without any issues, it stopped working only when used in custom widget. Here is the code from the custom widget
`			
array(
    'title' => array(
        'type' => 'text',
        'label' => __('Widget Title', 'mytheme'),
    ),	    
	'widget_repeater' => array(
        'type' => 'repeater',
        'label' => __( 'Add Document' , 'mytheme' ),
        'item_name'  => __( 'Click to add a document', 'mytheme' ),
        'item_label' => array(
            'selector'     => "[id*='document_name']",
            'update_event' => 'change',
            'value_method' => 'val'
        ),
    	'fields' => array(
		    'document_name' => array(
		        'type' => 'text',
		        'label' => __('Document Title', 'mytheme'),
		        'default' => ''
		    ),
			'document_icon' => array(
			    'type' => 'icon',
			    'label' => __('Icon', 'mytheme'),
			),					    
			'document_upload' => array(
		        'type' => 'media',
		        'label' => __( 'Upload a document', 'mytheme' ),
		        'choose' => __( 'Choose a document', 'mytheme' ),
		        'update' => __( 'Upload a document', 'mytheme' ),
		        'library' => 'application',
		        'fallback' => true
			),
		),
    ),
)`

**Comment by AlexGStapleton** [comment]
Okay thanks for that - spotted the issue. The field is currently locked to the label of form. To continue using this widget for the time being you'll need to change the label to icon.

**Comment by andrejarh** [comment]
This was blazing fast.
I can confirm the new patch solves the issue.
Thank You @AlexGStapleton,
you guys rock!
