### ISSUE TITLE
Testimonial Widget: Use the URL field

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#33]
The URL field in the testimonial widget isn't being used.

https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/testimonial/tpl/default.php

**Comment by gregpriday** [comment]
This can be done at the same time https://github.com/siteorigin/so-widgets-bundle/issues/36

**Comment by braamgenis** [comment]
Resolved in 1d3b02c9c633b16ec6f0314668b29d5188399881
