### ISSUE TITLE
Google Maps: When Google Translate script is present, map won't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#332]
After the recent Google Maps code update users have reported (and I've been able to replicate) that the Google Maps widget won't work when the Google "[website translator plugin](https://translate.google.com/manager/website/)" is present. The error message present is:

> js-map.min.js?ver=1.7.1:formatted:230Uncaught TypeError: Cannot read property 'Geocoder' of undefined

References:
![](https://i.imgur.com/b2yYYPC.png)
[Test Layout](https://u.teknik.io/RI7Qq.json) (with script code already present)

**Comment by gregpriday** [comment]
@braamgenis - can you handle this one?

**Comment by braamgenis** [comment]
Fixed: 7b98a3d6b17d2116ef276fa8323471875c1d0731
