### ISSUE TITLE
[embed] doesn't work in Editor or Text Widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#335]
The [embed shortcode](https://codex.wordpress.org/Embed_Shortcode) is a standard WordPress shortcode that allows users to [embed media](https://codex.wordpress.org/Embeds#Okay.2C_So_What_Sites_Can_I_Embed_From.3F) and specify parameters such as width and height, doesn't work anymore.

Nothing is output.

[Reference layout](https://u.teknik.io/2TAaQ.json)

**Comment by braamgenis** [comment]
@AlexGStapleton I don't think it's supposed to work in the Text widget. Did it ever work in our Editor widget? Looking at the current code I'd be surprised if it did, as it seems WP handles the `[embed]` shortcode differently to other shortcodes. It's processed earlier than other shortcodes and then the processing function is removed. See [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-embed.php#L33) and [here](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-embed.php#L49) :confused: So by the time we do our shortcode processing, the `[embed]` shortcode handling simply returns `false`

**Comment by braamgenis** [comment]
@AlexGStapleton Looks like there was an "easy" fix for this. :metal: Please check it out and see if it works for you?

**Comment by AlexGStapleton** [comment]
I was positive it did, but I guess it never did if that was the solution. 😕 

Just tried develop and it works! 👍
