### ISSUE TITLE
Preview issue for widgets with namespace

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#340]
[Reported in this thread](https://siteorigin.com/thread/widget-with-namespace-doesnt-show-preview/#comment-104334). [Please try this reference widget](https://gist.github.com/epinephrin/9269e2ae0981c0a53bad25c9947babf7).

Previewing this widget will result in an endless loading screen. The issue is that the class (which has a namespace) that is sent to siteorigin_widget_preview_widget_action() is escaped with extra /.  So, rather than VM\Widgets\SO_Widgets it's actually VM\Widgets\SO_Widgets which is obviously invalid.

**Comment by braamgenis** [comment]
We're still supporting down to PHP 5.2, so we don't allow namespaces yet. I think we'll be increasing the minimum supported version soon, then we can look into this and other namespace related issues.

**Comment by AlexGStapleton** [comment]
Unfortunately, we must continue to support PHP 5.2+ for as long as WordPress officially supports it.
I remember reading that WordPress will be dropping support for PHP 5 sometime in 2019 (I _think_ it was towards the end of the year) but I can't seem to find it again.

**Comment by drzippie** [comment]
WordPress officially requires PHP 5.6 or higher, so it would be necessary and important to change this ;-)
https://wordpress.org/news/2019/04/minimum-php-version-update/

**Comment by AlexGStapleton** [comment]
Hi @drzippie,

Greg has added support for namespaces [here](https://github.com/siteorigin/so-widgets-bundle/commit/21004c5d1cdd6f812b3282db761a5d2bacf21f9e). Are you still having issues with your plugins/themes namespace? If so, can you please provide me with a link to your plugin/theme? This will allow us to run some tests against the widgets.

Kind regards,
Alex
