### ISSUE TITLE
Sanitization of url in icon widget

### ISSUE THREAD

**Issue by suganyaselvakumar** [siteorigin/so-widgets-bundle#342]
Thanks for giving me a wonderful plugin.

 I have faced a problem in SO-Icon widget anchor is not working properly.
 I think that this is the url validation issue.
 Instaed of esc_attr_e($url) changed to sow_esc_url($url). 
  <a href="<?php **esc_attr_e( $url )** ?>"

**Comment by AlexGStapleton** [comment]
Preface: This is a development version. Please do not test this version on a production site.

Sorry, didn't see this until now. Can you try replicating the issue you're experiencing in the [latest version of develop](https://github.com/siteorigin/so-widgets-bundle/archive/develop.zip)? 

To install develop, please navigate to **WP Admin > Plugins > Installed Plugins** and deactivate the SIteOrigin Widgets Bundle. Then click Add New > Upload Plugin and upload /activate develop.

**Comment by braamgenis** [comment]
Just checked and this is working in our latest release version 1.8.1.
