### ISSUE TITLE
Convert Black Studio Editor to Siteorigin Editor

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/so-widgets-bundle#352]
I have an old site that still uses the old Black Studio TinyMCE Widget. I know it probably doesnt make a difference but this inconsistency with my other sites and the fact that the site now is a mix of old Black Studio and new Siteorigin Editor widgets is driving me nuts.

Is there a way to convert them all to the native Siteorigin editor?

**Comment by AlexGStapleton** [comment]
While we would obviously prefer that you use our widget, we can't just change the widget the user is using without their consent. It also wouldn't be fair for Black Studio as there are a decent chunk of users using the Black Studio editor over the SiteOrigin Editor.

Sorry mate. :(
