### ISSUE TITLE
Social Media Icons: Icon doesn't change color if no background is set

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#355]
The social media icon color setting doesn't seem to take effect if a background color isn't set. Ideally, the icon color could be set on its own. The use case for this at the moment is the social icon settings in Unwind in the menu. A background isn't really applicable there but we do need users to be able to change the icon color without setting a background.

**Comment by braamgenis** [comment]
@Misplon This seems to work about as expected for me. The only thing which may be considered slightly strange behaviour is when using the _Wire_ button theme, the icon only shows the selected color in the hover state. Which means if the _Use hover effects_ checkbox field is unchecked it will appear as if the icon color isn't taking effect.

**Comment by Misplon** [comment]
@braamgenis The original issue has resolved. It's no longer a problem. If you can perhaps work the issue you've uncovered, that would be sweet.

**Comment by Misplon** [comment]
@braamgenis Check the demo: http://demo.siteorigin.com/unwind/. If no background color is set, hover effects don't do anything. Do you want to make any changes in that regard?

**Comment by braamgenis** [comment]
@Misplon Hmm... I'm not sure what you mean by the issue I've uncovered? Everything seems to work about as I would expect it to work. Could you perhaps give a specific example of what isn't working as you would expect?

As far as the demo goes, the hover effects are working as they should, they are just so subtle that they're not really noticeable without the background.

**Comment by Misplon** [comment]
_As far as the demo goes, the hover effects are working as they should, they are just so subtle that they're not really noticeable without the background._

Sweet. Done.
