### ISSUE TITLE
not pulling google map API key to the template

### ISSUE THREAD

**Issue by kk77** [siteorigin/so-widgets-bundle#358]
https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/google-map/tpl/js-map.php
we need this:
data-api-key="API_KEY"

**Comment by AlexGStapleton** [comment]
[The key is set elsewhere](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/google-map/js/js-map.js#L388) so that attribute isn't required.

**Comment by kk77** [comment]
cool, thanks
