### ISSUE TITLE
Live editor and font fields

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/so-widgets-bundle#373]
If more than one widget has a custom font, only the first widget in the page builder has the custom font applied in the live editor. No problems in the front end. :)

Let me know if you need more details. Thanks

**Comment by gregpriday** [comment]
I tested this with the headline widget, and I don't seem to be getting the same issue. Both headline widgets are taking on the font.

![screen shot 2016-12-12 at 6 05 53 pm](https://cloud.githubusercontent.com/assets/1126859/21106157/a5f8a3ac-c095-11e6-9284-85f09bcac9b1.png)

Is there anything else about your setup that could be causing this?

**Comment by braamgenis** [comment]
This is happening for me too.
