### ISSUE TITLE
Google Maps widget doesn't work when Shortcode Ultimate is installed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#384]
The Google Maps widget doesn't work when [Shortcodes Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/) (600k+). The following error message appears in the console:

> js-map.min.js?ver=1.7.2:formatted:283Uncaught TypeError: Cannot read property 'libraries' of undefined
>     at HTMLDocument.<anonymous> (js-map.min.js?ver=1.7.2:formatted:283)
>     at i (jquery.js?ver=1.12.4:2)
>     at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
>     at Function.ready (jquery.js?ver=1.12.4:2)
>     at HTMLDocument.K (jquery.js?ver=1.12.4:2)
> (anonymous) @ js-map.min.js?ver=1.7.2:formatted:283
> i @ jquery.js?ver=1.12.4:2
> fireWith @ jquery.js?ver=1.12.4:2
> ready @ jquery.js?ver=1.12.4:2
> K @ jquery.js?ver=1.12.4:2

![](https://i.imgur.com/KWQ09BT.png)

**Comment by AlexGStapleton** [comment]
Never mind, I'm insane - this was an issue with their API key. :/

**Comment by braamgenis** [comment]
Hmmm... I'm glad the issue was just a missing/incorrect API key. We should maybe handle it more gracefully than a seemingly unrelated error. :sweat_smile: Perhaps log a nice descriptive error message to the console so users can more easily tell what's wrong.

**Comment by AlexGStapleton** [comment]
Yeah, that might be a better overall solution but this is honestly the first time I've ever seen this error message so I doubt this one will come up very often - at least it's searchable now.
