### ISSUE TITLE
Maps: Handle API errors more gracefully

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#385]
As per @braamgenis's [comment](https://github.com/siteorigin/so-widgets-bundle/issues/384#issuecomment-269631130).

We should try and "catch" API errors rather than have an unclear and confusing error output (see #384 for an example of this). While we _might_ know what the error actually means, users don't. This leads to confusion and in turn, frustration for something that might actually require a very easy solution.

**Comment by braamgenis** [comment]
Related #265

**Comment by braamgenis** [comment]
As commented in #265 there's no reliable way to check whether an error has occurred. Some people suggest checking whether the maps API has loaded after a set time and if not an error must have occurred, but this seems too unreliable to me. So I'm closing this for now.
