### ISSUE TITLE
Not an issue, a question

### ISSUE THREAD

**Issue by nickmak** [siteorigin/so-widgets-bundle#389]
I am trying to tie into the Image widget that you have. 

Now I've created a field to allow for tagging images with classes, however I can't seem to get it or figure out how to tie it to the $classes arrary in the default.php file in the widget folder.

Here is my initial code: 
		
    function sow_image_add_class( $form ){
        $form['class_field'] = array( 
		'type'		=>	'text',
		'label'		=>	__( 'Add Class to the Image', 'so-widgets-bundle' )
	);
	
        return $form;
				
    }
    
    add_filter('siteorigin_widgets_form_options_sow-image', 'sow_image_add_class', 10, 2);

Now, I've tried to filter into it using `siteorigin_widgets_template_html_sow-image` but I don't think that's the right spot, if it is, I get a return of array when doing the following within it's own function.
   
    add_filter( 'get_template_variables_sow-image', $instance, $classes );
    $classes = array('so-widget-image', 	$instance['class_field'],	);
    return $classes;

Any help is appreciated! Thank you.

**Comment by adiraomj** [comment]
A simple way would be to use the `siteorigin_widgets_image_attr` filter. 

```
function sow_change_image_class( $attr, $instance ) {
        $attr['class'] = 'so-widget-image ' . $instance['class_field'];
	return $attr;
}
add_filter('siteorigin_widgets_image_attr', 'sow_change_image_class', 10, 3);
```

Hope this helps.

**Comment by nickmak** [comment]
This worked like a charm! Thank you so much!
