### ISSUE TITLE
Build Post Query button and Posts Carousel

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/so-widgets-bundle#396]
Hi. A user recently reported that the **Build Post Query** button in my widgets work only if the **SiteOrigin Post Carousel** widget is active. Might be worth looking into. :)

**Comment by braamgenis** [comment]
Hey @adiraomj I've got a test widget using the posts field type and it seems to work with the Post Carousel widget deactivated. Could you give more details about what exactly isn't working?

**Comment by AlexGStapleton** [comment]
I just tried to replicate this issue and I can't either. As this was posted so long ago and we haven't received a similar report I'm going to close this. Let me know if someone else reports this and we'll pick this back up.
