### ISSUE TITLE
Google Maps: Do not geocode address if latitude and longitude is supplied.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#399]
In certain instances, Google will return the wrong location if provided with a latitude and longitude. An example of this is 45.481491, 12.588431 which is returned as 45.482889, 12.586389 for whatever reason. As such, we should place the marker based on the supplied latitude and longitude.

**Comment by braamgenis** [comment]
We already do this. And just to double check I entered the above coordinates into both our maps widget and the google maps app and they give exactly the same result.

**Comment by AlexGStapleton** [comment]
Huh, that's odd. When I initially posted this the results were definitely different. I'll try and track down the Google Map post I was using at the time.

**Comment by AlexGStapleton** [comment]
Another user reported something similar that I feel is related. 

![](https://i.imgur.com/vuQPj5h.png)

The first marker should be on the church but for some reason, it's appearing on a house next to the road. This is inconsistent with Google Maps, and while that's not uncommon, this is latitude and longitude which should vary depending on the different data sets.
 
The really odd thing about it is that the user managed to get it working by wrapping the latitude and longitude in brackets. which is why the second icon works.

[Reference layout](https://u.teknik.io/gZeba.json)
