### ISSUE TITLE
Implode issue with link field

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#403]
A few people have reported this error recently (before and after the update):

PHP Warning: implode(): Invalid arguments passed in public_html/wp-content/plugins/so-widgets-bundle/base/inc/fields/link.class.php on line 23

I suspect this is due to only having a single post type present.

**Comment by gregpriday** [comment]
Reported here too: https://wordpress.org/support/topic/possible-bug-found-2/

**Comment by AlexGStapleton** [comment]
I've had a number of reports of this since the update. Maybe something in the update exacerbated this issue?
