### ISSUE TITLE
Elementor: duplicated widgets missing CSS

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-widgets-bundle#404]
Issue reported [here](https://siteorigin.com/thread/siteorigin-widget-bundle-conflict-with-elementor-plugin/)

Intermittently, a duplicated widget's dynamically generated styles will be deleted while editing the widget. Saving and refreshing the page returns everything to normal.

**Comment by braamgenis** [comment]
I can't seem to reproduce this anymore. @AlexGStapleton Could you please take a shot at it and see if you find any issues?

**Comment by AlexGStapleton** [comment]
I've run a few tests and I can't replicate this issue. Elementor has had a pretty major update since 1.2.0 so that may have indirectly fixed this.

**Comment by gregpriday** [comment]
Awesome, I'm happy to close this and reopen if it comes up again.
