### ISSUE TITLE
Masonry: Layout after images have loaded

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-widgets-bundle#406]
Reference: #401 

Check whether `imagesLoaded` is triggering layout after images have loaded and if not remove and find alternative solution.

**Comment by braamgenis** [comment]
@AlexGStapleton I tried to reproduce this with images totalling around 4.3MB and throttled down to 250kb/s to that it took around 2m42s to download and the masonry layout still happens correctly. Can you give any more detail on exactly what's going wrong and how?

**Comment by AlexGStapleton** [comment]
Oh! Somehow I missed this reply. :(

I'm not too sure why you can't seem to replicate it. Hm. Try removing lines [69](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/simple-masonry/js/simple-masonry.js#L69) through [74](https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/simple-masonry/js/simple-masonry.js#L74). Does that allow you to replicate it? Other than that, I'm not too sure.

**Comment by braamgenis** [comment]
If I remove those lines completely, then it won't work at all, but even if I just remove the `setTimeout` and use throttling to simulate slow loading, it still seems to work just fine. :confused:

**Comment by braamgenis** [comment]
Closing this issue for now, until we get another report.
