### ISSUE TITLE
Headline: Missing Order Field

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#407]
A user reported having issues where the SiteOrigin Headline widget isn't showing for them. They provided me with [this layout](https://u.teknik.io/X9vgB.json). The Element Order field isn't showing the order options and as a result, the headline widget isn't being rendered on the frontend.

![](https://i.imgur.com/qKUjmUV.png)

The latter makes sense based on the template code but the actual missing order field doesn't.

To replicate this issue, please import [this layout](https://u.teknik.io/X9vgB.json). You can also add a new SiteOrigin Headline widget and it'll display correctly for whatever reason.

**Comment by braamgenis** [comment]
This was happening because somehow the order field's value ended up empty. So the "fix" just resets to the default value, if that ever happens.

**Comment by AlexGStapleton** [comment]
I doubt it'll happen often so this is likely the best overall solution.
