### ISSUE TITLE
Hero: Slide height calculation happens before FitText is run

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#408]
The Hero widget slide automatic height calculation happens before FitText is run on initial load. This can be a huge issue on mobile devices if the header font size is set to a very high amount while the resized header size is significantly lower.

You can view this issue [here](http://alex.siteorigin.net/hero-issue/).

![](https://i.imgur.com/xdiX1rq.gif)

**Comment by braamgenis** [comment]
@AlexGStapleton Hmmm, I was able to reproduce this, but now I can't. I think this was possibly fixed by the fix for another issue. Mind checking if this is still a problem for you?

**Comment by AlexGStapleton** [comment]
I'm still able to replicate this with the current version. Do you want me to try develop?

**Comment by braamgenis** [comment]
Yeesh, I'm having one of those days. All good. I've reproduced and fixed. :+1:

**Comment by AlexGStapleton** [comment]
Awesome - thanks mate! 😃
