### ISSUE TITLE
Google Map: Prevent Roboto Font Import

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#418]
Google Maps will import Roboto into the main page on inclusion and this can lead to some inconsistent fonts if the user is already using Roboto with a non-default font-weight - enable being Roboto (100). An example scenario is that a user using North sets their Headings font to be Roboto (100), this will appear differently on a page with the Google Maps widget present (with a valid API key). 

This can apparently be resolved by [removing the CSS link with JavaScript](http://jsfiddle.net/coma/7st6d9p2/) during the setup of the map, although I personally haven't tried it and thus can't vouch for it.

**Comment by vollyimnetz** [comment]
This is currently VERY questionable from a legal point of view. 

The sow maps plugin added a style in the header, to use the roboto font for the maps info window. Once maps is included, it will automaticly add the fonts by a google service. So if you not use google-fonts anywhere else on the site you suddenly have to insert a paragraph in your privacy policy about google-fonts.

**Comment by vollyimnetz** [comment]
Thats the style that is added.
```
<style type="text/css">.gm-style {
        font: 400 11px Roboto, Arial, sans-serif;
        text-decoration: none;
      }
      .gm-style img { max-width: none; }</style>
```

**Comment by AlexGStapleton** [comment]
I can assure you, this isn't something we're intentionally adding - Google Maps automatically adds it. Regrettably, we've looked into this in the past and we couldn't find a reliable method of removing the font. There may be one now so we'll take another look shortly.

**Comment by vollyimnetz** [comment]
Ah, ok. Thats odd.

Had you tried this / is this an option: 
https://cameronjonesweb.com.au/blog/fix-google-maps-including-overriding-roboto-fonts/

**Comment by AlexGStapleton** [comment]
Sorry for the delay - I didn't see this notification.
The issue with that fix is that removes the stylesheet, it doesn't prevent the connection in the first place. :(

**Comment by vollyimnetz** [comment]
OK, thank you very much.

**Comment by Misplon** [comment]
I'm going to close this for the time being. If Google provides a standard option to disable the font import, we'll gladly provide it as a setting.
