### ISSUE TITLE
Elementor: Fluid form elements

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#425]
There are a few responsive issues with certain form fields that should be addressed in a future update. An example field is the link field. Here's a quick example of that:

![](https://i.imgur.com/5UW4pTv.gif)

We should account for the maximum Elementor panel width and the minimum width for all fields.

**Comment by braamgenis** [comment]
Fixed in 8d96124411bd50ab86c20b6a67edc48c307cb30d, e2aec74ce285525b027b9777150d006c7438e216, cd6fc529bd10664f993dfa6f442f6382336898e0, and 878f47664b6733aadf3b9c4dbc3e466a546bdcd2
