### ISSUE TITLE
Video Player: Add FitVids.js support

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#426]
While we currently integrate with [FitVids.js](http://fitvidsjs.com/) for our themes, none of our current (as in, non-legacy) widgets include FitVids.js support. This is problematic for people not using a theme that includes FitVids support so we should include FitVids for the SiteOrigin Video Player widget.

Please note that there will definitely need to be an option of disabling FitVids.

**Comment by Misplon** [comment]
If we did this we'd need to look for FitVids and Jetpack Responsive Videos already being present and only include if they weren't.
