### ISSUE TITLE
Beaver Builder: Font Family issues

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#430]
Two up and coming plugins make use of styling that completely overrides the font family for everything but  `<i>`. This is a big problem for our icons use divs to display the font and as they result in the classic invalid character box.

The plugins are [PowerPack Lite for Beaver Builder
](https://en-au.wordpress.org/plugins/powerpack-addon-for-beaver-builder/) (3k) and [Ultimate Addons for Beaver Builder - Lite
](https://en-au.wordpress.org/plugins/ultimate-addons-for-beaver-builder-lite/) (2k).

References:
![](https://i.imgur.com/gaor1nA.png)
![](https://i.imgur.com/gNb6SxG.png)

**Comment by AlexGStapleton** [comment]
[Found in this thread](https://siteorigin.com/thread/icon-does-not-show-siteorigin-conflicts-with-beaver-builder/).

**Comment by braamgenis** [comment]
Lowered priority as these are fairly small plugins with 2k-3k installs. If this comes up a lot, we can raise priority again.

**Comment by Misplon** [comment]
@AlexGStapleton Can you look at this for us? Can we not add specificity to our rules?

**Comment by AlexGStapleton** [comment]
I mean, we may as well force it. It's not like we don't have to do that elsewhere anyway.

**Comment by Misplon** [comment]
Awesome, thanks.
