### ISSUE TITLE
Elementor: Setting a section to full width stretched will cause the section interface buttons to be covered

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#431]
Setting a section to full width stretched will cause the section interface buttons to be covered and the only way to uncover is to resize the Elementor panel or save and then reload. This doesn't happen when the SiteOrigin Widgets Bundle isn't active. I don't know the exact cause, but this doesn't happen when compat/elementor/styles.css isn't loaded.

Here are the steps to replicate:

1. Create new section
2. Set selection to be full width and stretched

![](https://i.imgur.com/c23LO8h.gif)

**Comment by braamgenis** [comment]
@AlexGStapleton This doesn't seem to happen for me with the default of full width page layout in Vantage. Could you please check if this is still an issue for you?

**Comment by AlexGStapleton** [comment]
This is no longer occurring for me or the person who reported it. I suspect this was indirectly fixed as a result of an Elementor update. :ohwell:
