### ISSUE TITLE
Layout Slider Overrides Headline color setting

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#432]
The layout slider will override the SiteOrigin Headline widget's headline and sub-headline colors. Ideally, the layout slider should only be able to override things like the text widget and the editor widget and shouldn't be able to override the headline widget.

![](https://i.imgur.com/khclNnb.png)

**Comment by Misplon** [comment]
@braamgenis Could we perhaps attend to this one in the next WB run?

**Comment by braamgenis** [comment]
Cool, will take a look.

**Comment by braamgenis** [comment]
My solution for this is to hide the form fields, but keep using the settings if they were previously set. I've added a filter `sow_layout_slider_show_heading_fields` which will allow users to display the fields again if they were using them for whatever reason.

**Comment by Misplon** [comment]
Super, thanks.

**Comment by Misplon** [comment]
@braamgenis It looks like this hides the global settings if they've been set. The user then has no way to change them. For the user I'm working with I was going to ask them to revert the global settings to default so the widget level settings would work. Can we consider changing this logic?

Would it be possible to save the headling and color settings as empty if the user clears them?

<img width="472" alt="clear" src="https://user-images.githubusercontent.com/789159/57517106-64418100-7316-11e9-987c-09f8c684dde9.png">

For users asking about this issue, we'd ask them to clear the values in the global settings. And I'd document this.

**Comment by braamgenis** [comment]
So yeah, check my previous comment again. I added a filter to allow displaying those fields. Then if the user clears them and saves, the defaults should no longer be used.

**Comment by Misplon** [comment]
Braam and I chatted quickly on Slack. We're keeping the current fix. Forward!
