### ISSUE TITLE
Hide extra player element in video widget.

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/so-widgets-bundle#434]
It would be nice to have the ability to disable things like the related videos that appear at the end of youtubevideos.

Regular imbeds give the options to turn them of amongst other things.

I guess a simple "all or nothing" checkbox would be the easies way to do it without cluttering the interface.

Example: 

- [x] Disable player extras (related videos, share buttons etc.)

**Comment by gregpriday** [comment]
Is there still a way to do this in YouTube? I seem to remember that they disabled some settings, but that might have just been video quality.

**Comment by AlexGStapleton** [comment]
Closing this in favor of recommending that users install a plugin that extends WordPress YouTube oEmbed functionality - such as [Hide YouTube Related Videos](https://wordpress.org/plugins/hide-youtube-related-videos/).

Currently, the only way we can do this now is to ditch oEmbed (or risk affecting all videos on the site) and manually embed the video which isn't ideal.

Internal Note: [Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1527665509000345)
