### ISSUE TITLE
Elementor: Unable to add SiteOrigin Slider widget

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#435]
When you add a standard SiteOrigin Slider widget to Elementor, the widget settings will never appear due to a 500 error. If you save the page, the entire page will not be useable due to this error occurring on load.

![](https://i.imgur.com/yeR3i4J.gif)

Here's a screenshot of what is seen when you save after adding the slider and then reload:
![](https://i.imgur.com/64RR2Iy.png)

Stack Trace:

> [18-Mar-2017 11:20:31 UTC] PHP Fatal error:  Cannot unset string offsets in D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\widgets\slider\slider.php on line 204
> [18-Mar-2017 11:20:31 UTC] PHP Stack trace:
> [18-Mar-2017 11:20:31 UTC] PHP   1. {main}() D:\wamp\www\siteorigin\index.php:0
> [18-Mar-2017 11:20:31 UTC] PHP   2. require() D:\wamp\www\siteorigin\index.php:17
> [18-Mar-2017 11:20:31 UTC] PHP   3. require_once() D:\wamp\www\siteorigin\wp-blog-header.php:19
> [18-Mar-2017 11:20:31 UTC] PHP   4. do_action() D:\wamp\www\siteorigin\wp-includes\template-loader.php:12
> [18-Mar-2017 11:20:31 UTC] PHP   5. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> [18-Mar-2017 11:20:31 UTC] PHP   6. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> [18-Mar-2017 11:20:31 UTC] PHP   7. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP   8. Elementor\Editor->init() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP   9. Elementor\Editor->print_panel_html() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\editor.php:66
> [18-Mar-2017 11:20:31 UTC] PHP  10. include() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\editor.php:138
> [18-Mar-2017 11:20:31 UTC] PHP  11. wp_head() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\editor-templates\editor-wrapper.php:19
> [18-Mar-2017 11:20:31 UTC] PHP  12. do_action() D:\wamp\www\siteorigin\wp-includes\general-template.php:2574
> [18-Mar-2017 11:20:31 UTC] PHP  13. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> [18-Mar-2017 11:20:31 UTC] PHP  14. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> [18-Mar-2017 11:20:31 UTC] PHP  15. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP  16. wp_enqueue_scripts() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP  17. do_action() D:\wamp\www\siteorigin\wp-includes\script-loader.php:1221
> [18-Mar-2017 11:20:31 UTC] PHP  18. WP_Hook->do_action() D:\wamp\www\siteorigin\wp-includes\plugin.php:453
> [18-Mar-2017 11:20:31 UTC] PHP  19. WP_Hook->apply_filters() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:323
> [18-Mar-2017 11:20:31 UTC] PHP  20. call_user_func_array:{D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298}() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP  21. Elementor\Editor->enqueue_scripts() D:\wamp\www\siteorigin\wp-includes\class-wp-hook.php:298
> [18-Mar-2017 11:20:31 UTC] PHP  22. Elementor\DB->get_builder() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\editor.php:147
> [18-Mar-2017 11:20:31 UTC] PHP  23. Elementor\DB->_get_editor_data() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\db.php:98
> [18-Mar-2017 11:20:31 UTC] PHP  24. Elementor\Element_Base->get_raw_data() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\db.php:276
> [18-Mar-2017 11:20:31 UTC] PHP  25. Elementor\Element_Base->get_raw_data() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\base\element-base.php:493
> [18-Mar-2017 11:20:31 UTC] PHP  26. Elementor\Widget_Base->get_raw_data() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\base\element-base.php:493
> [18-Mar-2017 11:20:31 UTC] PHP  27. Elementor\Widget_Base->render_content() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\base\widget-base.php:244
> [18-Mar-2017 11:20:31 UTC] PHP  28. Elementor\Widget_WordPress->render() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\base\widget-base.php:192
> [18-Mar-2017 11:20:31 UTC] PHP  29. SiteOrigin_Widget->widget() D:\wamp\www\siteorigin\wp-content\plugins\elementor\includes\widgets\wordpress.php:105
> [18-Mar-2017 11:20:31 UTC] PHP  30. SiteOrigin_Widget_Slider_Widget->modify_instance() D:\wamp\www\siteorigin\wp-content\plugins\so-widgets-bundle\base\siteorigin-widget.class.php:152
> 
>

**Comment by braamgenis** [comment]
Fixed in 1e917f17c9b2451852c8f72e97b616b3cee15d4a
