### ISSUE TITLE
question on Post selector args

### ISSUE THREAD

**Issue by soniapello** [siteorigin/so-widgets-bundle#438]
Hi I have a question on adding args value on post selector 
for example if I want to have 
```
$args = array(
	        'post_type'      => 'post',
	        'posts_per_page' => $ppp,
	        'cat'            => $cat,
	        'offset'          => $offset,
	    );
```
the first three one can be added from the widget but the last one ?
Is it possible to add it like that ? : 
```
$post_selector_pseudo_query = $instance['someposts'];
$processed_query = siteorigin_widget_post_selector_process_query( $post_selector_pseudo_query );
$processed_query['offset'] = $offset;
```

**Comment by AlexGStapleton** [comment]
You should be able to do this by appending the value to `$post_selector_pseudo_query `. Alternatively, you can use [siteorigin_widgets_posts_selector_query](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/post-selector.php#L106)
