### ISSUE TITLE
Radios in Repeaters several repeaters deep aren't displaying as checked

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#444]
[Reported in this thread](https://siteorigin.com/thread/radio-field-inside-repeater-only-saving-on-last-item/).

fb59e0d has resolved this issue for radios in repeaters one level deep. Radios inside of a repeater inside of a repeater (and so on) are still affected by this issue.

**Comment by Misplon** [comment]
@AlexGStapleton Are you able to resolve this for us?

**Comment by braamgenis** [comment]
I think I've finally fixed this issue between these three commits: 88d80abf732b4f1da78ad662be8337329f28c145, 34d6d29b25777ffb73dbb184bbde6b7873dab8b9, and 9412458dbb34ebca8eb2717057401ad6f93dbbd0. Will still have to check what's going on with state emitters at some point.

**Comment by gregpriday** [comment]
@AlexGStapleton can you check if @braamgenis' commits have solved the core issue?

@braamgenis do we need to fix state emitters to close this issue? What's the actual problem there?

**Comment by AlexGStapleton** [comment]
I just tried this and it no longer appears to be having issues - it looks like the previously outlined commits have resolved this issue.
