### ISSUE TITLE
Icon not showing in Features widget

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#446]
Something changed with the migration to flexbox for the features widget. It no longer displays the selected icon. Looking at the inspector, it's displayed below the container now.

![screen shot 2017-04-01 at 4 39 17 pm](https://cloud.githubusercontent.com/assets/1126859/24579659/da255386-16f9-11e7-9147-5e86d829c608.png)

**Comment by gregpriday** [comment]
The fix for this is part of the way there - https://github.com/siteorigin/so-widgets-bundle/commit/88f5ccdda6cb6e82ec23b8dc954adaa60251348e

The icon display is still a bit off, though.

![screen shot 2017-04-04 at 3 43 56 pm](https://cloud.githubusercontent.com/assets/1126859/24659628/8a00fab2-194d-11e7-9145-cac7422cf543.png)

**Comment by braamgenis** [comment]
This was due to Page Builder import layout not running widgets through their update functions to sanitize the imported layouts widget settings.
