### ISSUE TITLE
State Emitters aren't being triggered on load when several repeaters deep 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#448]
[Reported in this thread](https://siteorigin.com/thread/select-field-inside-repeater-state-emitter-not-firing-on-load/).

It appears as though state emitters aren't working on load when they're several repeaters deep (at least two).

[Example plugin](https://u.teknik.io/K1U9u.zip
)

How to replicate with example plugin: `Set Has a model` (inside of the bubble repeater) to `No` and `Enter a link for the bubble` will appear. Enter a link for the bubble should appear on load if `has_model` is set to no.

This is somewhat similar to #444.

**Comment by alenb** [comment]
Thank you very much Alex!

**Comment by AlexGStapleton** [comment]
No problem.

For reference, @alenb is the person who reported this issue.

**Comment by gregpriday** [comment]
I'll get my mind around repeaters again at some point and fix all these little issues. Deeply nested repeaters isn't something I've actually tested before.

**Comment by AlexGStapleton** [comment]
I just tried the reference plugin and this issue no longer appears to be occurring. It's possible this may have been indirectly fixed. Can someone else try the provided plugin to see if it happens for them?

**Comment by gregpriday** [comment]
We can close for now then. If the issue does happen again, we can either try and fix it or just call it a limitation.
