### ISSUE TITLE
Widget bundle and Ninja form compatibility issues

### ISSUE THREAD

**Issue by LittleHamster** [siteorigin/so-widgets-bundle#450]
Hi guys, seems like the latest version of Widget bundle has compatibility issues with Ninja form, 
I get this error in console: 

```
formData.js:20Uncaught ReferenceError: nfForms is not defined
Uncaught ReferenceError: nfForms is not defined 
    at n.initialize (formData.js:20)
    at n.s.Object (front-end-deps.js?ver=3.0.31:20)
    at new n (backbone.min.js?ver=1.2.3:1)
    at n.initialize (loadControllers.js:130)
    at n.s.Object (front-end-deps.js?ver=3.0.31:20)
    at new n (backbone.min.js?ver=1.2.3:1)
    at n.initialize (main.js:58)
    at n.s.Object (front-end-deps.js?ver=3.0.31:20)
    at n.constructor (front-end-deps.js?ver=3.0.31:21)
    at new n (backbone.min.js?ver=1.2.3:1)
```

as soon I disable the widget bundle the form loads perfectly fine

**Comment by LittleHamster** [comment]
@AlexGStapleton just saw [this issue](https://siteorigin.com/thread/siteorigin-widgets-bundle-conflicts-with-ninja-forms/). I am having the same problem. I think something changed in version 1.8.2 which causes this because I reverted back to 1.8.1 and it works

**Comment by LittleHamster** [comment]
@AlexGStapleton did you put the form inside a layout?
here is a sample json output of the layout I used (1 row, 1 column)
```
{"widgets":[{"filter":"1","text":"[ninja_form id=1]","title":"","type":"visual","panels_info":{"class":"SiteOrigin_Widget_Editor_Widget","raw":false,"grid":0,"cell":0,"id":0,"widget_id":"b1e0d846-0ca2-4b60-a559-2f24f465353c","style":[]}}],"grids":[{"cells":1,"style":[]}],"grid_cells":[{"grid":0,"weight":1}]}
```

in front end, it gives the javascript error in the console

**Comment by AlexGStapleton** [comment]
Thanks. Please untick Automatically add paragraphs and it'll work.
Ideally, I would recommend using the Ninja Forms Widget over a shortcode if you can help it.

**Comment by LittleHamster** [comment]
@AlexGStapleton thanks, that resolved this issue.
