### ISSUE TITLE
Editor: Change when we apply autop

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#454]
In a recent change (989163558dd84be5fcde0f17e1ac07bd42aea80b) Greg reorganized how the Editor handles text to allow for it to be cached with the new page builder cache. Now is this fine but the issue here is that he changed when autop was applied. It's now [applied after shortcode_unautop](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/editor/editor.php#L77) [rather than before like it use to be](https://github.com/siteorigin/so-widgets-bundle/blob/ab2e55c64e3ecfb7bbe355af669e78c321081907/widgets/editor/editor.php#L73).

**Comment by vollyimnetz** [comment]
Hi,
i also added a bugticket on wordpress.org and your own support forum - and got no response. The Problem still exists in 1.8.4.

**How to test**

- add a editor-widget 
- add the content "[test]"
- add the following code in functions.php
```
add_shortcode('test','test_shortcode');
function test_shortcode() {
	$data = '
	(first Line)
	
	(first Line Part 2)';
	return $data;
}
```

**Expected (rendered) Output on the page** 
`(first Line)(first Line Part 2)`

**Actual (rendered) Output on the page**
```
(first Line)
(first Line Part 2)
```

This is especially annoying you add i.e. javascript inside a shortcode, cause it will break the syntax and therefore will change the page behavior.
