### ISSUE TITLE
Google Maps: The Events Calendar conflict

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#456]
[The Events Calendar](https://en-au.wordpress.org/plugins/the-events-calendar/) plugin (500k+ installs) includes usage of Google Maps and their implementation is sadly causing issues with ours. We should look into a potential solution to prevent this conflict.

**Comment by braamgenis** [comment]
@AlexGStapleton Could you please give some more info on exactly when/where the conflict occurs?

**Comment by AlexGStapleton** [comment]
The single event page is affected by this when a Google maps widget is present. You'll likely need to add our widget via the sidebar or footer.

The premium version also has issues with weekly events list but I suspect they're directly related.
