### ISSUE TITLE
Conflict with MonsterInsights

### ISSUE THREAD

**Issue by chriscct7** [siteorigin/so-widgets-bundle#459]
We have a user whose been able to create a conflict between SO (I believe its the widget bundle causing it based on the class names on the HTML, ergo the ticket here) and MonsterInsights (~2 million active installs) of which I'm the lead developer.

When both are active at the same time, attempting to edit a page or post results in a blank page upon the initial loading of the page. I've been unable to reproduce their issue so far, but it is occurring on a couple of their sites.

They have a block of HTML being output that I believe is related to the issue and I'm not sure where precisely it comes from or how to make it (I believe if I can figure out how to get SO to output this on the edit screens, I'll be able to reproduce the issue). 

The HTML fragment in question is below:
```
<div class="siteorigin-widget-form siteorigin-widget-form-main siteorigin-widget-form-main-siteorigin-widget-button-widget" id="siteorigin_widget_form_96b07bd08480eb67b38ef461804fe96c" data-class="SiteOrigin_Widget_Button_Widget" style="display: none">
	<div class="siteorigin-widget-field siteorigin-widget-field-type-text siteorigin-widget-field-text" >
		<label for="widget-sow-button-1-text" class="siteorigin-widget-field-label">Button text</label>
		<input type="text" name="widget-sow-button[1][text]" id="widget-sow-button-1-text" value="" class="widefat siteorigin-widget-input" />
	</div>
	<div class="siteorigin-widget-field siteorigin-widget-field-type-link siteorigin-widget-field-url" >
		<label for="widget-sow-button-1-url" class="siteorigin-widget-field-label">Destination URL</label>
		<a href="#" class="select-content-button button button-small">Select Content</a>
		<div class="existing-content-selector">
			<input type="text" class="content-text-search" data-post-types=""placeholder="Search Content"/>
			<ul class="posts"></ul>
			<div class="buttons">
				<a href="#" class="button-close button">Close</a>
			</div>
		</div>
		<div class="url-input-wrapper">
			<input type="text" name="widget-sow-button[1][url]" id="widget-sow-button-1-url" value="" class="widefat siteorigin-widget-input"/>
		</div>
	</div>
```

Can you point out where this comes from so I can work on trying to replicate this issue and then figure out what needs to happen

**Comment by braamgenis** [comment]
Hi @chriscct7 This is the edit form for our button widget. To make it output on the edit screen you can install [SO Page Builder](https://wordpress.org/plugins/siteorigin-panels/) and then just add a button widget to the page and open it for editing. I have tried this with MonsterInsights installed and didn't seem to have any problems, but I assume that's because I didn't have it connected to a Google Analytics account.

Hope that helps and please let us know if we can help further.
