### ISSUE TITLE
Slider Widget: Ignore empty frames

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#460]
If the user accidently adds an empty slider frame we shouldn't try and display it as it looks weird.

![](https://i.imgur.com/o3QY9Tf.gif)

**Comment by braamgenis** [comment]
IMO this is being a bit overprotective as there's technically nothing "wrong" with having an empty frame, and some users might even do it intentionally, which means there's potential for breakage if we suddenly remove the ability to have empty frames. Perhaps we can just have some kind of "empty frame" warning which the user can choose to ignore.

**Comment by gregpriday** [comment]
I actually agree with @braamgenis on this one. If the user has asked for an empty frame, who are we to say they can't have it.
