### ISSUE TITLE
Post selector categories

### ISSUE THREAD

**Issue by michellomp** [siteorigin/so-widgets-bundle#463]
Hi it's more a question than an issue
I'm using the siteorigin post selector field which allows the user to build a query to find posts in the database. I'm getting back the query result with

 ```
 $post_selector_pseudo_query = $instance['some_posts'];
    // Process the post selector pseudo query.
    $processed_query = siteorigin_widget_post_selector_process_query( $post_selector_pseudo_query );
```

and I'm using it for list categories of this query

```
$categories = get_categories($processed_query);
    foreach ($categories as $cat) {
        echo '<div class="one_fourth">';
        echo '<h1 class="valignmiddle uppercase title-bold">'.$cat->name.'<img src="'.$cat->term_icon.'" alt=""  class="alignleft"/>'.'<br />'.'<span class="solutions">'.$cat->description.'</span>'.'</h1>';
        $post = array( 'posts_per_page' => 5, 'offset'=> 1, 'category' => 10 );
        $posts_array = get_posts( $post );

        echo '</div>';
    }

```
but it list all the categories not only the query's categories
Any idea on how to list only query categories ?
I open a stackoverflow question [here](http://stackoverflow.com/questions/43708852/post-selector-categories)

**Comment by AlexGStapleton** [comment]
Do you still need help with this?

**Comment by AlexGStapleton** [comment]
I'm going to close this. Let me know if this issue is still occurring for you and we'll re-open this.
