### ISSUE TITLE
Features: Custom icons have container size applied rather than icon size

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#467]
The icon images are being given the container size rather than the icon size. This is done [here](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/features/styles/default.less#L82).

An example of this issue can be seen [here](http://alex.siteorigin.net/features-custom-icons-have-container-size-applied-rather-than-icon-size/).
[Here's the exported layout](https://u.teknik.io/yCw7r.json).

**Comment by braamgenis** [comment]
@AlexGStapleton Ok, so I see what's going on here.

The `container_size` property is applied to the icon container background (the shapes), and the HTML element containing the icon.

When it's one of the icons we supply, `container_size` is set on the `span` containing the icon and it doesn't actually affect the icon itself. The icon is a font and it's size is controlled by the `font-size` property.

When it's a custom icon image, `container_size` is set on the `div` which has the image set as it's `background-image`, so the image is as big as the container. The custom icon image size should really be controlled by the `icon_image_size` property instead. The `icon_image_size` is currently only used to specify the size of the source image, but is ignored when actually displaying the image... :confounded:

**Comment by braamgenis** [comment]
@AlexGStapleton I've added a checkbox below the 'Icon size' field which users should check if they want that size to apply to custom icon images. Ideally this would be default behavior, but need to avoid breakage for existing pages.

**Comment by AlexGStapleton** [comment]
Thanks for the heads up. :)
