### ISSUE TITLE
Hero Widget: Automatic height calculation sometimes not working

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#468]
This is a follow-up to #266. It seems the fix for that is quite problematic as certain websites have hero widgets that sometimes do not set a height on the first page load. This can be very problematic for websites that cache pages as it'll result in an invisible hero widget due to the height not being calculated when the cache was generated. I would recommend trying a different solution or reverting 6421e5a.

[Slack reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1493760257753198)

**Comment by gregpriday** [comment]
Emptying the sentinel was mainly for removing things like iframe videos, etc. So perhaps a less heavy handed approach would be to selectively remove elements from the sentinel. Like just stripping out iframes and replacing them with similarly sized DIVs.

There might also be some options around dynamically adding/removing the sentinel. This would account for things like Fitvids resizing video iframes.

A few options, I'll look into this.

**Comment by braamgenis** [comment]
Turns out this wasn't related to the sentinel content being removed, but due to the `fitTextDone` being triggered before the slider has added it's listener for `fitTextDone`.
