### ISSUE TITLE
Contact: If no fields have data submitted, don't output errors

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#471]
If none of the contact form fields have any data, don't show any error messages. This will allow for instances where there are multiple contact forms on a page. Currently, each contact form has its data processed and as a result, there ends up being a lot of visible errors when those other contact forms weren't even interacted with.

**Comment by braamgenis** [comment]
@AlexGStapleton This was only happening when the forms were exact duplicates of each other, which shouldn't happen very often, but should be fixed now anyway.
