### ISSUE TITLE
Google Maps: Only 10 markers are placed on the map at a time

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#472]
Preface: This issue doesn't occur in 1.8.2.

If a user has more than 10 markers, only ten will be drawn (randomly selected) and the rest will never appear. Previously, ten would be drawn and then the rest would slowly appear.

**Comment by braamgenis** [comment]
All markers should display now. However it still only draws 10 and then the rest are slowly added as the query rate limit window moves. Not quite the 50 requests per second stated in their [docs](https://developers.google.com/maps/documentation/geocoding/usage-limits). :confused:

**Comment by AlexGStapleton** [comment]
Oh well. The important thing is that they'll show eventually rather than never.
