### ISSUE TITLE
When SOW is active, TinyMCE Advanced editor styles aren't able to load

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#477]
When the SiteOrigin Widgets Bundle is active, [TinyMCE Advanced](https://wordpress.org/plugins/tinymce-advanced/) (2+ million) isn't able to load its [editor styles](https://plugins.trac.wordpress.org/browser/tinymce-advanced/trunk/tinymce-advanced.php#L219) successfully.

![](https://i.imgur.com/rWHtgef.png)

**Comment by braamgenis** [comment]
@AlexGStapleton The TinyMCE Advanced editor looks the same to me with and without WB active. I've also tried deactivating PB and all other plugins and it still looks OK to me. Could you be a bit more specific with expected vs actual behavior? Also the line (219) of code you linked to above doesn't seem related to the editor itself, but rather to the plugin settings page?

**Comment by AlexGStapleton** [comment]
Yeah, you're right - sorry.

The settings bar (not too sure what it's called) no longer has its background applied as the editor styles aren't loaded when WB is active.

If you have text in the editor and scroll it'll appear like in the provided screenshot - you'll be able to see it through the settings bar when you normally wouldn't be able too.

**Comment by AlexGStapleton** [comment]
Resolved in #512
