### ISSUE TITLE
SiteOrigin Slider -  Bug - Foreground Image

### ISSUE THREAD

**Issue by sigimasteff** [siteorigin/so-widgets-bundle#481]
Hi there, 

when uploading images as a background image, SiteOrigin Slider automatically also puts the same image also as a foreground image. Example attached. Please note that I haven´t uploaded anything as a foreground image. 
![bug_siteoriginslider](https://cloud.githubusercontent.com/assets/28921725/26399408/1d166728-407d-11e7-92f7-923d90bfdbc5.JPG)

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this issue locally. :(
Do you by any chance have a public URL where I can take a look at the issue? This would be the best way for me to diagnose what's going on.

**Comment by AlexGStapleton** [comment]
I just tried to replicate this issue again and I still can't. As this was posted so long ago I'm going to close this. Let me know if this issue is still occurring for you and we will pick this back up.
