### ISSUE TITLE
Button Widget: Ability to link URL based on post meta or shortcode

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#500]
We should add the ability to add a shortcode or a specific post meta to the SiteOrigin Button widget. The reasoning being that the URL will change depending upon the shortcode and/or the post meta. This allows for the user to build more "dynamic" style buttons.

**Comment by Misplon** [comment]
@AlexGStapleton Does this one come up often? Any examples of the post meta you'd link to?

**Comment by AlexGStapleton** [comment]
This comes up every other month. The most recent use case was a shortcode that would output a link based on the user's geolocation.

**Comment by Misplon** [comment]
Thanks for the update.
