### ISSUE TITLE
Indexing broken when using custom field in repeaters

### ISSUE THREAD

**Issue by MichaelPote** [siteorigin/so-widgets-bundle#501]
All fields inside a repeater are given a name originally set with `#repeater-name#` as a placeholder and The SiteOrigin admin.min.js file is supposed to replace these placeholder with the actual index of the field inside the repeater. So eg. I have a repeater called “taxonomies” and I have a custom field called “taxselect”. The name is outputted as `widgets[c59][taxonomies][#taxonomies#][taxselect]` and should be changed to `widgets[c59][taxonomies][0][taxselect]` when the page runs, but it is not. This is causing the field data to mess up when the page is saved.

After some digging around the admin.js file, I found the place where I think this exchange is happening at _line 487 in the updateFieldPositions event_. The problem I can see is that the function is ONLY looking for fields which have the `.siteorigin-widget-input` class. I went back to my custom field and added the `.siteorigin-widget-input` class to my inputs (they were actually select boxes so I had `.siteorigin-widget-select` originally on them) and it now works.

Seems like a bug to me? Or maybe the documentation just needs to explain this better.

**Comment by AlexGStapleton** [comment]
[Related Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1528098703000435)

**Comment by AlexGStapleton** [comment]
We haven't heard from you so it's quite possible you've moved onto a different project. That's completely understandable and I'm very sorry for the delay. I'm going to close this at this time, let me know if you would like to pick this back up and I'll re-open it.
