### ISSUE TITLE
Admin: Remove min-width applied to form container outside of Page Builder

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#503]
[This min-width](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/css/admin.less#L54) will cause display issues on the widgets page (**WP Admin > Appearance > Widgets**). We should either remove it or rewrite it so it only affects Page Builder.

![](https://vgy.me/3iRHlU.png)

**Comment by braamgenis** [comment]
Ah, so this is actually a problem where the post loop widget configuration doesn't specify a width. This has been [fixed](https://github.com/siteorigin/siteorigin-panels/blob/develop/inc/widgets/post-loop.php#L25) just not released yet.
