### ISSUE TITLE
Layout Slides will not be copied when a page is cloned

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#507]
If you clone a page/post with a layout slider present, the layout slider frames will be empty.

This may actually be a PB issue but I suspect it's a WB due to this being related to the builder form type.

**Comment by gregpriday** [comment]
Resolved this with a Page Builder update - https://github.com/siteorigin/siteorigin-panels/commit/a0ec6b78ece05086eac77c7b61509a7686f2366c
