### ISSUE TITLE
Introduce more Global Widget Settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#509]
Currently, only two widgets have global widget settings - Editor (Automatically add Paragraph) and the SiteOrigin Google Maps widget (API key).

We should expand global default widget settings to make better use of this powerful time saver. Possible settings:

- A color field for any field form type (Features, Icon, etc)
- FitText status (Headline and Hero Widget)

**Comment by AlexGStapleton** [comment]
It should be noted that there is now a global setting for the Google Maps widget.

**Comment by Misplon** [comment]
@AlexGStapleton I'd like to close this if you're ok with that. If you spot a widget where there is high demand for global settings, where it'll decrease support, please log that for the individual widget. Thanks mate.

**Comment by AlexGStapleton** [comment]
I'm okay with closing this. The ability to set the default colors is commonly requested so that should still be considered down the line.

**Comment by Misplon** [comment]
After an issue is raised a few times, please, log a specific issue for the widget that is being discussed. Thanks.
