### ISSUE TITLE
Translate the widgets

### ISSUE THREAD

**Issue by luizrw** [siteorigin/so-widgets-bundle#51]
Hy,

Using the plugin these last days, I have developed some additional widgets on its own plugin. Then test the translations and does not work with widgets. With other plugin files works, but with the extra widgets  (e.g. '../path/widgets-extras') not.

This would be a bug? Any suggestion?

Thanks.

**Comment by AlexGStapleton** [comment]
I just tried to replicate this issue again and I can't. As this was posted so long ago I'm going to close this. Let me know if this issue is still occurring for you and we will pick this back up.
