### ISSUE TITLE
Widget Manager Path Comparison fails on windows Pt. 2

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#510]
This is a follow up to #375.

What I did previously allowed for the widget settings button to appear on the widgets but it didn't help with the actual widget settings due to how the widget settings Ajax works (checking paths). As it stands, you're unable to the actual widget settings. This issue is caused due to how we're storing paths - basically, we need to use [realpath()](http://php.net/manual/en/function.realpath.php) more.

An example of an instance where `realpath()` needs to be applied is [this line](https://github.com/siteorigin/so-widgets-bundle/blob/develop/so-widgets-bundle.php#L621). On previous line we use make use of SiteOrigin_Widgets_Widget_Manager->get_class_from_path() which correctly applies `realpath()`. but we don't store the widget class with the correct `realpath()`.

I've run a few tests and it seems to not be another simple fix like in #375 because if you change the path associated with the widget_class - no widget settings appear at all.

**Comment by gregpriday** [comment]
@AlexGStapleton: do you want to submit a PR for this? It'd be much easier for you to add calls to `realpath` where you think they need to go, then test them right away.
