### ISSUE TITLE
Post Loop: include sticky count in total

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#513]
Currently, it can be a tad confusing as to why so many posts are returning if you've only selected two and you have a dozen or so sticky posts. As such, we should include the sticky amount in the total as it's confusing to say the total amount selected is 2 posts when in reality it could be significantly more than that.

I would say one of the following values is enough: `2 (+4 sticky)` or `2 (+4)` or even `2+` (no counter)

**Comment by gregpriday** [comment]
Yeah, I think sticky should be included in the count.

**Comment by braamgenis** [comment]
@AlexGStapleton By Post Loop, you mean the posts selector field? Because that includes a dropdown which lets users specify how sticky posts should be handled. It's possible that isn't working as it should though.

**Comment by AlexGStapleton** [comment]
Oh sorry, yeah you're right - I meant the posts selector field.

To clarify, I'm specifically referring to this counter.

![](https://i.imgur.com/KIuVSLY.png)

 This counter doesn't factor sticky posts and while I, and you, both understand that the Sticky Posts are included others don't. This is basically to prevent any confusion as to why 6 posts (2 of which are sticky) return when they set the Posts Per Page setting to 4.

Alternatively, if we can factor set sticky posts up to allow for pagination that would be better.

**Comment by braamgenis** [comment]
The counter does factor in sticky posts according to what's been selected in the Sticky Posts dropdown. I.e. if a user selects `Default` or `Ignore sticky` then sticky posts are included in the total.

In testing this I uncovered a bug where it wasn't possible to clear the specific date selection fields, which could have resulted in you seeing an incorrect count.

**Comment by gregpriday** [comment]
I'm going to close this. It's fairly similar to https://github.com/siteorigin/so-widgets-bundle/issues/563 where we're just using core WordPress functionality to get the counts.
