### ISSUE TITLE
Prevent Page Builder widget Teaser

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#517]
We should disable the SiteOrigin Page Builder Teaser. This way we'll prevent the following widgets from showing up when they're disabled.

- SiteOrigin Features
- SiteOrigin Image
- SiteOrigin Post Carousel

**Comment by braamgenis** [comment]
@AlexGStapleton Could you elaborate? What's the behavior you expect and what's the actual behavior?

**Comment by AlexGStapleton** [comment]
When you disable one of the above-mentioned widgets by navigating to **WP Admin > Plugins > SiteOrigin Widgets**, they'll still appear in the Add Widgets Interface in page builder.

**Comment by AlexGStapleton** [comment]
Closed due to siteorigin/siteorigin-panels#451
