### ISSUE TITLE
Icon picker not working (1.9.4 update)

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#525]
Hi,
I just updated widget bundle to the latest version and noticed a major issue with icon picker. When you click on the icon picker to select an icon, it opens and closes automatically, so the user can't select the icon. There is no way to keep it open.

I was testing in Google Chrome / OSX

Please see example of this behaviour: http://jmp.sh/Mub1rvl

**Comment by braamgenis** [comment]
Hi, we've just released another update to resolve this issue. Thanks for reporting! :+1:

**Comment by andrejarh** [comment]
I can confirm it's working. Thanks!
