### ISSUE TITLE
Siteorigin Editor widget not working properly after update 

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#526]
After updating Widget Bundle today I noticed another major bug in HTML editor widget. 
If you save the editor in HTML view, the next time you edit it, TinyMCE won't load.

You can easily test this:
1. Add Editor Widget to a page 
2. Switch to HTML view and add dummy text
3. Save page.
4. Edit the Editor Widget again. (TinyMCE will not load)

<img width="1390" alt="screen shot 2017-07-25 at 14 45 26" src="https://user-images.githubusercontent.com/10053621/28573089-b5b57878-7149-11e7-9dbf-af724e2415e2.png">

**Comment by gregpriday** [comment]
Hi @andrejarh - I think the update we released a few minutes ago fixes this. Can you take a quick look?

**Comment by andrejarh** [comment]
I can confirm it's working. You are the best!
