### ISSUE TITLE
Editor: The editor seems to filter out emoji

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#530]
After saving the page. the SiteOrigin Editor widget seems to be filtering out emojis in the editor, but not the preview (until the editor is opened that is). It seems if you add the emoji directly in text mode it works without issue.

To replicate this, add a sentence with a random emoji to a SiteOrigin Editor widget and then save. For example:

> That mixtape is 🔥🔥🔥🔥

![](https://i.imgur.com/VHTi1YB.gif)

**Comment by AlexGStapleton** [comment]
I can confirm this is now happening again. 😢

**Comment by braamgenis** [comment]
@AlexGStapleton Could you please check again? Seems to be working for me at the moment with the following steps:

- Create new page
- Add SiteOrigin Editor widget and pasted the above example text.
- Publish page and view.
- Reopened editor. Emoji are still present.

**Comment by braamgenis** [comment]
@AlexGStapleton Ah, wait nevermind. I see it now. Seems to only happen when switching between Visual and Text modes though?

**Comment by AlexGStapleton** [comment]
What you've found in your last reply is the case for me also.

**Comment by gregpriday** [comment]
Does the core WordPress editor handle this properly?

**Comment by braamgenis** [comment]
Yeah, seems to work as it should in the block editor and with the Classic Editor plugin installed.

**Comment by Misplon** [comment]
I can confirm this happens in the SiteOrigin Editor widget if you save in Text mode. If you add the emoji in the Text tab, it will be lost. If you switch from Visual to Text and back to Visual and save, it's fine. If you add it in Visual and switch to Text and save, it'll be lost. Saving in Text appears to be the issue.

This doesn't appear to happen when using Black Studio TinyMCE.

**Comment by braamgenis** [comment]
Thanks @Misplon. I've found the source of the issue, but not the exact cause yet. It's related to the twemoji TinyMCE plugin, which is supposed to replace emoji with images in the Visual Editor for compatibility with older browsers. The problem is that it's also doing that when in Text mode. Hopefully close to getting this fixed.

**Comment by Misplon** [comment]
Legend! Thanks. 

Do we still need the older browser support?

**Comment by braamgenis** [comment]
I'd say not, but I already tried just disabling the plugin and then it seems to look/function differently to WP core text widget and even BS Visual Editor.

**Comment by Misplon** [comment]
Ahh ok, in it stays :)

**Comment by braamgenis** [comment]
Gah! Wrong branch. 🤦‍♂️
