### ISSUE TITLE
tinyMce style_formats not visible

### ISSUE THREAD

**Issue by vollyimnetz** [siteorigin/so-widgets-bundle#538]
I added some custom style-formats using the following code. The custom formats are shown in normal wordpress-wysiwyg but not in the editor-widget. In prior versions it worked without any issue.
```
add_filter( 'tiny_mce_before_init', 'tm_framework_mce_before_init' );
function tm_framework_mce_before_init( $settings ) {
	$style_formats = array(
		array(
			'title' => 'Button 1',
			'selector' => 'a',
			'classes' => 'btn btn-primary'
		),
		array(
			'title' => 'Button 2',
			'selector' => 'a',
			'classes' => 'btn btn-default'
		),
		array(
			'title' => 'Text-Intro',
			'selector' => 'p',
			'classes' => 'textIntro'
		),
	);
	$settings['style_formats'] = json_encode( $style_formats );
	return $settings;
}
```

pagebuilder version: 2.5.10
so-widget-bundle version: 1.9.6
WP-version: 4.8.1

**Comment by vollyimnetz** [comment]
The bug still exists in 
pagebuilder version: 2.5.10
**so-widget-bundle version: 1.9.7**
WP-version: 4.8.1

**Comment by AlexGStapleton** [comment]
This should be resolved in the latest version. Let me know if updating helps. Very sorry about this!

**Comment by vollyimnetz** [comment]
Yeah it is fixed, thanks you.
