### ISSUE TITLE
[PHP 7.1] Elementor as of 1.6 doesn't work when SiteOrigin Widgets Bundle is enabled

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#539]
When SiteOrigin Widgets Bundle is enabled, I'm getting the following error:

![](https://i.imgur.com/Q7EbTJL.png)

**Comment by AlexGStapleton** [comment]
This doesn't happen for me when using PHP 7.0.10 but it does happen for me when I'm using PHP 7.1.7.

**Comment by braamgenis** [comment]
[Fixed](https://siteorigin.slack.com/archives/C02SYBBH2/p1502846952000213?thread_ts=1502801643.000034&cid=C02SYBBH2)
