### ISSUE TITLE
Posts Form Field: Unable to select post types created by Toolset Types when Jetpack is installed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#540]
When Jetpack and [Toolset Type](https://wordpress.org/plugins/types/) (200k) are installed, the selected post type will be reset to post on save.

Steps to replicate:
- Install and connect Jetpack to WordPress.com (this means this issue can only be replicated on a public facing website)
- Create a new type and add a few dummy posts ([here's an export](https://siteorigin.slack.com/archives/C0312TWU8/p1502788832000175?thread_ts=1502788785.000065&cid=C0312TWU8))
- Add a Post Carousel widget or Post loop widget ot a page and try and select

**Comment by Misplon** [comment]
Toolset Types was closed on the directory on April 4th, 2019. 
https://wordpress.org/plugins/types/
