### ISSUE TITLE
Editor: grunion_media_button not found

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#544]
This is a follow up to #528.

A user has reported that after the SiteOrigin Widgets Bundle 1.9.8 update, they now receive the following warning message when trying to edit a SiteOrigin Editor widget:

`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'grunion_media_button' not found or invalid function name in /home/fondatioua/www/wp-includes/class-wp-hook.php on line 298`

They've stated they only experience this when TinyMCE advanced is enabled but I can't personally replicate that - it could very well be as a result of their toolbar settings. I'm logging this as we should be able to resolve this by simply checking if the grunion_media_button function exists before trying to remove it.

**Comment by ree2theyan** [comment]
This has also occurred for me too. I have no idea how to resolve this.

**Comment by JustDuckyDesigns** [comment]
This has also occurred for me. It seems to only show up (for me anyway) when using the SiteOrigin Editor within a Widget (when TinyMCE Advanced is enabled); I have not seen it on pages yet. I'd like to see a resolution to this.

**Comment by aaron843** [comment]
Yes. I can confirm this happens to me as well. I usually only update plugins if they have been stable for 2 weeks, but apparently this interoperability problem goes back further.

**Comment by AlexGStapleton** [comment]
No longer an issue due to Jetpack changes. If you're still facing this issue please ensure you're using the latest version of the SiteOrigin Widgets Bundle and Jetpack.
