### ISSUE TITLE
Editor: If user has visual editor disabled, changes to widget won't be saved

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#545]
You can disable the visual editor by navigating to **WP Admin > Users > Your Profile** and tick **VIsual Editor**.

[Reference video](https://doc-04-4g-docs.googleusercontent.com/docs/securesc/b090cql7fqrrvb6ljitnujvtlmh9ijlg/jjqbv4uq1htpk7dcg08388tc6n9d06rf/1503885600000/15522570231455504901/15522570231455504901/0BymU-6VMHHPfM1J2S25ZUXNlY0E?h=02211706589536887182&nonce=vv1ligeq09bha&user=15522570231455504901&hash=b08mprg0091to9g5tjts83m2k8ahf1d6)

**Comment by AlexGStapleton** [comment]
I'm fine with that, but can we add a notice or something like that? I ask because even though you and I understand what that setting does, certain people don't and they do get confused why the SiteOrgin Editor doesn't save their changes.

**Comment by braamgenis** [comment]
It turned out to be only slightly more effort to fix the issue, than to display a notice. So went with fixing it instead. 😜

**Comment by AlexGStapleton** [comment]
Oh cool! Thanks mate! 👍
