### ISSUE TITLE
Elementor: SiteOrigin Button disappears when add button text until reload

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#546]
Add a SiteOrigin Button widget to Elementor and try adding text and the button background will disappear. It'll stay missing until you save and reload the page.

![](https://i.imgur.com/ChqiLMk.gif)

I suspect this may be caused by #547

**Comment by AlexGStapleton** [comment]
Hm. This appears to be a general issue with loading SiteOrigin Widget Bundle generated stylesheets as the Headline widget also suffers from the same issue. As does the hero widget and it's also the only widget with an actual console message:

sow-hero-default-bf4548961ea4.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by braamgenis** [comment]
@AlexGStapleton Could please confirm whether this fixed the issue for you?

**Comment by AlexGStapleton** [comment]
All good for me. 👍
