### ISSUE TITLE
Contact Form Widget: Add ability to send to multiple widgets

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#55]
Add the ability to comma separate to: addresses. Right now if you try the comma is removed.

**Comment by gregpriday** [comment]
Seen this requested a few times. Should be easy enough to implement too.

**Comment by Misplon** [comment]
Awesome :)

**Comment by braamgenis** [comment]
Resolved in 1d17831ab0e98ae0adc28ba7acfa24a20d43c99d
