### ISSUE TITLE
Editor strips line breaks

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#552]
Upon saving the SiteOrigin Editor widget, empty lines (read: instances of `&nbsp;`) will be removed from the editor.

Video reference:
https://drive.google.com/a/siteorigin.com/uc?id=0BymU-6VMHHPfQU4wLXpQMUJFUEE

Steps taken in the video:

- Add text to editor with three blank returns
- Show text to verify blank rows contain `&nbsp;`
- Saved and verify spacing
- Enable Page Builder, verified spacing
- Saved and verified spacing was removed upon saving Page Builder.

**Comment by sptutusukanta** [comment]
This is a ridiculous bug of SiteOrigin Editor. It makes it hard to format the content, when it needs newlines.

By default newlines are removed, then I thought to add `&nbsp;` manually, but they just decode the space and wp thinks its a regular space not `&nbsp;` and so removed. Please fix this.

**Comment by scottrpaterson** [comment]
This bug really needs to be fixed.
