### ISSUE TITLE
Editor: Previous editor Mode isn't remembered

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#556]
The new SiteOrigin Editor widget doesn't default to the previously active editor mode.

For example, if I was editing a SiteOrigin Editor widget and added some HTML to the text widget this would previously be fine but due to how the SiteOrigin Editor widget will reset back to the visual mode it'll likely break my HTML.

**Comment by braamgenis** [comment]
Fixed here: 8f1291721f2ddf4160cada99d8c19ceb979c5af3 (Typo in issue number in commit message :finnadie: )
