### ISSUE TITLE
Post Selector: Factor sticky posts into posts per page selector

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#563]
If I have two sticky posts and I set posts per page to 3 posts per page, I'll end up with five posts on the first page. This also happens if I set the posts per page value to 1.

**Comment by braamgenis** [comment]
Ah, yeah so sticky post handling is determined by the 'Sticky posts' field (just below the 'Posts per page' field). E.g. if you want to prevent sticky posts from being sticky but still include them in the query results, that should be set to 'Ignore sticky'

**Comment by AlexGStapleton** [comment]
That's not the issue here. Sticky posts aren't being factored in the output and are bypassing the posts per page setting. People want sticky posts but they also want the posts per page value to be maintained.

**Comment by braamgenis** [comment]
I understand what the issue is and it's not ideal that this doesn't quite function as one would intuitively expect, but this has been out there for quite some time now and to change it now without warning could cause a lot of people to complain. :finnadie:

**Comment by AlexGStapleton** [comment]
I think we should fix it and deal with peoples complaints (I honestly doubt there will be any). If it's not intuitive and isn't intentional, there's little reason to maintain the status quo imo.

What are your thoughts on this @gregpriday?

**Comment by gregpriday** [comment]
For the most part, the post selector field and the widgets that use it, are just calling [WP_Query](https://codex.wordpress.org/Class_Reference/WP_Query). So it's the one deciding this behaviour.

https://wordpress.stackexchange.com/questions/85657/wp-query-pulling-an-extra-post-per-page

So fixing this would require a custom WP_Query class of sorts, which isn't worth it to fix the behaviour that WordPress decided should be default.
