### ISSUE TITLE
Contact: Don't Default To and From Email to the Same Email

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#567]
When a new contact form is added, we need to prevent the To and From email from being the same (which will happen if the user has the site email set to their email also) as it'll be definitely be flagged as spam.

![](https://i.imgur.com/lOFtAp8.png)

I think we should change the from email to wordpress@domain.com in instances like this. if the user doesn't like it, they can adjust it as desired anyway.

**Comment by AlexGStapleton** [comment]
Work was started in the #753 PR.

**Comment by gregpriday** [comment]
Made some additional improvements in https://github.com/siteorigin/so-widgets-bundle/commit/3e862e2fd4d94466f73e8464bc443445e222a5a7
