### ISSUE TITLE
Editor: Unable to use custom editor styles by post type

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#570]
It's currently not possible to do something like [this](https://gist.github.com/leoken/3978368) due to [get_editor_stylesheets()](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/fields/tinymce.class.php#L346) being run at `admin_init` rather than current_screen (or any other hook after `admin_init`).

**Comment by braamgenis** [comment]
I don't think that will work for cases where page builders are using AJAX to retrieve the widget form. Ideally they should be using the `editor_stylesheets` filter to add their stylesheets to the editor as follows:
```
function my_editor_style( $stylesheets ) {
	global $current_screen;
	$style_uri = get_stylesheet_directory_uri();
	switch ($current_screen->post_type) {
		case 'post':
			$stylesheets[] = "$style_uri/editor-style-post.css";
			break;
		case 'page':
			$stylesheets[] = "$style_uri/editor-style-page.css";
			break;
		case 'portfolio':
			$stylesheets[] = "$style_uri/editor-style-portfolio.css";
			break;
	}
	return $stylesheets;
}
add_action( 'editor_stylesheets', 'my_editor_style' );
```

The sucky thing about this way is they'll have to do their own RTL detection and path resolution, but it's the only option I know of for the widgeted TinyMCE editor.

**Comment by braamgenis** [comment]
@AlexGStapleton Actually I could just add an action before calling `get_editor_stylesheets()`, then users should be able hook into that and use `add_editor_style`. Would that work?

**Comment by AlexGStapleton** [comment]
That'll work. :)

People might be upset about the fact their code doesn't work without modification but hey, at least its possible.

**Comment by braamgenis** [comment]
Ah, yeah that's not going to work either. It's missing the required context during the AJAX request for figuring out the post type.

**Comment by AlexGStapleton** [comment]
Oh well. It's not the end of the world mate. We can put this on the backburner until something is implemented in WordPress to allow for this.

**Comment by AlexGStapleton** [comment]
This hasn't come up in a very long time and there doesn't appear to be any real way for us to avoid this at this time. We'll look into again if we receive more reports but for the time being, I think it's best if we close this.
