### ISSUE TITLE
Contact: Add placeholder field

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#585]
We should add a placeholder field in addition to the label field. Alternatively, we should give the option of converting the label to a placeholder.

**Comment by Misplon** [comment]
I think the option of Inside is enough unless there have been several requests for both a placeholder and label.

**Comment by AlexGStapleton** [comment]
I haven't received a request for both in a very long time.

**Comment by Misplon** [comment]
Super, thanks.
