### ISSUE TITLE
Contact Form: Use anchor to return to form after submit

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#59]
After a user submits the contact form, their browser takes them to the top of the page. Ideally it should take them back to where the form is so they can see the success message or any error messages.

**Comment by Nautic** [comment]
I have the same problem and have seen that many other users do too. The issue was closed so I assume there is a solution. 
So **what is the solution here****?** 
If there is no solution yet please reopen and highliy prioritize the issue because in my opinion this is a UX No Go. Thanks.
