### ISSUE TITLE
Site Origin Bundle Googlemaps Widget Not Working

### ISSUE THREAD

**Issue by evanrunningfish** [siteorigin/so-widgets-bundle#592]
I did a couple of google searches and it seems this issue was resolved in the past yet I am still having trouble with it. I've tried different API keys, the static vs. interactive maps, and deactivating and reactivating the widgets. What else should I try?

Website I am working on is www.gbodgroup.com

The place I want the widget should be in the footer under "Location"

**Comment by AlexGStapleton** [comment]
Very sorry for missing this. It looks like you've swapped out the SiteOrigin Google Maps for a different widget. Do you still need help with this?
