### ISSUE TITLE
I don't see all widgets in admin

### ISSUE THREAD

**Issue by yupii1986** [siteorigin/so-widgets-bundle#604]
Hi, In folder widgets i see many widgets but in editor admin i see only 6, how can use all of them

And second, how can i overwrite all widgets? I want to add folder in my theme like i make with woocommerce.

I want to modify one and transform in title with text with font and size changer

Thank you

**Comment by Misplon** [comment]
Hi @yupii1986 Thanks for posting. Please, could you consider putting this question on the support forum at https://siteorigin.com/thread. If you send me the link once up I'll happily escalate it for you.
