### ISSUE TITLE
Widget with global settings defined in theme does not work

### ISSUE THREAD

**Issue by d--j** [siteorigin/so-widgets-bundle#610]
If you define a widget in a theme this widget cannot have a settings form anymore (that worked some time ago).

The button "Settings" will be shown on the widgets overview page but clicking it will just open an empty modal.

The reason is the `WP_PLUGIN_DIR` that gets prepended unconditionally:

https://github.com/siteorigin/so-widgets-bundle/blob/e8d6565050eeb1096784d66c6cb1f4faa3ba986a/admin/tpl/admin.php#L78
https://github.com/siteorigin/so-widgets-bundle/blob/e8d6565050eeb1096784d66c6cb1f4faa3ba986a/so-widgets-bundle.php#L385

Is defining widgets in a theme not supported anymore?

**Comment by Misplon** [comment]
Hi @d--j. Thanks for reporting. We'll try to find the cause of this as soon as possible. So sorry for the hassle.
