### ISSUE TITLE
Hero Widget: Unable to remove text shadow from paragraph text

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#612]
In the Hero widget design section we have: Heading shadow intensity. However, shadow is also applied to paragraph text. So right now we don't have a way to change the paragraph text shadow or to remove it. I suggest we consider re-labelling the shadow intensity field and apply it to both headings and text.

@braamgenis What do you reckon?

**Comment by braamgenis** [comment]
So it's not the heading text shadow that's being applied to the `<p>` text. We have this in the stylesheet for the hero widget:
```
p {
    color: @text_color;
    text-shadow: 0 1px 2px rgba(0,0,0,0.25);
    margin: 1em 0;
    font-size: @text_size;
}
```
So we could perhaps add another field to make the `<p>` shadow configurable?

**Comment by Misplon** [comment]
Perfect. That'll be great.
