### ISSUE TITLE
Overriding template files - get_template_variables() not being passed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#615]
A user is trying to use [the template file override instructions in the SiteOrigin Widgets Bundle](https://siteorigin.com/docs/widgets-bundle/getting-started/extending-existing-widgets/#heading-changing-the-template-file) to override the tabs widget. For whatever reasons, [get_template_variables()](https://github.com/siteorigin/so-widgets-bundle/blob/3200655a900a937e435dd5ec59f7730dd34157ff/widgets/tabs/tabs.php#L197) isn't being passed and only the direct widget settings are.

For reference, here's the code their using:

```
function mytheme_tabs_template_file( $filename, $instance, $widget ){
    return get_stylesheet_directory() . '/tpl/tabs.php';
}
add_filter( 'siteorigin_widgets_template_file_sow-tabs', 'mytheme_tabs_template_file', 1, 3 );
```

Tabs.php is a copy of the tabs widget template file.

[Slack Reference](https://siteorigin.slack.com/archives/C02SYBBH2/p1512123327000302)
[Example Plugin that overrides tabs widget template](https://drive.google.com/a/siteorigin.com/uc?id=1Xk223HWRugTcYpyeeAgf0oqVwQe4cikf)

**Comment by braamgenis** [comment]
I've tested using the above example code and it's working as intended. The variables are successfully extracted and available to the template as `$tabs` and `$initial_tab_index`. Please give more detail about the issue, such as expected and actual behaviour.

**Comment by AlexGStapleton** [comment]
Not too sure what changed but this is working for me now also. 👍
