### ISSUE TITLE
Accordion: Large titles or limited space will result in icon moving below title

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#617]
If you set an long enough accordion title to be two lines, the expand icon will be on the same line as the last line:

![](https://i.imgur.com/yxrNpsz.png)

The same applies if there's not enough available space:

![](https://i.imgur.com/wVDPleA.gif)

Ideally, we should account for this and vertically center the expand icon relative to the title size.

**Comment by acollis** [comment]
Here's how you fix this:

/* Fixes Accordion Title width */
.sow-accordion-title{
  width: calc(100% - 20px);
}
