### ISSUE TITLE
Content Block will duplicate tab widget if widget is present

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#640]
The [Content Blocks](https://wordpress.org/plugins/custom-post-widget/) plugin (30k) stops working correctly if the tabs widget is present on the page. The content block widget is replaced with the contents of the SiteOrigin Tabs Widget rather than what it should be.

**Comment by braamgenis** [comment]
There are a bunch of `Undefined index: ` notices when trying to save a content block widget which makes me not really want to go any further in trying to support this plugin. :finnadie: It occurs in both PB pages and on the Appearance > Widgets page.

**Comment by AlexGStapleton** [comment]
That's completely understandable. I'll suggest switching to an alternative the next time this comes up.
