### ISSUE TITLE
Beaver Builder and Pods: unable to save widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#652]
[Reported in this thread](https://siteorigin.com/thread/bug-report-conflict-with-beaver-builder-standard-plugin-and-pods-widget/).

This issue affects Beaver Builder and [Pods](https://wordpress.org/plugins/pods/) (50k). Basically, you can't save a Pods widget when the SiteOrigin Widgets Bundle is activated. This issue is due to [this line](https://github.com/siteorigin/so-widgets-bundle/blob/develop/compat/beaver-builder/beaver-builder.php#L77) because if it's not present, this issue doesn't occur.

**Comment by braamgenis** [comment]
@AlexGStapleton I was unable to reproduce this in the develop branch. Please confirm whether this still occurs for you?

**Comment by AlexGStapleton** [comment]
Can confirm, no longer occurs with develop.
