### ISSUE TITLE
Beaver Builder: avoid overriding FLBuilder._getSettings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#660]
[Beaver Builder has reported](https://wordpress.org/support/topic/issues-with-beaver-builder-2-0/) a few issues with associated with how we override [FLBuilder._getSettings](https://github.com/siteorigin/so-widgets-bundle/blob/1.11.4/compat/beaver-builder/sowb-beaver-builder.js). We should try and avoid this for greater general compatibility.

[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1519987738000241)

**Comment by AlexGStapleton** [comment]
Beaver Builder has informed me that the widgets referenced in the linked thread are the Beaver Builder Pro widgets, not the SiteOrigin Widget Bundle widgets.

**Comment by braamgenis** [comment]
Should be fixed in 29f280a46445ce4ec128fd94f9953bd6fab4f613
