### ISSUE TITLE
Check Gutenberg compat

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-widgets-bundle#664]
Check the requirements for Gutenberg compat and makes sure we meet them.
See here: https://plugincompat.danielbachhuber.com

**Comment by braamgenis** [comment]
Marked as P1, but monitoring Gutenberg development and will work on it full steam when they start getting close to release.

**Comment by Misplon** [comment]
@AlexGStapleton You happy to close this. We are monitoring and have the big release going out soon.
