### ISSUE TITLE
paragraphs in tinyMCE text/visual mode inconsistency while saving content.

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#665]
Our client reported a really interesting issue in tinyMCE form field. 
While testing, I found out that there are inconsistencies in how text and visual mode save the input content. If the same content is saved in visual mode paragraphs are added to the content (expected behaviour). If you switch to the text mode before saving (without any additional editing), all paragraphs are removed. 

**To recreate this issue:**
1. add some content to the tinymce form with breaks, lists, etc:
![screen shot 2018-03-12 at 09 54 47](https://user-images.githubusercontent.com/10053621/37273972-9fcbf504-25db-11e8-8a47-a74c2feae80a.png)
2. Save while in visual mode.
result on front end:
![screen shot 2018-03-12 at 09 56 59](https://user-images.githubusercontent.com/10053621/37274026-c7675e0a-25db-11e8-96da-9d1802201f52.png)
3. Edit the widget again and switch to text mode before saving.
Result on front end: 
![screen shot 2018-03-12 at 09 58 18](https://user-images.githubusercontent.com/10053621/37274082-eff494e6-25db-11e8-8ae9-cc846a7fc924.png)

**Additional info:**
This was done on a custom widget using a tinyMCE form in a repeater field. All the content is escaped with wp_kses_post() before rendering on front end.

**Comment by AlexGStapleton** [comment]
This sounds like the TinyMCE Editor is stripping spacing when you switch to text mode. After switching to text mode, does the text display as expected in the visual editor?

**Comment by andrejarh** [comment]
Just did additional testing, after updating to SO Panels ver 2.6.3, all formatting is gone in both modes now. 

In version 2.6.2 when switching back and forth, it looked same on the backend. The text displayed OK in the backend.
