### ISSUE TITLE
Contact Form: Use reply-to instead of from in email headers

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#67]
Using `reply-to` instead of `from` would be a more correct choice. Some email servers will reject the email depending on the from email used.

https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/contact/contact.php#L942

**Comment by AlexGStapleton** [comment]
Certain email (such as Yahoo) and web hosting (such as Dreamhost) providers will prevent emails from being sent with the current setup.
