### ISSUE TITLE
Editor: Spacing isn't retained if new lines are added in text tab

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#671]
Editor: Spacing isn't retained if new lines are added in text tab

Add the following to a SiteOrigin Editor widget when in text mode:

```
test

test

test

test
```

Switch to Visual and the spacing will be gone. If you add the same text to Visual, switch to text and then back to Visual, the spacing will remain. This doesn't occur with the default WordPress editor.

**Comment by Misplon** [comment]
@braamgenis Hey pal. To confirm, the core editor and Black Studio Visual Editor widget are able to handle this use case.

**Comment by Misplon** [comment]
https://make.wordpress.org/support/user-manual/content/editors/#switching-editors
