### ISSUE TITLE
Widgets Page: Add new widget icons

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#672]
Add eight new widget icons recently designed. If there is an icon already added for any of these eight, please, replace with the new version.

Icons on [Slack](https://siteorigin.slack.com/files/U02SY6HE4/F9RJ2DL3U/siteorigin_icons.zip).

**Comment by braamgenis** [comment]
Fixed in 35979d9baa69e9ad43b072f922b9bb15ac518737
