### ISSUE TITLE
Testimonials: Standardise label prefixing and capitalisation

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#677]
1. In the testimonial repeater, locate the last setting, the label is: `Open In New Window`. In all other widgets, that's labelled `Open in a new window`. Suggest changing.

2. In the `Design > Image` section should `Testimonial image shape` be `Image shape`?

3. In the `Design > Colors` section, `Widget Background` should perhaps be `Widget background`. The same for `Text Background` and `Text Color`

4. In the Design section, locate the settings cluster at the bottom of the section.

a. `Testimonial Radius`. That should perhaps just be `Radius` OR the `Padding` setting above should be changed to `Testimonial padding`.

b. `Testimonial layout`, should that rather be `Layout`?

<strong>tl;dr</strong>
1. Fix instances of inconsistent capitalisation. 
2. Decide on a pattern of description. In some instances we're using `Testimonial` to prefix the label, I'm not sure there is a consistency to this. I know that in some settings we're differentiating between a scope for each testimonial and a scope for the widget as a whole.

**Comment by braamgenis** [comment]
@Misplon 
1. Yes.
2. Yes.
3. Yes.
4. Not sure what you mean by this or what the purpose of the change is?

a. These don't refer to the same thing so it kindof makes sense that they're named differently, but I do agree that the labels aren't very clear. `Padding` refers to padding around each of the user info and the testimonial text parts. `Radius` refers **only** to the background of the testmonial text part. IMO `Padding` is fine as it refers to general padding in and around the widget. Perhaps we should just change `Testimonial Radius` to something like `Text background radius`?

b. Yes.

**Comment by Misplon** [comment]
a. Sounds good, happy with your suggestions.

4. Ignore, not quite sure what I was seeing there. Have checked, looks good now.
