### ISSUE TITLE
Add more control over widget folders structure

### ISSUE THREAD

**Issue by NazarkinRoman** [siteorigin/so-widgets-bundle#679]
Would be great to have some control over widget file loading process. For now it just looks for `*/*.php` pattern which is not flexible. For example, I'd like to have next directory structure:
```
my-first-widget
-- widget.php
-- template.php

my-second-widget
-- widget.php
-- template.php
```

Current widgets loading process does not allow be to implement this. There is no any filters inside `SiteOrigin_Widgets_Bundle->get_widget_objects()` and `SiteOrigin_Widgets_Bundle->get_widgets_list()` functions to control glob pattern. 

**Different approach without using glob:** load only registered widget files from internal storage of `SiteOrigin_Widgets_Widget_Manager` class.

**Comment by AlexGStapleton** [comment]
Unfortunately, this isn't something we're currently interested in doing but I can definitely understand why you would want this. I'm going to put this on our backlog internally and close this one to remove it from the priority list.
