### ISSUE TITLE
Contact Form: Helvetica Neue not outputting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#681]
In the Contact Form widget when I select `Helvetica Neue` for the form labels, the following is being printed:

`.so-widget-sow-contact-form-default-5f745e04fd46 .sow-form-field > label strong {
    font-family: Arial, Helvetica, Geneva, sans-serif;
}`

I tested using Unwind.

**Comment by braamgenis** [comment]
Hmmm... So then technically the label for that font in the dropdown should be `Arial` ? We can't change the value that's being output as it will change the font for existing users' contact form labels.
