### ISSUE TITLE
Add media button adds image to the wrong #tinyMCE instance in repeater field when duplicated

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#683]
When I duplicate the TinyMCE instance in repeater field and try to add an image into the duplicated instance, the image is added to the previous tinyMCE instance instead. Please check the video: http://jmp.sh/zt61gqF

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this issue in the hero/accordion/tabs widget. Are you able to replicate this issue in any of those widgets?

To clarify, what widget is in the video?

**Comment by andrejarh** [comment]
In the video, there was a custom widget. Here is the same bug with the accordion widget for example:
http://jmp.sh/XmkVqm1

Version details:
SiteOrigin Panels: Version 2.6.3 
SiteOrigin Widgets Bundle: Version 1.11.7

**Comment by AlexGStapleton** [comment]
Ah. I missed the part where you duplicated the widget - that appears to be key to replicating this issue. Are you able to recreate this issue without duplicating the field? I ask because I can't so I just want to completely rule that out.

**Comment by andrejarh** [comment]
Just tested, 
It happens only when an item is duplicated.

**Comment by AlexGStapleton** [comment]
Thanks for confirming. We've given this a priority 1 and this will likely be fixed in the next round of updates.
