### ISSUE TITLE
Contact Form: Add “descriptions” to form fields

### ISSUE THREAD

**Issue by bogdanb** [siteorigin/so-widgets-bundle#69]
It would be nice to have the option of adding a “description” below fields in contact form. 

These are useful for, e.g., reminding people what sort of information is useful in a support request, or linking to a privacy policy when asking for an email address. (So HTML is better than text-only.)

Might be nice to have a “description” setting for the entire form, i.e. to add a message below the submit button. (You can do that separately in the WordPress editor, but if it’s part of the form it could help with styling.)

**Comment by gregpriday** [comment]
Another great suggestion @bogdanb - please keep them coming.
