### ISSUE TITLE
Editor: Certain shortcodes will have their output wrapped in paragraphs

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#694]
Related: siteorigin/siteorigin-panels#522

Certain shortcodes, such as [Smart Slider 3 ](https://wordpress.org/plugins/smart-slider-3/), will have their output wrapped in paragraphs if they're added to the SiteOrgin Editor widget. This is a semi-common issue that is currently avoided by disabling Automatically Add Paragraphs. We should find a way to prevent the need for disabling that setting.

**Comment by nextend** [comment]
Well, I was able to narrow it down. It does not related to Smart Slider.

Steps:

1. Add this test plugin to WordPress: https://gist.github.com/nextend/38591c54cc6dd5dd9032fbd3e64ea321
2. Place [test] shortcode into SiteOrigin Editor widget. Make sure the autop checkbox checked
3. Install Phlox theme and activate: https://wordpress.org/themes/phlox/
4. You should end up with <br> tags in the SVG which is incorrect:
`
<div><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1920 120" preserveAspectRatio="none"><br />
--
  | <g class="n2-ss-divider-start">
  | <path fill="RGBA(255,255,255,1)" opacity="0.25" d="M1920,0 0,120 0,0z" duration="1" delay="0" data-original="M1920,0 0,0 0,0z"></path>
  | <path fill="RGBA(255,255,255,1)" opacity="0.5" d="M1920,0 0,80 0,0z" duration="1" delay="0.2" data-original="M1920,0 0,0 0,0z"></path>
  | <path fill="RGBA(255,255,255,1)" d="M1920,0 0,40 0,0z" duration="1" delay="0.4" data-original="M1920,0 0,0 0,0z"></path>
  | </g><br />
  | <g class="n2-ss-divider-end">
  | <path fill="RGBA(255,255,255,1)" opacity="0.25" d="M1920,0 0,120 0,0z"></path>
  | <path fill="RGBA(255,255,255,1)" opacity="0.5" d="M1920,0 0,80 0,0z"></path>
  | <path fill="RGBA(255,255,255,1)" d="M1920,0 0,40 0,0z"></path>
  | </g></div>

`

So it is probably theme + SiteOrigin Widgets Bundle conflict.

Several themes from our support channel which might have the very same issue:
- virtue
- oxane
- himmelen
- sydney
- roxima
- customizr-pro

**Comment by nextend** [comment]
Okay, I found the cause and I have a suggestion.

These themes add the following `do_shortcode` to the `widget_text` filter:
`add_filter( 'widget_text', 'do_shortcode');`

Line 634 -> https://themes.svn.wordpress.org/phlox/2.0.9/auxin/auxin-include/include/hooks-general.php


https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/editor/editor.php

```
$instance['text'] = apply_filters( 'widget_text', $instance['text'] );

if( $instance['autop'] ) {
		$instance['text'] = wpautop( $instance['text'] );
}

$instance['text'] = do_shortcode( shortcode_unautop( $instance['text'] ) );
```

As `widget_text` fitler runs before your `wpautop`, the shortocde already evaluated and this mess up the html codes.

**Simple solution**
Trick WordPress do_shortcode to do not parse shortcodes while `widget_text` filter does  its job:

```
global $shortcode_tags;
$temp_shortcode_tags = $shortcode_tags;
$shortcode_tags = array();

$instance['text'] = apply_filters( 'widget_text', $instance['text'] );

$shortcode_tags = $temp_shortcode_tags;
unset($temp_shortcode_tags);
```

**Robust solution**
Check `/wp-includes/widgets/class-wp-widget-text.php` `->widget` method

There are the codes to prevent conflicts:

```
/*
 * Suspend legacy plugin-supplied do_shortcode() for 'widget_text' filter for the visual Text widget to prevent
 * shortcodes being processed twice. Now do_shortcode() is added to the 'widget_text_content' filter in core itself
 * and it applies after wpautop() to prevent corrupting HTML output added by the shortcode. When do_shortcode() is
 * added to 'widget_text_content' then do_shortcode() will be manually called when in legacy mode as well.
 */
$widget_text_do_shortcode_priority = has_filter( 'widget_text', 'do_shortcode' );
$should_suspend_legacy_shortcode_support = ( $is_visual_text_widget && false !== $widget_text_do_shortcode_priority );
if ( $should_suspend_legacy_shortcode_support ) {
	remove_filter( 'widget_text', 'do_shortcode', $widget_text_do_shortcode_priority );
}

..........................

/**
 * Filters the content of the Text widget.
 *
 * @since 2.3.0
 * @since 4.4.0 Added the `$this` parameter.
 * @since 4.8.1 The `$this` param may now be a `WP_Widget_Custom_HTML` object in addition to a `WP_Widget_Text` object.
 *
 * @param string                               $text     The widget content.
 * @param array                                $instance Array of settings for the current widget.
 * @param WP_Widget_Text|WP_Widget_Custom_HTML $this     Current Text widget instance.
 */
$text = apply_filters( 'widget_text', $text, $instance, $this );

if ( $is_visual_text_widget ) {

	/**
	 * Filters the content of the Text widget to apply changes expected from the visual (TinyMCE) editor.
	 *
	 * By default a subset of the_content filters are applied, including wpautop and wptexturize.
	 *
	 * @since 4.8.0
	 *
	 * @param string         $text     The widget content.
	 * @param array          $instance Array of settings for the current widget.
	 * @param WP_Widget_Text $this     Current Text widget instance.
	 */
	$text = apply_filters( 'widget_text_content', $text, $instance, $this );
} else {
	// Now in legacy mode, add paragraphs and line breaks when checkbox is checked.
	if ( ! empty( $instance['filter'] ) ) {
		$text = wpautop( $text );
	}

	/*
	 * Manually do shortcodes on the content when the core-added filter is present. It is added by default
	 * in core by adding do_shortcode() to the 'widget_text_content' filter to apply after wpautop().
	 * Since the legacy Text widget runs wpautop() after 'widget_text' filters are applied, the widget in
	 * legacy mode here manually applies do_shortcode() on the content unless the default
	 * core filter for 'widget_text_content' has been removed, or if do_shortcode() has already
	 * been applied via a plugin adding do_shortcode() to 'widget_text' filters.
	 */
	if ( has_filter( 'widget_text_content', 'do_shortcode' ) && ! $widget_text_do_shortcode_priority ) {
		if ( ! empty( $instance['filter'] ) ) {
			$text = shortcode_unautop( $text );
		}
		$text = do_shortcode( $text );
	}
}

// Restore post global.
$post = $original_post;
remove_filter( 'shortcode_atts_gallery', array( $this, '_filter_gallery_shortcode_attrs' ) );

// Undo suspension of legacy plugin-supplied shortcode handling.
if ( $should_suspend_legacy_shortcode_support ) {
	add_filter( 'widget_text', 'do_shortcode', $widget_text_do_shortcode_priority );
}
```

**Comment by braamgenis** [comment]
Hi @nextend Thanks for the very detailed feedback! 👍 So we're going to add a simplified version of the above which just removes any `widget_text` filters which call `do_shortcode` before we run `widget_text` and adds them back afterwards. That should hopefully prevent the above conflicts from occurring without any other side effects.

**Comment by nextend** [comment]
Great, thanks! :)
