### ISSUE TITLE
Hero: iOS autoplay video

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#696]
Currently, hero backgrounds that are locally hosted aren't currently able to play on iOS correctly. A user of ours has provided a fix and Andrew has confirmed it. To fix this issue, you need to remove sow-background-element (I can't find the source of this class) from [the video HTML](https://github.com/siteorigin/so-widgets-bundle/blob/1.11.8/base/inc/widgets/base-slider.class.php#L308) and instead set sow-full-element.  I saw remove because this issue remians if both classes are added. I was going to submit a PR to resolve this issue but I noticed [certain](https://github.com/siteorigin/so-widgets-bundle/blob/1.11.8/js/slider/jquery.slider.js#L28) [functionality ](https://github.com/siteorigin/so-widgets-bundle/blob/1.11.8/js/slider/jquery.slider.js#L172 )was tied to sow-background-element so it's possible that could result in issues if removed. Admitally, Andrew didn't come across any but we didn't do extensive testing by any means.

Also, .sow-full-element, oddly, should be already set due to [its inclusion in the usage of the video_code method](https://github.com/siteorigin/so-widgets-bundle/blob/1.11.8/base/inc/widgets/base-slider.class.php#L267) but it's not being output for whatever reason. That might be related to this issue.

**Comment by braamgenis** [comment]
@AlexGStapleton There seems to be a typo in the base slider class [here](https://github.com/siteorigin/so-widgets-bundle/blob/1.12.1/base/inc/widgets/base-slider.class.php#L233). Could you check the effect of correcting that to `video-sizing` instead of `videos-sizing`?

**Comment by AlexGStapleton** [comment]
I don't see any difference on iOS as a result of correcting that.  Oddly, I can't seem to get the video playing in Android Chrome either. I suspect a recent change may have broken it or they changed something again. 😞  Do SiteOrigin Hero widget videos work for you on your phone?

**Comment by braamgenis** [comment]
There's some very specific CSS to hide slider background videos on mobile [here](https://github.com/siteorigin/so-widgets-bundle/blob/develop/css/slider/slider.less#L201). Not sure what the point of that was. I'll play around and see if I can see any serious negative effects of removing it.

**Comment by AlexGStapleton** [comment]
That's interesting. Surprised this hasn't come up sooner based.

**Comment by braamgenis** [comment]
Ok, so apparently the background videos just don't work well on mobile. Seeing as this has been the case for quite some time already,  changing it is likely to affect a large number of users. If users want to change this behaviour they can use a bit of custom CSS as a workaround. So we're going to leave this as is for now.
