### ISSUE TITLE
SiteOrigin Video Player: Add support for Google Drive hosted videos

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#701]
Add support for Google Drive hosted videos. Thanks.

**Comment by gregpriday** [comment]
Does the core WordPress video widget support drive videos?

**Comment by Misplon** [comment]
Not that I can see.

**Comment by AlexGStapleton** [comment]
We're going to close this for the time being due to a lack of overall requests. We may investigate this in the future if more requests are made.
