### ISSUE TITLE
Editor WPML: Avoid using widget_text on translations

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#703]
We should add a condition to this line to ensure WPML translations are not run against (for example) [this line.](https://github.com/siteorigin/so-widgets-bundle/blame/develop/widgets/editor/editor.php#L94)

Basically, they've added a system to automatically "collect" all widget_text and store it for translation. The way we're handling the text here makes the system "recollect" it. This is resulting in a massive amount of duplicate text. 

[Slack](https://siteorigin.slack.com/files/U0MGMTM4M/FANA13LUX/-.txt)

**Comment by gregpriday** [comment]
@AlexGStapleton Any suggestions on how to fix it? Is there some sort of conditional we could check for in WPML? Do you want to take a try at fixing this?

**Comment by Misplon** [comment]
I've sent the latest version of WPML's core plugin to Alex.

**Comment by AlexGStapleton** [comment]
I've had a look over the WPML code and I can't seem to find where they're actually doing this for `widget_text` outside of one instance where they're adjusting the permalink. I can find references to `widget_title`.

In the WPBakery compatibility file, WPML prevents `icl_sw_filters_widget_title` and `icl_sw_filters_widget_text` from running. This could be seen as a possible solution but `icl_sw_filters_widget_text` doesn't actually exist so I'm not too sure what's going on. I've (privately) posted this file on Slack and it can be seen here.

**Comment by Misplon** [comment]
@AlexGStapleton Is this still a problem?

**Comment by AlexGStapleton** [comment]
I don't _think_ so. This was reported by WPML, but I suspect this issue was fixed as I can't find any recent reports on our end or theirs.

**Comment by Misplon** [comment]
Is there a way we can confirm this?
