### ISSUE TITLE
Gutenberg custom widgets compatibility

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#716]
Hi guys.
This is not really an "issue", but I have a feeling this is a question a lot of people will soon be asking themselves:

For those of us, who have created custom widgets using the so-widgets-bundle form fields... 
We would like to make them available as blocks in the Gutenberg editor. 
Do we need to custom code all this functionality in React? Or will there be an easier way, by using the widget bundle?
Which steps do we need to take to make our custom widgets Gutenberg compatible? 
Thanks!

**Comment by braamgenis** [comment]
Hi @andrejarh

The way we're handling compatibility for now should mean there is little or nothing third party developers such as yourself, would need to do, apart from perhaps testing and reporting any issues you find here. Seeing as Gutenberg is still being developed and changing quite a bit, we have tried to keep the cost of being compatible to a minimum, at least until things seem a bit more stable and/or merged into core and updates to Gutenberg will be less likely to break compatiblity.

We have created a dynamic 'wrapper' block which simply allows users to select the widget they would like to add, and then the form is rendered right there in Gutenberg. Users will then be able to edit and preview the widget without leaving the editor. This is not an ideal solution, but gives us, and third party plugins based on our plugin, some extra time to see how things play out.

You can follow along with development [here](https://github.com/siteorigin/so-widgets-bundle/tree/feature/gutenberg-compat). (Bear in mind this branch is not stable and there are most likely still a few bugs to work out.)

In the longer term, we will be looking at migrating our widgets to be standalone Gutenberg blocks, as it makes sense to conform to the design and development conventions of the platform we're building on.

Hope that clears things up as much as possible.

**Comment by andrejarh** [comment]
Great, thanks for the effort. It seems I will be able to take some vocation this summer after all :)
