### ISSUE TITLE
Price Table: Fix feature icon positioning

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#72]
At the moment, when there is too much text for a feature in the Price Table widget, the icon appears above the text. This should still be inline with the text. Ideally still centered or user specifiable.

![tablebuilder](https://cloud.githubusercontent.com/assets/1126859/12009296/90222678-ac7a-11e5-90ac-527a86d6a91e.png)

**Comment by AlexGStapleton** [comment]
Ran into this issue in [this support thread](https://siteorigin.com/thread/price-table-2/). My fix isn't really ideal and it would be better if the paragraph had a class attached to it instead.
