### ISSUE TITLE
Social Media Buttons: Change title text for email button

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#725]
The Email network option doesn't really make much sense with the default title text - `SITENAME on Envelope`. We should change it to something more logical like, `Email SITENAME`.

![](https://i.imgur.com/NGqPJG7.png)
[Related](https://siteorigin.com/thread/social-media-buttons-3/)

**Comment by Misplon** [comment]
@AlexGStapleton Can you perhaps submit a PR for this? Thanks mate.

**Comment by AlexGStapleton** [comment]
👍
