### ISSUE TITLE
Google Maps: should use geocoding only in backend (and coordinates in frontend)

### ISSUE THREAD

**Issue by vollyimnetz** [siteorigin/so-widgets-bundle#731]
Hi there,
today severeal of my customers informed me that a layer is visible above there google-maps areas.
As i investigate the problem i noticed that your plugin might be causing the problem.

It seems that the plugin use the geocoding api everytime it is loaded. Meaning that the plugin requests the coordinates for the address everytime it renders the map, instead of doing this once in the backend and then use the coordinates in the frontend.
Can you confirm that behaviour?

As the geocoding api has a way lower contingent than the normal javascript api, this leads to the problem of the overlay once the contingent is exceeded.

**Comment by AlexGStapleton** [comment]
Hi Vollyimetz,

Thank you for your report. This is @braamgenis department so I can't really help with this, but out of interest, can you please show me a screenshot of the overlay you're referring too?

**Comment by AlexGStapleton** [comment]
That's odd. I can't seem to replicate that overlay. Would it be possible for you to send me an export for the pictured widgets? To do this please open up the linked page in the editor and click the Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://upload.teknik.io/">teknik.io</a>.

**Comment by vollyimnetz** [comment]
Nevermind - i think I found the problem elsewhere. It seems anyone uses our api-key to generate trafic on the google api - so the quota exceeded.

**Comment by Misplon** [comment]
Awesome, glad to hear you were able to find the problem. All the best.

**Comment by vollyimnetz** [comment]
Sorry, i have to reopen this.
Turns out, that this plugin indeed calls serveral hundert times the GeocodeService and by this exceeds my quota.

![image](https://user-images.githubusercontent.com/6512765/44714292-3e8c8880-aab5-11e8-9e4a-9c2210a98278.png)

**Comment by vollyimnetz** [comment]
So the question remains: Why use the geocode service in the frontend? Even if its not hang in a loop - its totally unnessesary. Do this in a backend and you dont get any problems.

**Comment by AlexGStapleton** [comment]
Can you please try #735 to see if that helps?

**Comment by AlexGStapleton** [comment]
Let me know if you need help with testing the above PR and I'll provide further instructions.

**Comment by braamgenis** [comment]
Hi @vollyimnetz. I was unable to reproduce this behavior. I only ever see a single geocoding request per marker location. Do you think you could provide us with some more steps to reproduce? I think your idea of doing server-side geocoding is good, and I'm going to look into how we might implement it, but would still like to know what's causing this issue. Thanks for your help!

**Comment by vollyimnetz** [comment]
Hi @braamgenis, i had commented the PR.

As it turns out the problem was a "adverse concatenation of circumstances".
- as you might know google changed the behavior it prices its api-calls. 
- Therefore if you do not save billing information for the google-console-project you might get a api-contingent of 1 calls per month
- which leads to the problem that the geocoding-calls in the plugin on my websites fail pretty fast
- the problem has been amplified by the behavior of the plugin wich tries to make new calls untill the end of time

**The problem should be fixed in 2 ways:**
- by the pull request i approved: https://github.com/siteorigin/so-widgets-bundle/pull/735
- by saving valid billing informations on the site-owners google-api-project

BUT, as I mentioned above.
I recommend you refactor the plugin. There is no need to make geocoding-calls in the frontend. The user/page-owner can make them in the backend while he search/set the correct location. The plugin should have saved the geocoords (and the user-input of the location) and use the geocoords instead of making a new geocoding-call every time in the frontend. This would be sheaper for the page-owner (see: https://cloud.google.com/maps-platform/pricing/sheet).

**Comment by braamgenis** [comment]
Ah, ok. Yeah, the changes to the Google API billing are definitely part of the issue.

This code was originally introduced to avoid hitting the per-second rate limit and they still had a free quota without even adding a key. Unfortunately they're using the same error code to indicate that the daily/monthly/etc quota has been reached and, since they removed the free quota, unless you add a billing method it will result in retrying forever.

#735 is the correct client-side solution, however, I think it should allow at least 3 attempts, as suggested in the docs, before deciding the cause is quota limits and stopping.

We'll keep this issue open and look into making the changes to call the geocoding API on the server-side as soon as we can.

Thanks for your help and feedback!
