### ISSUE TITLE
Gutenberg: Changing widget should retain previously set widget settings

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#738]
If you change the widget selected for the SiteOrigin Widget block, the settings aren't be retained. Settings are retained when you do this with Beaver Builder, Elementor, etc, so it would be a good idea to retain them for consistency reasons.

[Slack](https://siteorigin.slack.com/archives/C02SYBBH2/p1534857718000100)

**Comment by braamgenis** [comment]
@AlexGStapleton I might be missing what you mean, but widgets work slightly differently in Gutenberg which has a single wrapper, for all the widgets, in which you select the widget and the widget settings form is completely replaced. Retaining settings for each possible widget in each widget block on the page isn't ideal IMO, but perhaps we can warn users that changes will be lost if they change the selected widget? We did this for Visual Composer.

**Comment by AlexGStapleton** [comment]
I specifically mean the SiteOrigin Widget block. If you change widget, it doesn't retain changes. It may not have been Visual Composer, but one of the other page builders we support has a single widget that allows you to change SiteOrigin to each of the SiteOrigin Widgets and when that happens, you're able to retain any previously altered settings.

In other words, there needs to be a way of retaining or preventing the loose of settings if the user accidentally changes widget.

**Comment by braamgenis** [comment]
>I specifically mean the SiteOrigin Widget block. If you change widget, it doesn't retain changes. It may not have been Visual Composer, but one of the other page builders we support has a single widget that allows you to change SiteOrigin to each of the SiteOrigin Widgets and when that happens, you're able to retain any previously altered settings.

Yep, I understand what you mean. As far as I know, the only other page builder, for which we specifically added support, that uses a similar mechanism, is Visual Composer. If there's another one I may have forgotten about, please let me know which one and/or link to the code for reference.

>In other words, there needs to be a way of retaining or preventing the loose of settings if the user accidentally changes widget.

As I said in the above comment, for Visual Composer we show an alert when users try to change the widget, to warn them that they will lose any unsaved changes. I agree that we should do the same for Gutenberg.
