### ISSUE TITLE
SiteOrigin Layout Slider: Widgets can be lost in the Layout Builder

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#743]
In the SiteOrigin Layout Slider, add a frame and open the builder. Add a widget and then drag that widget into the open space in the modal. If you drop the widget there it's gone. 

<img width="1680" alt="screen_shot_2018-09-07_at_19_20_16" src="https://user-images.githubusercontent.com/789159/45233539-5c3ac880-b2d3-11e8-8ffb-f955a3c84bc5.png">

Once you've exited the Layout Slider you'll see the widgets have been dropped into the Page Builder page but are no longer in the layout slider frame layout builder.

**Comment by gregpriday** [comment]
My guess is this has something to do with the Gutenberg compatibility change where we allowed a widget to be dragged outside its original builder. Just a hunch though.

**Comment by Misplon** [comment]
That’s a good start. Legend, thanks for the feedback.

**Comment by AlexGStapleton** [comment]
I can replicate this. I honestly have no idea why this may be happening. 😕

**Comment by Misplon** [comment]
Thanks for looking, hopefully, @braamgenis can take a look for us soon.
