### ISSUE TITLE
Layout Slider: Consider adding a mobile height setting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#746]
Consider adding a mobile height setting to the Layout Slider widget. We've done this elsewhere and it's really helpful.

**Comment by Misplon** [comment]
@AlexGStapleton What do you think of this idea?

**Comment by AlexGStapleton** [comment]
There's actually a PR for this already #720

**Comment by Misplon** [comment]
Sweet!!!!1
