### ISSUE TITLE
Add ability to specify a SiteOrigin Editor widget as the post excerpt

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#749]
A user recently suggested the following:

> add the ability to have a SiteOrigin Text Editors content automatically be set as a posts excerpt (checkbox? first editor widget?)

This UX suggestion will allow users to easily create excerpts without having to have multiple instances of the same text on the backend. Andrew liked the idea of doing something like this but he didn't like the idea of a dedicated setting. Maybe we could add a setting to automatically pull from the first SiteOrigin Editor widget?

**Comment by braamgenis** [comment]
Should be in the Page Builder repo, so I've relogged there.
