### ISSUE TITLE
Post Loop widget Additional => Meta Query

### ISSUE THREAD

**Issue by scottsawyer** [siteorigin/so-widgets-bundle#751]
I have a post type, "Events" with some meta fields, Start, End, Location.

I want to use the Post Loop widget to a) sort the posts by Start, and only display posts with End > now.

In a normal Wp_Query, I would have something like: 
```
$args = [
  'post_type' => 'event',
  'meta_query' => [
    'relation' => 'AND',
    'end_time' => [
     'key' => 'end',
     'value' => time(),
     'type' => 'NUMERIC',
     'compare' => '>',
    ],
    'start_time' => [
      'key' => 'start',
      'compare' => 'EXISTS',
    ],
  ],
  'orderby' => [ 'start_time' => 'ASC' ],
];
```
How would I go about doing this with Post Loop widget?  I think the biggest challenge would be getting the date in there, no?

**Comment by AlexGStapleton** [comment]
You may be able to use the `Date selection type` field.

![](https://i.imgur.com/DgXlPrF.png)

If that doesn't meet your needs, you'll need to use PHP to do this as there's no direct way to use `time()`. You can alter the post loop query to do by using the [siteorigin_widgets_posts_selector_query](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/post-selector.php#L106) filter.

**Comment by scottsawyer** [comment]
Hey @AlexGStapleton  I appreciate it, but I am pretty sure the fields in the screen shot are for post date, not meta date fields.

I wound up just creating a shortcode instead.  Thanks.
