### ISSUE TITLE
Gutenberg: Assess whether to add wide and full options to the SO Widget block

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#755]
Assess what the impacts might be of adding wide and full options to the widget block.

https://wordpress.org/gutenberg/handbook/block-api/#supports-optional

**Comment by braamgenis** [comment]
@Misplon I might be missing something, but I can't seem to find references to wide and full options anymore. 😕

**Comment by Misplon** [comment]
I can't find any documentation on doing this. @braamgenis can you take a look at how core blocks are doing it? Does this help as a starting point?

https://github.com/WordPress/gutenberg/blob/d98a803a7078291203a46449e59292a6415d7112/packages/block-library/src/cover/index.js#L36

**Comment by braamgenis** [comment]
Ok, found it [here](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#supports-optional). Check the comment under the `align` option:
>Important: It doesn’t work with dynamic blocks yet.

Our blocks are dynamic blocks, so it seems we can't do anything about this for now.

**Comment by Misplon** [comment]
Legend! Sorry, I didn't find that out for us. I'm going to close for now to limit the noise in our issue list. I can re-open or post again when the situation changes.
