### ISSUE TITLE
Bug Contact form: page jumps to the top

### ISSUE THREAD

**Issue by Nautic** [siteorigin/so-widgets-bundle#756]
After a user submits the contact form, their browser takes them to the top of the page. Though it should take them back to where the form is so they can see the success message or any error messages.

Use case: I have a contact form to register for an event. It´s at the bottom of the page. If the user fills in his data and clicks on submit, the page jumps to the top, the form can not longer be seen unless you scroll down again. 
The problem is of course: the user won´t realize when his submission was not successful. He thinks it´s done and most of the users won´t have the idea to scroll down to double check. Thus I loose submissions and produce frustrated customers.

By researching I have seen that many other users have this problem too. 
There was a former github issue on that
Contact Form: Use anchor to return to form after submit #59 
but that was closed.

**So what is the solution here?**

If there is no solution yet please highliy prioritize this issue. 
In my opinion this is a **UX No Go** and a **bug** (not an enhancement as in the old issue!). 

Thank you in advance.

**Comment by Misplon** [comment]
Hi @Nautic 

Please, take a look at this demo: https://demo.siteorigin.com/corp/contact/. The page returns to the form after submit.

Please, send a link to your form so we can take a look. Thanks.

**Comment by Nautic** [comment]
Okay. That is like it should be. 
So what could be the cause that it doesn´t work at my place?
I used the Firefox browser.

**Comment by Misplon** [comment]
In Firefox, your form repositions to the anchor as long as there were no errors. If there was an error, then it isn't repositioning on submit. The same issue doesn't happen for the Corp demo. For the Corp demo I can throw an error and still reposition to the anchor on submit in Firefox.

**Comment by Misplon** [comment]
@AlexGStapleton Can you please, take a look for us. Diagnosis above. Go to: https://cornelia-dietz.de/ in Firefox complete the form incorrectly and submit then complete the form correctly and submit.

**Comment by Nautic** [comment]
I have tested it again in Firefox. 
first try with incorrect data: jumps to the top. 
seconda try with correct data: jumps in between Anmeldung and Anmeldeformular (not to the correct mark as it should be)
third try with correct data: jumps to the black and white-graphic

I have also tested on IE and Chrome with incorrect data: in both cases it works correctly.

**Comment by Misplon** [comment]
With correct data in Firefox I jump to the anchor without issue. If you'd like to assist in the mean time, please try a form submission in Firefox with all other plugins deactivated. Temporarily deactivate all non-SiteOrigin plugins and run a test. If you have caching or optimization plugins of any sort, clear them before deactivation. Thanks.

**Comment by Nautic** [comment]
![screenshot_2018-10-18 plugins trainer moderatoren barcamp wordpress](https://user-images.githubusercontent.com/1636150/47147018-92ee0080-d2cd-11e8-9538-a2d4bcf48430.png)
I would like to assist though I am not sure not to damage something or crash the webpage. 

On the screenshot are all my plugins. If I deactivate all of them except SiteOrigin - is that safe?
Which of them are caching or optimizing plugins and where can I clear them?

**Comment by Misplon** [comment]
I can't see any caching plugins there. There is no danger from doing this test. Select all non-SiteOrigin plugins, deactivate, reload the home page and test the form for us. Thanks.

**Comment by Nautic** [comment]
I tested it as follows:
deleted the text in the URL after https://cornelia-dietz.de
scrolled down to the form
typed text in with correct data
pressed submit button

the result is in the screenshot:
![screenshot_2018-10-18 trainer moderatoren barcamp](https://user-images.githubusercontent.com/1636150/47147937-9f735880-d2cf-11e8-917f-0f295d550530.png)

the same happened with wrong data.

Two thoughts: 
1) Anmeldeformular is not a menu item of its own but Anmeldung and Kontakt. Maybe this is, why it now jumps to Anmeldung
2) I have no idea why it doesn´t jump to the top anymore now

**Comment by Misplon** [comment]
Two more tests to run would be to:

1. Run this same test with no other plugins activated but run the test logged out.
2. Edit the page, copy the form widget, create a new page, paste the form widget. Test that page, are the issues the same?

**Comment by Misplon** [comment]
And then finally, the ultimate test to run would be with all non-SiteOrigin plugins deactivated AND a default theme like Twenty Sixteen. That would rule out any conflicts from the theme. Also, safe test.

**Comment by Nautic** [comment]
No. 2: I have a problem creating a new page. I inserted the copied widget and clicked on preview but the site could not be found.

**Comment by Misplon** [comment]
Try saving the page after inserting the widget.

**Comment by Nautic** [comment]
No. 2: in both cases with correct and incorrect data the page jumps to the beginning of the form (as it should be)

Though in this case I don´t have text or anything above so that might give a wrong impression.
![screenshot_2018-10-18 test trainer moderatoren barcamp](https://user-images.githubusercontent.com/1636150/47149190-1f4ef200-d2d3-11e8-9095-6d91294a6d28.png)

**Comment by Misplon** [comment]
On the demo page, insert a Text widget above and a lot of dummy text to test. Thanks.
https://www.lipsum.com/feed/html

**Comment by Nautic** [comment]
No 3 with standard theme Twenty six
the same results with correct or incorrect data
![screenshot_2018-10-18 trainer moderatoren barcamp 5](https://user-images.githubusercontent.com/1636150/47149493-00049480-d2d4-11e8-8bcb-d6f79afc72b0.png)


![screenshot_2018-10-18 trainer moderatoren barcamp 6](https://user-images.githubusercontent.com/1636150/47149444-df3c3f00-d2d3-11e8-8c83-62ac34f406a9.png)

**Comment by Nautic** [comment]
On the demo page, I inserter text and run the text again with correct data. 
I would say it does not jump to the correct point but higher. It should show the German text only.

![screenshot_2018-10-18 test trainer moderatoren barcamp 1](https://user-images.githubusercontent.com/1636150/47149740-bff1e180-d2d4-11e8-8c0c-57f84133dd2b.png)

**Comment by Misplon** [comment]
The page can only jump so far down. If there is no space below the form the page can't go any further down. So what you can try doing is copying the text widget and adding it below the form and then try again.

**Comment by Nautic** [comment]
yes, that´s it. It worked fine with text added below.
![screenshot_2018-10-18 test trainer moderatoren barcamp 2](https://user-images.githubusercontent.com/1636150/47150064-b1f09080-d2d5-11e8-8168-73cd99999abd.png)

**Comment by AlexGStapleton** [comment]
I've tried the contact form with FireFox and I'm scrolled to the top of the form. This, to me, suggests that something is loading after the page jump starts. Out of all of the plugins you listed, the most likely cause for that would be the a3 Lazy Load but based you mentioned, disabling it didn't produce any results.

Can you please link me to the demo page you're working on?

**Comment by Nautic** [comment]
you mean this one? https://cornelia-dietz.de/?page_id=767&preview=true#contact-form-7676

**Comment by AlexGStapleton** [comment]
Can you please publish the linked page? Guests aren't able to view unpublished or private pages.

**Comment by Nautic** [comment]
ok
should work now with this link https://cornelia-dietz.de/test

**Comment by Nautic** [comment]
WeTransfer requires an email-address. Where shall I send it to?

**Comment by AlexGStapleton** [comment]
Please leave that field empty. It will generate you a link after upload, please reply with that link.

**Comment by Nautic** [comment]
ok, that worked.
https://we.tl/t-RQgHpW30Zb

**Comment by Nautic** [comment]
I´m sorry, I need to go back to work now. Do you have all information from me that you need? 
If you need something else I can assist again in the evening (in approx. 5 hours). 
Thank you very much for your help so far. I hope, we find a solution soon :-)

**Comment by AlexGStapleton** [comment]
Thanks. I've identified what's going wrong. If you submit a contact form incorrectly and then submit the form correctly, the browser won't scroll due to the fix for #644. I'm going to create a dedicated issue for this shortly.

**Comment by Nautic** [comment]
Thank you for your dedication! :-)
I understand that this is only a problem in firefox and that it occurs due to the order of steps.

Thus I tried it once more (in firefox), filling in the correct data at the first time. The page still does not jump to the correct point. Did I misunderstand something?

**Comment by AlexGStapleton** [comment]
That's odd. I'm not too sure why you were still able to experience this issue on the first submission - I couldn't cause this issue to happen on the first submission no matter what I tried. 😕  

At this stage, I recommend trying the next* SiteOrigin Widgets Bundle update as it will contain a possible fix to resolve this issue in all situations. If it doesn't fix this issue, we'll pick this back up.

* At this stage, it looks likely that it will be in the next update.

**Comment by AlexGStapleton** [comment]
This issue has been fixed in the 1.13.1 update. Let me know if you're still having issues with this.
