### ISSUE TITLE
[Firefox] Contact: If form is submitted once incorrectly before a valid submission, browser won't scroll to form on reload

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#757]
The fix for #644 has an issue in FireFox that prevents the scroll from occurring. To replicate this issue...

- Add a contact form to your page and open it.
- Fill it out incorrectly (invalid email, leave required empty, etc).
- Fill out the form correctly and submit it.

This issue is related to #756.

**Comment by Misplon** [comment]
Note: If testing with SiteOrigin Corp, this issue doesn't occur in Firefox because of smooth scrolling from external anchor functionality: https://github.com/siteorigin/siteorigin-corp/blob/develop/js/jquery.theme.js#L153
