### ISSUE TITLE
FitText: When more than one instance is in place, resize isn't working correctly

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#758]
When `runFitText` is called asecond time, it removes the `resize` listener for the first heading.

Test page: https://demo.siteorigin.com/corp/fittext/

When testing, Braam is seeing the second heading resize correctly but I am not. When I switch from Chrome to Firefox, then I'm seeing the second heading resize. @AlexGStapleton can you check to see if you get the same results?

**Comment by AlexGStapleton** [comment]
I'm getting the same results. Second heading is resizing while the first one isn't.
