### ISSUE TITLE
Conflict with [gallery] by Jetpack

### ISSUE THREAD

**Issue by anendel** [siteorigin/so-widgets-bundle#76]
When I want to integrate a gallery using the Jetpack plugin, an error warning is shown that the shortcode [gallery] is already in use (by theme or plugin).

**Comment by Misplon** [comment]
Hi @anendel 

Sorry we weren't able to reply at the time. I'm closing because the gallery shortcode looks to be functioning normally in the SiteOrigin Editor widget. 

Thanks for the input, much appreciated. Cheers.
