### ISSUE TITLE
Wp Anything Slider prevents SiteOrigin Slider from working

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#762]
To reproduce, add a SiteOrigin Slider and a [Wp Anything Slider ](https://wordpress.org/plugins/wp-anything-slider/)shortcode to a page, the SiteOrigin Slider won't function beyond the first slide.

Both make use of jQuery Cycle which is most likely where the issue lies.

`<script type="text/javascript">jQuery(function() {jQuery('#WP-ANYTHING-SETTING1').cycle({fx: 'scrollLeft',speed: 700,timeout: 5000});});</script>`

**Comment by Misplon** [comment]
I've reached out to the author and asked if they could ensure that Anything Slider assets (Cycle and CSS) aren't outputted on every page. Right now assets are outputted to every page, regardless of whether an Anything Slider shortcode is in use. It won't fix the core issue but would allow the two plugins to be used on the same site without disturbing each other across pages.

**Comment by gregpriday** [comment]
Difficult to fix this and we haven't heard back from the plugin author.
