### ISSUE TITLE
Timeline next s-widget-bundle release

### ISSUE THREAD

**Issue by miili** [siteorigin/so-widgets-bundle#77]
Hi guys,

thanks for developing this extensive bundle of great widgets!

There's a merged feature I am awaiting to use on our website, but it's not released yet.

Do you have a timeline for the next release?

Best, M

**Comment by gregpriday** [comment]
Hi @miili - glad to hear you're enjoying the bundle :)

We're due to release an update very soon. What's the feature you're looking for?

**Comment by miili** [comment]
Great!
It's #57 I am after.
