### ISSUE TITLE
WPBakery [Backend Editor]: Adding Text Element to page will reset the SiteOrigin Widget to default and data on frontend

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#772]
Adding a Text Element to page will reset the SiteOrigin Widget to default when it's set to be Contact - this may affect other widgets also.

Steps to recreate:
- Create new page and enable backend editor 
- Add a SiteOrigin Widget and set it to use the cotnact form
- Save and view page to confirm contact appears as expected
- Add Text element (don't adjust the default text)
- Save and view the page

[Reference video](WPBakery)

<img width="766" alt="2018-11-06-22-01-35" src="https://user-images.githubusercontent.com/17275120/48150376-35683500-e30a-11e8-98a8-6d920d7f066f.png">
(user supplied)

**Comment by AlexGStapleton** [comment]
This appears to be affecting a few other widgets - [thread](https://wordpress.org/support/topic/problem-with-update-page-and-plugin-crash/#post-10857401).

**Comment by Misplon** [comment]
In checking for an alternative/workaround for users right now, I've ruled out:

Text Block
WP Text
Raw HTML
SiteOrigin Editor

All of the above elements cause the same issue.

**Comment by Misplon** [comment]
Quick update on the issue for reference:
If you add the SO Wiget in the Front End Editor, the page will save normally. If you then save the page in the Back End Editor/regular WP interface, the SO widget fails, even if no edit was made to the page.

**Comment by Misplon** [comment]
@AlexGStapleton For ease of reading, please, could you summarise here the other widgets you mention being impacted? Thanks.

**Comment by AlexGStapleton** [comment]
When I initially logged this, it was every SiteOrigin widget I tried. Which, from memory, were all widgets with a TinyMCE field.

**Comment by Misplon** [comment]
Going on my impacted list: 

Text Block
WP Text
Raw HTML
SiteOrigin Editor

that would certainly make sense.

**Comment by Misplon** [comment]
@AlexGStapleton Can you perhaps take a look at support tickets and locate a combination of versions (VC and WB) where this wasn't happening?

**Comment by AlexGStapleton** [comment]
The earliest reference to this issue was using [5.4.7 (08.03.2018)](https://kb.wpbakery.com/docs/preface/release-notes/).
