### ISSUE TITLE
Google Maps widget: Info box all the same

### ISSUE THREAD

**Issue by dfragac** [siteorigin/so-widgets-bundle#773]
I have an issue on Google Maps widget... all info boxes from every pin point are the same (when, logically, every one is different in configuration).

You can see it in https://ronautica.com/

Regards

**Comment by Misplon** [comment]
Hi @dfragac Thanks for posting, resolved here: https://github.com/siteorigin/so-widgets-bundle/issues/769. Sorry for the hassle. Will push a release for the Widgets Bundle in the next few days.
