### ISSUE TITLE
WB Post Meta Boxes functionality doesn't save data in Gutenberg

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#778]
The [Widgets Bundle Meta Boxes](https://siteorigin.com/docs/widgets-bundle/advanced-concepts/post-meta-box-forms/) functionality isn't saving data while using the Gutenberg editor. Any values input aren't saved and instead, the post meta is saved as NULL.

This issue doesn't occur with the Classic Editor.

**Comment by gregpriday** [comment]
@AlexGStapleton, which of our own widgets use a WB Meta Box? Sorry, been a long time, can't quite remember.

**Comment by AlexGStapleton** [comment]
None of our widgets are using it. I'm not aware of any third party widgets facing this issue - the only reason I know about it as I tried it during the RC WP 5.0 testing.

**Comment by gregpriday** [comment]
Awesome, we can drop it back to P3 then.

**Comment by gregpriday** [comment]
@braamgenis Can you check if this is a quick fix. I seem to remember we just need to add some flag to make metaboxes Gutenberg compatible. Do you remember what that flag is?

**Comment by braamgenis** [comment]
@gregpriday The flag doesn't make metaboxes compatible, they just signal to the block editor whether or not they are compatible. Then it skips the ones flagged as not compatible. So I've just set the flags to prevent displaying these in the block editor.

**Comment by gregpriday** [comment]
Good enough for me.
