### ISSUE TITLE
CSS cache not cleared for extending plugins

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#78]
Any plugins that extend Widgets Bundle don't have their CSS cache cleared when they update. There's currently a mechanism in the Widgets Bundle plugin that checks when the core plugin updates and clears cache, but this doesn't extend to other plugins.

This was reported by @adiraomj: https://siteorigin.com/thread/automatically-compiling-less-files-after-plugin-update/

**Comment by braamgenis** [comment]
Resolved by GH-98
