### ISSUE TITLE
Plugin breaks wp-cli

### ISSUE THREAD

**Issue by atomicus** [siteorigin/so-widgets-bundle#781]
Hi guys,

Enabling this plugin breaks wp-cli by adding unnecessary HTML output.

The example:
Running the following code on site with plugin enabled:
`wp option get siteurl`
returns:

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body><p>http://test
</p></body></html>
```

While running:
`wp option get siteurl --skip-plugins=so-widgets-bundle`
returns:
`http://test`

As it should.

Clearly, this proves a plugin breaks a lot in code, affects un-related parts of it and is generally not separated well.

Such a serious issue makes this plugin totally unusable in any quality development & automated deployments.

**Comment by AlexGStapleton** [comment]
Unfortunately, I can't seem to replicate this. I tried this using WordPress 4.9.8 and 5.0 Beta 5 with the following plugins active:

- Page Builder by SiteOrigin
- SIteOrigin Widgets Bundle
- SiteOrigin CSS
- WooCommerce
- SiteOrigin Premium

I was using Twenty Seventeen.
Does this issue occur when all non-SiteOrigin Plugins are activated and a default theme?

**Comment by atomicus** [comment]
My fault.
Excuse me for this issue, you can close it, it's unrelated to this plugin.

**Comment by AlexGStapleton** [comment]
No worries.
