### ISSUE TITLE
TinyMCE Field: Can't have more than 10 repeater items with TinyMCE fields

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#79]
For any repeater items that you add beyond the first 10, the TinyMCE field isn't properly initialised. This was first reported here: https://wordpress.org/support/topic/tinymce-repeater

I confirmed this using markers in the Google Maps widget.

![screen shot 2016-01-18 at 12 04 56 pm](https://cloud.githubusercontent.com/assets/1126859/12388467/b66d3bd4-bddb-11e5-9d4c-6b3d64732931.png)

**Comment by braamgenis** [comment]
Resolved by cf739f98ca19c8f32bdced8c251f93837a38db81
