### ISSUE TITLE
PHP 7.3: Warning: preg_replace_callback(): Compilation failed: invalid range in character class at offset

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#791]
`Warning: preg_replace_callback(): Compilation failed: invalid range in character class at offset 22 in /wp-content/plugins/so-widgets-bundle/base/siteorigin-widget.class.php on line 853`

**Comment by AlexGStapleton** [comment]
I've updated the title to reflect this issue only affects PHP 7.3. Here's a [link to 853](https://github.com/siteorigin/so-widgets-bundle/blob/1.13.4/base/siteorigin-widget.class.php#L853).

**Comment by Misplon** [comment]
Super, thanks.
