### ISSUE TITLE
Elementor Pro: WB breaks Global Widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#793]
When the Widgets Bundle is activated, users are unable to use Elementor when a Global Widget has been set. It doesn't matter if that global widget is one of ours or not. To replicate this issue:

- Open Elementor on a page
- Set a Global Widget
- Save and close the page.
- Re-open Element and you'll be presented with the following error message:

![](https://vgy.me/UyKBqH.png)

There's a PHP error log for this:

```
[07-Dec-2018 00:09:24 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_component() on null in /home/***/***/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php:180
Stack trace:
#0 /home/***/***/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php(68): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->set_preview_settings(Array)
#1 /home/***/***/wp-content/plugins/elementor/includes/base/element-base.php(739): ElementorPro\Modules\GlobalWidget\Widgets\Global_Widget->get_raw_data(true)
#2 /home/***/***/wp-content/plugins/elementor/includes/base/element-base.php(739): Elementor\Element_Base->get_raw_data(true)
#3 /home/***/***/wp-content/plugins/elementor/includes/base/element-base.php(739): Elementor\Element_Base->get_raw_data(true)
#4 /home/***/***/wp-content/plugins/elementor/includes/base/element-base.php(739): in /home/***/***/wp-content/plugins/elementor-pro/modules/global-widget/widgets/global-widget.php on line 180
```

**Comment by francislagazon** [comment]
Im having same issue. @AlexGStapleton @braamgenis did you resolve the issue?

**Comment by Misplon** [comment]
Hi @francislagazon. Thanks for reaching out. We've, unfortunately, ceased our support for Elementor. The challenges involved and the small number of users making use of the Widgets Bundle within Elementor meant it wasn't viable for us to continue. Sorry, I don't have better news.
