### ISSUE TITLE
[Bug] Version >= 1.13.2: Brakes edit / create new Post

### ISSUE THREAD

**Issue by mamaretti** [siteorigin/so-widgets-bundle#795]
when editing or creating new post (wp-admin/post-new.php) its not possible to use pagebuilder
(testet with 1.13.3 and 1.13.4)

![version-1 13 3](https://user-images.githubusercontent.com/3448514/50282749-18b83480-0454-11e9-8784-84ef93cf1808.png)

thx

**Comment by AlexGStapleton** [comment]
Unfortunately, I'm unable to replicate this issue. Have you done a plugin and theme conflict test?

**Comment by mamaretti** [comment]
sorry i forgot to write my WP version. its 4.7.12
(not sure if happens with 4.8 .... too   )

**Comment by mamaretti** [comment]
tested it with a clean install of 4.7.12, and standard-theme, an only pagebuilder plugin

**Comment by mamaretti** [comment]
Hi Alex, its not my decision.
but why ist it old? its still on trac.
would be great if there is a way to use 1.13.4  because of some bugfixes i need.
but i dont know what causes the bug between 1.3.2 and 1.3.3

**Comment by AlexGStapleton** [comment]
Thanks. That line was removed as it's no longer required as of 4.8 and it was causing issues in newer versions of WordPress. We're only able to support [officially supported versions of WordPress](https://codex.wordpress.org/Supported_Versions) and can only provide limited support for legacy versions of WordPress.

You can add the highlighted PHP back to your website and it'll avoid this issue. If you're using a child theme, please add the highlighted PHP to your child funtions.php. If you aren't using a child theme, you can add the code using [Code Snippets](https://wordpress.org/plugins/code-snippets/).

**Comment by Misplon** [comment]
Hi @mamaretti. Thanks for reaching out. Sorry, we weren't able to assist with a solution from within the Widgets Bundle but I'm glad to see there is a quick Code Snippets fix. If any questions arise about this in the future, please let us know here or on the forum at https://siteorigin.com/thread. We'll help out wherever possible.
