### ISSUE TITLE
Assigning widgets to tab groups

### ISSUE THREAD

**Issue by stueynet** [siteorigin/so-widgets-bundle#8]
No rush on this. I know you guys are busy working on the new docs. If you have time let me know. I have successfully registered the tab for my custom widgets bundle as follows:

```
function so_custom_widgets_tab($tabs){
	$tabs['custom_widgets'] = array(
		'title' => __('Custom Widgets', 'siteorigin-panels'),
		'filter' => array(
			'groups' => array('so-custom-widgets')
		)
	);

	return $tabs;
}

add_filter( 'siteorigin_panels_widget_dialog_tabs', 'so_custom_widgets_tab');
```

However, I have not been able to figure out how to get each of the sub widgets in my plugin to reside in this new tab. I am using the dev examples as the starting point where it runs through my widgets folder, but it doesn't seem you guys implemented that in the examples.

If you can guide me I would appreciate it!

**Comment by braamgenis** [comment]
Hi Stuart

Great to see you're building custom widgets using the Widgets Bundle. :) There are a couple of ways you could do this and you can read more about them in the Page Builder docs [here](https://siteorigin.com/docs/page-builder/widget-groups/).

We'd like to keep Github Issues to actual issues with the code, such as bugs and feature requests. So, in future, it would be very much appreciated if you could post any support questions over at the [SiteOrigin forum](https://siteorigin.com/new-thread/). Thanks!
