### ISSUE TITLE
Repeaters: When user visual editor setting deactivated repeaters are broken

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#801]
Widgets with repeaters are unusable if the user setting: Disable the visual editor when writing is enabled. To replicate:

1. Go to Users, edit your username and deactivate the visual editor when writing.
2. Go to a page, insert a Contact Form widget for example and view the console.

`tinymce-field.js:65 Uncaught TypeError: Cannot read property 'EditorManager' of undefined`

@AlexGStapleton is unable to replicate at the moment. I'm using WP 5.0.2, the only plugins I have activated are Page Builder and the Widgets Bundle. The issue is only visible in a classic page because once you have the Disable visual editor setting enabled, you can't insert blocks into a block editor page.

**Comment by AlexGStapleton** [comment]
I was able to replicate this issue by disabling Yoast. I suspect they may have added something that avoids this issue.
