### ISSUE TITLE
Google Maps OVER_QUERY_LIMIT

### ISSUE THREAD

**Issue by SmashBrando** [siteorigin/so-widgets-bundle#802]
I ran into an odd issue that may be related to #731. 

I have this page https://pinnacleskin.com/our-locations/ loading 23 map locations (more to come soon). I noticed not all are showing and the console is showing OVER_QUERY_LIMIT (8 times). 

My API limits all look good - https://cloudup.com/c7_XI-DzInL

From what I can tell I shouldn't be hitting any limits that I know of. I have billing setup and active on the account as well.

Edit: Reducing the BATCH_SIZE to 1 or 2 seems to eliminate the error but due to the request time, they markers slowly appear over 8 seconds or so.

**Comment by Misplon** [comment]
Hi @SmashBrando 

Great to hear from you :) Sorry we didn't reply at the time. We've resolved this issue, the fix will be included in the next release.

If anything arises in the future, please let us know. Cheers for now.
