### ISSUE TITLE
custom icons issue in icon.class.php in get_value_parts()

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#808]
Hi I just noticed that custom icon packs are causing PHP warnings. They are trying to include a non-existing file due to an error in get_value_parts function of icon.class.php class.

The file which is trying to get included is /plugins/so-widget-bundle/icons/[custom icon pack]/filter.php

**Example of the warning:**
![screenshot 2019-01-08 at 11 12 25](https://user-images.githubusercontent.com/10053621/50825701-f40bfa00-1339-11e9-879e-c9924441bc72.png)

**How to reproduce the issue:**
1. Load a custom icon pack inside a theme/plugin using the siteorigin_widgets_icon_families filter as written in this tutorial: https://siteorigin.com/docs/widgets-bundle/form-building/icons-and-fonts/
2. Add define('WP_DEBUG', true); in the wp-config.php
3. Install Debug Bar plugin, to see all the warnings, notices on the fly.

**What causes the issue?**
I think this line of code (icon.class.php line 113):
```
if ( ! empty( $value_family ) ) {
	include_once plugin_dir_path(SOW_BUNDLE_BASE_FILE) . 'icons/' . $value_family . '/filter.php';
}
```

**Comment by AlexGStapleton** [comment]
This appears to be caused by [this line](https://github.com/siteorigin/so-widgets-bundle/blob/1.14.0/icons/icons.php#L16). When I changed that line, this error no longer occured for me. Not too sure why it would be triggering something now but I'm not very familiar with the overall changes made.

Does changing the highlighted line to the following resolve this issue for you?

```
		if ( file_exists( plugin_dir_path(__FILE__) . $font . '/filter.php' ) ) {
			include_once plugin_dir_path(__FILE__) . $font . '/filter.php';
		}
```

**Comment by andrejarh** [comment]
No,
but it does resolve if i change the line 113 in icon.class.php to
```
		if ( ! empty( $value_family ) ) {
			if ( file_exists( plugin_dir_path(SOW_BUNDLE_BASE_FILE) . 'icons/' . $value_family . '/filter.php' ) ) {
				include_once plugin_dir_path(SOW_BUNDLE_BASE_FILE) . 'icons/' . $value_family . '/filter.php';
			}
		}
```

**Comment by AlexGStapleton** [comment]
Odd stuff. Would you be willing to [submit a PR](https://help.github.com/articles/about-pull-requests/) with that? If not, I can submit one.

**Comment by andrejarh** [comment]
I just submitted PR, which solves the issue.  @AlexGStapleton please check.

On the long run, it might even make sense to add an ability to reference the file containing the icon array for custom icons. This would allow third party icons be included only if the icons are present on the page (like currently bundled icons work) and not hardcoding the path to 
/so-widget-bundle/icons/[icon pack]/filter.php 

...If this makes any sense.
