### ISSUE TITLE
PHP 7.3 Compat: Continue Targeting Switch issues Warning

### ISSUE THREAD

**Issue by trepmal** [siteorigin/so-widgets-bundle#812]
Hi,

The Less lib included has some PHP 7.3 compat issues:

>  _continue_ statements targeting _switch_ control flow structures will now generate a warning. In PHP such _continue_ statements are equivalent to _break_, while they behave as _continue 2_ in other languages. 

http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

Example:
https://github.com/siteorigin/so-widgets-bundle/blob/7bdbcf76a6053450040c24382b15571f83d70e04/base/inc/lib/Less/Exception/Chunk.php#L70

The original repo has been [abandoned](https://github.com/oyejorge/less.php/issues/371), but this fork includes the fix:

https://github.com/Asenar/less.php/commit/b56f7bb82b708573a90f2b8a6c4b1fa5d36f838e#diff-cd3ec84e97521abdea4b5c455448c3b9

**Comment by Misplon** [comment]
Hi @trepmal. Thanks for post this issue. The fix is linked above and will be included in the next Widgets Bundle release. All the best :)

**Comment by trepmal** [comment]
Thanks!
