### ISSUE TITLE
Font Awesome Font Weight CSS Precedence

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#813]
A user reported FA mostly not working. [Site concerned](https://cursenglezamedicala.ro/). The theme in question is setting:

```
.entry-content span {
font-weight: 400;
} 
```
To resolve, the user added to Custom CSS:

```
.sow-fa, .sow-fas {
    font-weight: 900 !important;
}
```
@braamgenis Are you happy with adding `!important` to avoid this?

**Comment by braamgenis** [comment]
No, not if it can be avoided by rather adding more specificity to our selector. I prefer to avoid using `!important` unless there really is no other option. Their theme is possibly breaking Google fonts that don't have a `font-weight: 400;` too.

**Comment by Misplon** [comment]
For sure, happy to resolve as you see fit. The gist of the problem is their `.entry-content span` beats our rule targetting the `span` tag.

**Comment by andrejarh** [comment]
I think this is a theme's fault, not SO Page Builder. However in the case of the site mentioned, just changing the style from:
```
.sow-fa,
.sow-fas {
    font-family: 'sow-fontawesome-free';
    font-weight: 900;
}
```
to this:
```
.sow-icon-fontawesome.sow-fa, .sow-icon-fontawesome.sow-fas {
    font-family: 'sow-fontawesome-free';
    font-weight: 900;
}
```
should do the trick.

**Comment by gregpriday** [comment]
@Misplon Are all Font Awesome fonts weight `900`? Will they always break if the weight is set to anything other than `900`? In that case, I'd personally be fine with using `!important`. That's a fair use case for it.

**Comment by Misplon** [comment]
From what I can see in the FA download, the following are always `900`:

```.sow-fa, .sow-fas {
	font-family: 'sow-fontawesome-free';
	font-weight: 900;
}```

**Comment by gregpriday** [comment]
Looking at the font filenames, they even have the weight in them. So yeah, we can go with `!important` on `font-weight` and `font-style`.
