### ISSUE TITLE
Beaver Builder: SiteOrigin widgets aren't working

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#825]
SiteOrigin widgets don't appear to be functioning in Beaver Builder. The only PHP error I can see is:

`Notice: Undefined index: style in /Users/andrew/Dropbox/Sites/siteorigin/wp-content/plugins/beaver-builder-lite-version/classes/class-fl-builder.php on line 2919`

For example, try testing the button widget, it doesn't appear to output after saving.

Font Awesome icons aren't showing in the admin:

<img width="397" alt="icons" src="https://user-images.githubusercontent.com/789159/52467730-31f57b80-2b8f-11e9-9a2d-7450f14393bb.png">

Originally reported on our forum [here](https://siteorigin.com/thread/widgets-not-working-5/).

I've tested with so-widgets-bundle.1.15.0-rc.3 and the issue persists.

**Comment by Misplon** [comment]
@AlexGStapleton Does anything jump out at you as the cause?

**Comment by AlexGStapleton** [comment]
Unsure what the error is in relation too but this is happening due to the font-family not being updated. I've submitted #826 to fix this.

**Comment by braamgenis** [comment]
#826 fixes the FontAwesome icons not showing, but doesn't fix the issue with widgets not updating or saving correctly.

**Comment by Misplon** [comment]
Thanks for checking @braamgenis! If you could attend, that would be awesome.

**Comment by AlexGStapleton** [comment]
Oh. Awkwardly, I didn't realize it had issues saving as I never actually tried to save. If you could take a look that would be much appreciated.

**Comment by gregpriday** [comment]
Issue fixed in https://github.com/siteorigin/so-widgets-bundle/commit/5a68c691a272f4116dabdd8c1e1b559573731782 - did some testing and everything seems to be working nicely now. We can reopen this if the issue still comes up.

This should be going out in the next update - `1.15.1`.
