### ISSUE TITLE
Problem with Insert Pages TinyMCE plugin

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-widgets-bundle#84]
Ideally we'd find generic way to support third party TinyMCE plugins so that we don't have to keep adding explicit support for each new plugin.

Related support thread: https://wordpress.org/support/topic/conflict-with-other-plugins-button-of-other-plugins-in-tinymce-disappear?replies=1

**Comment by Misplon** [comment]
Hasn't come up in a while so closing for the time being.
