### ISSUE TITLE
Maps: Open widget settings API request button in new tab

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#842]
<img width="970" alt="maps-button" src="https://user-images.githubusercontent.com/789159/53633355-e11df380-3c1f-11e9-880f-0fc9e4efb072.png">

Change the Go to Google Maps Widget Settings button to open in a new tab.

**Comment by braamgenis** [comment]
Also part of the changes that haven't been released yet: #839

Two points here:
* When the link is to the same domain, it should stay in the same tab.
* The widget form page will have to be reloaded anyway to get the API key after it's been set in global settings.

**Comment by Misplon** [comment]
Makes sense. Thanks mate.
