### ISSUE TITLE
SiteOrigin Widget Block - Icon: Notice: Undefined index

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#848]
Using PHP 7.2.1 and WP_DEBUG enabled, the SiteOrigin Widget Block: Icon widget is showing the following notices:

`Notice: Undefined index: color in /wp-content/plugins/so-widgets-bundle/widgets/icon/icon.php on line 70`

`Notice: Undefined index: alignment in /wp-content/plugins/so-widgets-bundle/widgets/icon/icon.php on line 71`

`Notice: Undefined index: size in /wp-content/plugins/so-widgets-bundle/widgets/icon/icon.php on line 72`

**Comment by braamgenis** [comment]
Fixed in 298224bb6925463c3c4179f4b62677676d630861
