### ISSUE TITLE
Content not shown

### ISSUE THREAD

**Issue by WimSchol** [siteorigin/so-widgets-bundle#851]
Hello 
After the last update the content of pages is not shown in the PageBuilder editor (i use TinyMCE) while try to edit.
Switching to block editor doesnt have effect, content is still not shown in the editor. 

Thx Wim

**Comment by Misplon** [comment]
Hi Wim

Sorry to hear about the hassle. Have you made progress since posting?

**Comment by Misplon** [comment]
Hi Wim

I'm going to close for the moment. If anything comes up in the future, please feel free to open a support topic on our forum https://siteorigin.com/thread. Alternatively, if you have a bug that can be confirmed, you can log it here.

All the best with your site :)

**Comment by WimSchol** [comment]
Thx Andrew.

Op 5 apr. 2019 09:29 schreef Andrew Misplon <notifications@github.com>:

Hi Wim

I'm going to close for the moment. If anything comes up in the future, please feel free to open a support topic on our forum https://siteorigin.com/thread. Alternatively, if you have a bug that can be confirmed, you can log it here.

All the best with your site :)
