### ISSUE TITLE
New widgets admin notification: all widgets shown as new

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#853]
[Raised on Twitter](https://twitter.com/sadosit/status/1113171817865318400) by https://twitter.com/sadosit. All widgets are showing as new on update.

![D3LHidjWkAAbRJq](https://user-images.githubusercontent.com/789159/55468425-a08d0d80-5603-11e9-8b0b-94ed7dc15e19.jpg)

**Comment by gregpriday** [comment]
This comes up from time to time. It has something to do with user data caching. Whatever the cause, I suggest we just remove that notification entirely.

**Comment by Misplon** [comment]
That'll do. 

@braamgenis Can you hit this one for the next WB update?

Thanks, guys.
