### ISSUE TITLE
Multi-image Upload Field

### ISSUE THREAD

**Issue by ingageco** [siteorigin/so-widgets-bundle#877]
Hey Team - I'm developing a few widgets and I'd love the ability to have a multi-upload field, similar to the "Add Media" button. The application for these fields are various types of galleries where it is tedious to add images in the repeatable field. Is there a way to do this already by chance?

**Comment by AlexGStapleton** [comment]
Unfortunately, this isn't possible with any of the current form fields. This would be a nice improvement though so I've labeled this as an enhancement.
