### ISSUE TITLE
slider field default value ignored in Gutenberg (SO Widget)

### ISSUE THREAD

**Issue by andrejarh** [siteorigin/so-widgets-bundle#879]
In Gutenberg, when adding a custom widget with a slider field in the form, slider default value is not recognized, the value is set to 0.
Example widget form:

```
			    'logo_height' => array(
			        'type' => 'slider',
			        'label' => 'Row height (px)',
			        'default' => 180,
			        'min' => 60,
			        'max' => 360,
			        'integer' => true
			    ),

				'logo_img_size' => array(
			        'type' => 'slider',
			        'label' => 'Logo size (%)',
			        'default' => 80,
			        'min' => 40,
			        'max' => 100,
			        'integer' => true,
			    ),

				'logo_img_hover_size' => array(
			        'type' => 'slider',
			        'label' => 'Logo size on hover (%)',
			        'default' => 90,
			        'min' => 40,
			        'max' => 100,
			        'integer' => true,
			    ), 

```

The actual display in the form:

![image](https://user-images.githubusercontent.com/10053621/59674641-ffeec880-91c3-11e9-9872-5fd1e37e57c7.png)

Notice also that min is set to 40 (or 60), so the 0 should not be allowed at all, but it actually saves the 0 value, when the form is saved.

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

Unfortunately, I can't seem to replicate this. Can you please provide me with a copy of your entire widget's code? This will allow me to run some tests against that widget directly and that should (hopefully) help allow me to replicate this issue.

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

I'm going to close this as I'm having trouble replicating it. Please re-open this if you would like to pick this back up.

**Comment by andrejarh** [comment]
Hi Alex,
Thank you for looking into this.
I just retested the same widget with the latest PB from wp.org and it worked without an issue. Not sure what caused it in the first place, now the issue seems to be resolved.

**Comment by AlexGStapleton** [comment]
Hi @andrejarh,

It's great to hear it's working now. Let me know if this issue occurs again and we'll pick this back up.
