### ISSUE TITLE
Simple Masonry bug in 1.5.5

### ISSUE THREAD

**Issue by jordif** [siteorigin/so-widgets-bundle#88]
Hi!

First, thanks for sharing this plugin.

The Simple Masonry widget no longer works after updating to 1.5.5

It seems one of the assets is named "imagesloaded.pkgd.js" but it's being called as "imagesLoaded.pkgd":

https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/simple-masonry/simple-masonry.php#L165

Renaming the JS file fixes the issue in Linux environments.

Thanks,

Jordi

**Comment by gregpriday** [comment]
Thanks for letting us know @jordif! There was a problem with migration code in 1.5.5, so we pulled it form WordPress.org, but it was available for a few hours. For now, you can roll back to 1.5.4. We'll fix this issue for the next release too.
