### ISSUE TITLE
Warning: preg_match(): Compilation failed: missing terminating ]

### ISSUE THREAD

**Issue by kallehauge** [siteorigin/so-widgets-bundle#880]
**How to reproduce**

* Enable `WP_DEBUG` since it's a warning
* Copy [this code](https://gist.github.com/kallehauge/d3a86a673733d383de0a001b7fdf3fb8)  and add it to a theme/plugin. The template file can simply be empty because it is a rendering/setting issue.
* Create a new Gutenberg page and copy+paste the content-snippet below with the code editor instead of the visual editor.
* Refresh page and you should be meet with the following error: `Warning: preg_match(): Compilation failed: missing terminating ] for character class at offset 61 in /var/www/html/wp-content/plugins/so-widgets-bundle/base/inc/fields/tinymce.class.php on line 285`

**Content snippet**
```
<!-- wp:siteorigin-panels/layout-block {"panelsData":{"widgets":[{"columns":{"column_0":{"content":"\u003cp\u003eAsdasdasd asd asd\u003cstrong\u003e asd asd asd\u003c/strong\u003e\u003c/p\u003e\n\u003cp\u003easdasd\u003c/p\u003e\n","content_selected_editor":"tinymce","so_field_container_state":"open"},"so_field_container_state":"open"},"_sow_form_id":"19212491075d109997225fe941115363","_sow_form_timestamp":"1561369009479","panels_info":{"class":"Theme_Cta_Columns_Widget","raw":true,"grid":0,"cell":0,"id":0,"widget_id":"fa3ea451-5a87-48b8-9425-c7ef91d250f5","style":[]}}],"grids":[{"cells":1,"style":[]}],"grid_cells":[{"grid":0,"index":0,"weight":1,"style":[]}]}} /-->
```
_This snippet will create a layout block with the example widgets linked in the gist and the `raw` panel_info attribute set to `true`._

**Description**

So there is a couple of conditions that have to be meet to hit this edge-case:

First, it needs to be a `tinymce` field that contains a `mce_buttons` filter override to be able to get through the first "if" condition in `SiteOrigin_Widget_Field_TinyMCE::__call`.

Secondly, `panel_info` have to contain `"raw": true` so the `base_name` property will contain square brackets (`/widget-theme-cta-columns-widget-.*-columns][column_0][content/`).
Because `preg_match` use square brackets to create patterns, then this example will end up with an opening square bracket that will create the warning because the bracket is never closed.

Thirdly, then the widget have to contain nested fields so the base name will actually contain square brackets. 

This makes pages with the warning unusable because the Gutenberg editor will start having floaing elements etc because of broken markup and logs will quickly be > 10mb because the warning is outputted multiple times on each load of the editor page.

**Comment by AlexGStapleton** [comment]
I've run a few tests and have been able to replicate this issue.

**Comment by AlexGStapleton** [comment]
Hi @kallehauge,

Do you happen to have a copy of the code you originally linked with this issue? The provided link isn't working anymore and I can't seem to find it in my notes.

Kind regards,
Alex

**Comment by AlexGStapleton** [comment]
Hi @kallehauge,

I'm going to close this to clear up the current queue. Due to the complexity of replicating this issue and the very specific TinyMCE adjustments, the guesswork on our end in replicating this issue without the originally linked code is quite high. We're still keen on fixing this and If you're still keen also, please reply with a copy of the code and we'll pick this back up.

Kind regards,
Alex
