### ISSUE TITLE
Site Origin Bundle Features Widget - Character encoding issue

### ISSUE THREAD

**Issue by e-me** [siteorigin/so-widgets-bundle#888]
There is an issue with content created with this widget not appearing in searches, 
Here is the issue:  In image widget, when Greek text is added it gets converted to json utf u0xx codes.
This doesn't happen with s.o. editor or other widgets, but is really critical since the added text is not found on search e.t.c.

It is saved like that to DB
![image](https://user-images.githubusercontent.com/38039666/62379985-d52cb980-b550-11e9-8ee9-a910ae218741.png)

Instead of 
![image](https://user-images.githubusercontent.com/38039666/62380026-f68da580-b550-11e9-865d-2e345063c086.png)

**Comment by AlexGStapleton** [comment]
Hi @e-me,

Thank you for the report. Would it be possible for you to send me an export of the widget you're working on? This will allow me to run some tests against the specific widget you're working on and hopefully work out where things are going wrong.

To export a page, please open up the linked page in the editor and click the Layout button in the Page Builder toolbar. Then click import/export and then click download. Please upload the export to a 3rd party file hosting site such as <a href="https://wetransfer.com/">WeTransfer</a>  (no email is required).

**Comment by e-me** [comment]
Hi, [here's the export](https://we.tl/t-hRA9pLEA1o), which looks ok because it is already parsed. 
The data in database still looks the way I described, making search impossible.

**Comment by AlexGStapleton** [comment]
Thanks. To confirm, is this happening for all widgets for you or is it only the SiteOrigin Image widget?

**Comment by e-me** [comment]
Only for the image widget.

**Comment by AlexGStapleton** [comment]
Thanks. I've had a look over the provided layout and there isn't an image widget present. Can you please confirm which widget in the provided layout (please provide me with a copy of the custom widget title you're using) you're specifically having trouble with?

Also, to confirm, are you having issues with the (WordPress) Image widget or the SiteOrigin Image widget? If the image widget, does this issue occur with the SiteOrigin Image widget?

**Comment by e-me** [comment]
Oh, my bad, the widget is named SiteOrigin Features. 
That's the second row, left column on the page.

**Comment by AlexGStapleton** [comment]
Hi @e-me Thanks. I've been able to replicate this. I suspect an upcoming change we're making will indirectly resolve this issue. Once those changes are ready for testing, I'll run some tests with your layout to see if this issue has been resolved by it.

**Comment by e-me** [comment]
@AlexGStapleton  Nice! Will be waiting for the update!

**Comment by e-me** [comment]
Hi @AlexGStapleton , any update on this one? Thanx!

**Comment by AlexGStapleton** [comment]
Hi @e-me,

Unfourtantly the aforementioned update hasn't been completed yet. That update is a large change to how we're handling fallback data and passing it to plugins like Yoast so it's providing to be a huge undertaking. I'm really sorry about this!

**Comment by AlexGStapleton** [comment]
I've retagged this issue with the bug tag and given it a priority 3. I've assigned it a p3 due to it being dependent on a PR that's halting progress.
