### ISSUE TITLE
Widget Hooks (Do something when widget removed)

### ISSUE THREAD

**Issue by ingageco** [siteorigin/so-widgets-bundle#889]
Hey Team - thanks again for the great plugin/framework. 

I'd like to know if there is a system for detecting when a widget is deleted. 

Use case: i have a widget for a Vimeo video gallery that caches the api response in a meta field. If the widget is deleted, i'd like to be able to delete that cached data. 

Is this possible? ... or as I'm writing this, should i be using transients instead so they are periodically cleaned up? (i know that's a general question)

**Comment by AlexGStapleton** [comment]
Hi Jay,

Unfortunately, there isn't a reliable method of tracking whether a widget has been removed/added.
I highly recommend using transients to do this. It's what we use to handle widget CSS generation to ensure it's effectively cached.

**Comment by ingageco** [comment]
Thanks Alex - i knew i answered my own question. No need for the hooks if the cache expires in my case.
