### ISSUE TITLE
Contact: Prevent Required Message markup from output if no required text is set

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#894]
Prevent Required Message markup from output if no required text is set. This will allow for the user to indicate this via alternative methods.

![2019-08-17_00-22-36-896](https://user-images.githubusercontent.com/17275120/63174356-2080b500-c085-11e9-8b3d-9304509e3378.png)

**Comment by AlexGStapleton** [comment]
Related: #753

**Comment by AlexGStapleton** [comment]
@Misplon You know, in hindsight, I'm not sure if this is a good idea. If this change is made, any field with the required message not set, which is how it's set by default, will no longer appear when it previously did. What are your thoughts? A developer could interact with the message by using CSS (or even JavaScript) using the `.sow-error` class.

I do however think it would be a good idea to set the `Missing Message` to `This field is required` (or what it currently is, `Required Field`) as it's currently blank by default.

**Comment by Misplon** [comment]
Thanks, agreed on all points.
