### ISSUE TITLE
Social Media Buttons: Add unit of measurement to breakpoint

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#895]
The Social Media buttons breakpoint doesn't always work due [the default breakpoint](https://github.com/siteorigin/so-widgets-bundle/blob/1.15.7/widgets/social-media-buttons/social-media-buttons.php#L34) being without a unit of measurement.

Related #767

**Comment by gregpriday** [comment]
Just fixing the default value for `responsive_breakpoint` was enough to fix this. After a user saved the setting, as @braamgenis mentioned in https://github.com/siteorigin/so-widgets-bundle/pull/767, it would have been properly sanitized with a `px`.

From my testing, the original default value is the only way a value without a measurement could occur.
