### ISSUE TITLE
TinyMCE widget as a field

### ISSUE THREAD

**Issue by stueynet** [siteorigin/so-widgets-bundle#9]
Again sorry for all the issues. Please just ignore if you are busy. 

I need a wysiwyg field as part of one of my custom widgets. I know there isn't a built in field as we leverage Black Studio's widget in Page Builder. So my next move was to try and use it as a subwidget in a field but it goes fatal. 

Here is what I tried:

```
			'editor' => array(
				'type' => 'widget',
				'label' => __( 'Black Studio Widget', 'text-domain' ),
				'class' => 'WP_Widget_Black_Studio_TinyMCE',
				'hide' => true
			)
```

Thanks again!

**Comment by gregpriday** [comment]
Yeah, unfortunately the widget field in the Widgets Bundle can only handle widgets that extend `SiteOrigin_Widget`, you can't use arbitrary widgets in there (not yet anyway). We've added some checks for this in the dev version.
