### ISSUE TITLE
Google Maps: Map center drop-down isn't working in the Customizer

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#900]
To reproduce this issue, open the Customizer > Widgets and add a SiteOrigin Google Maps widget to a theme widget area. Try to add a map center, the drop-down isn't appearing which means you can't select a center. Manually typing one in doesn't help.

**Comment by Misplon** [comment]
@AlexGStapleton Can you confirm you're seeing the same issue? Thanks.

**Comment by AlexGStapleton** [comment]
I've been able to replicate this.

**Comment by Misplon** [comment]
Thanks. If you notice any errors, please, add them to the issue. I didn't.

**Comment by AlexGStapleton** [comment]
I just double checked, and I'm not getting any error messages.

**Comment by Misplon** [comment]
@braamgenis Would you perhaps be able to resolve this next week?

**Comment by braamgenis** [comment]
@Misplon Sure, just assign to me and I'll take a look as soon as I can.

**Comment by Misplon** [comment]
Looks good. Thanks!
