### ISSUE TITLE
Remove 'Add Media' button on TinyMCE field (widget form)

### ISSUE THREAD

**Issue by ingageco** [siteorigin/so-widgets-bundle#902]
Is there a way to disable toe "Add Media" button on the tinymce field? Looking for something like what CMB2 has with 'media_buttons' => false. I see that there are filters for the editor, but i wasn't sure if those targeted the media buttons. Thanks for the help

https://github.com/CMB2/CMB2/wiki/Field-Types#wysiwyg

**Comment by AlexGStapleton** [comment]
Hi @ingageco,

There isn't a direct method of removing the **Add Media** button without overriding the [media_buttons](https://developer.wordpress.org/reference/hooks/media_buttons/) action. I've created an enhancement issue with a request to add an option to remove the Add Media Button.

**Comment by aloziak** [comment]
Hi, in the documentation of SiteOrigin is option for disable Add Media, [see](https://siteorigin.com/docs/widgets-bundle/form-building/form-fields/). But this option does not work. I've discovered the class [tinymce.class.php](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/fields/tinymce.class.php) and there is nothing related to the option media_buttons which is mentioned in the documentation. How this option works?

**Comment by AlexGStapleton** [comment]
This option is currently pending as a PR here: https://github.com/siteorigin/so-widgets-bundle/pull/1229
It looks like the docs were updated a little bit too soon - sorry about that!
