### ISSUE TITLE
Add setting to always show slider navigation, or expand nav_always_show_mobile to drop down

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#906]
A number of requests have come in about always showing the Slider navigation. Due to the changes made in #815, this could be done by changing [nav_always_show_mobile](https://github.com/siteorigin/so-widgets-bundle/blob/develop/base/inc/widgets/base-slider.class.php#L94) to a drop down and adding an additional conditional to [the relevant slider JS](https://github.com/siteorigin/so-widgets-bundle/blob/67907a25c3115f2de8fe993bf1bdc8345401e4fb/js/slider/jquery.slider.js#L204). Alternatively, a dedicated setting could be introduced to control the desktop version independently of the mobile setting.

**Comment by Misplon** [comment]
@AlexGStapleton I'm keen to see this rolled out, I'm bumping to p2.
