### ISSUE TITLE
Contact: Checkbox and Radio labels aren't able have colors changed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#907]
The Radio and Checkbox field labels aren't able to have their colors changed via any of the Designs settings. This is problematic if the user changes the contact form background and the text colors defined by the theme don't work with this change.

We should extend the Field Label Text Color setting to cover the Checkbox and Radio labels to avoid this.

**Comment by gregpriday** [comment]
@AlexGStapleton do you want to implement this and submit a PR?
