### ISSUE TITLE
Post Carousel: Add a setting to change the thumbnail overlay color

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#908]
Consider adding a setting to change the hover overlay color and perhaps opacity.

**Comment by AlexGStapleton** [comment]
The thumbnail overlay color is actually already adjustable via the ` Thumbnail overlay hover color` setting. Do you want to proceed adding an opacity setting?

**Comment by Misplon** [comment]
Sure, let's do that. Thanks.
