### ISSUE TITLE
5.3 RC3: SiteOrigin Widget Block doesn't work

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#915]
The SiteOrigin Widgets Block isn't working with the WordPress 5.3-RC3-46639. I'm unable to edit SiteOrigin Widget Block and unable to preview it.

![](https://i.imgur.com/gs08mT2.png)

The following console error is present:
![](https://i.imgur.com/xcmymLm.png)

**Comment by Misplon** [comment]
I can confirm that this issue persists with `5.3-RC4-46680`. This is a newer version than when the issue was logged.

**Comment by Misplon** [comment]
I've also confirmed that the issue existed in `5.3-beta3`.

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/so-widgets-bundle/commit/76ac79ca388a39e90e21b2d9babd72a28ef9d8e8.
