### ISSUE TITLE
Hero Widget: Pause while focussed new setting proposal

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#920]
Consider adding a setting to the Hero that will pause the slider when a user is focussed on a slide. This will be useful for users wanting to add a form to their slider (newsletter etc.) but still have multiple frames/slides. Once implemented the same setting could be extended to the Layout Slider widget.

**Comment by AlexGStapleton** [comment]
This was resolved by https://github.com/siteorigin/so-widgets-bundle/pull/1109
