### ISSUE TITLE
Post Carousel: Add a new setting to disable looping

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#929]
Consider adding a setting to the Post Carousel widget to disable looping behavior introduced in `1.15.9`.

**Comment by Misplon** [comment]
I think the setting should be located as follows:

<img width="850" alt="Edit_Page_‹_SiteOrigin_—_WordPress" src="https://user-images.githubusercontent.com/789159/71544613-71d17700-298a-11ea-8925-9e372403efab.png">

I think the setting should be a default enabled checkbox with the following wording.

**Loop posts**
Automatically return to the beginning of the post loop once reaching the end.

**Comment by AlexGStapleton** [comment]
The intentions behind the changes introduced in 1.15.9 were to make the carousel function more like a traditional carousel but it also resolved an issue with how the carousel previously worked.

Previously, when all of the posts have been displayed, if the user clicked navigate a blank post would be displayed. This would happen each time the user clicks next until the last real post was the only visible post left - the rest were blank "posts". 

When the last series of posts load, if there isn't enough to fill the full width of the carousel, the required number of posts from the previous series of posts should remain visible. The next button should also be disabled at this point.
