### ISSUE TITLE
post carousel thumbnail not showing ?

### ISSUE THREAD

**Issue by beppe9000** [siteorigin/so-widgets-bundle#930]
Even tough there are images in the post. I think posts should be scanned for images automatically.

**Comment by Misplon** [comment]
Hi, thanks for reaching out.

The Post Carousel uses the featured image from the post or pages being included in the loop. If you add a featured image per post or page, the carousel will display the image.

Hope that helps :)

**Comment by beppe9000** [comment]
I solved using another plugin that sets the featured image automatically. Yet I would like to suggest to add a checkbox option to scan posts for first content image when featured image is missing.

**Comment by Misplon** [comment]
Super, glad to hear you've made progress with a plugin solution. 

If we receive many requests to add scanning as a feature, I'll be sure to log it. Using the featured image to represent a post or page is very well supported across plugins and themes.

If you have any support questions in the future, feel free to open a thread on our [forum](https://siteorigin.com/thread).

Cheers for now :)
