### ISSUE TITLE
Slider widgets:  Consider adding font-display for web fonts

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#938]
Consider adding `font-display` for the slider web-font.

**Comment by AlexGStapleton** [comment]
I'm personally partial to setting it to `swap` but I feel certain users may not understand why a different font may briefly appear on load and that may result in support tickets. How would we communicate that to avoid this?

**Comment by Misplon** [comment]
Let's perhaps start with `swap` and see how we go on the support front.
