### ISSUE TITLE
Adding filter for LESS variables

### ISSUE THREAD

**Issue by ernilambar** [siteorigin/so-widgets-bundle#94]
I am trying to extend bundle widgets. I am able to add extra color fields. I also created and hooked custom LESS file. But I could not find appropriate hook to add my extra fields to LESS variables array. Is there any other way? Am I missing related hook? If not this would be great addition in the plugin.

Thanks

**Comment by ernilambar** [comment]
Can anyone please check this issue? Thanks.

**Comment by AlexGStapleton** [comment]
As this issue was posted so long ago I'm going to close it. Let me know if you still need assistance with this and I'll reopen it.
