### ISSUE TITLE
Social Media Icons: Ensure all icons are correctly centered

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#941]
[Demo](https://demo.siteorigin.com/premium/social-widgets/).

Not all icons appeared to be correctly centered.

<img width="693" alt="Screenshot 2019-12-27 at 16 29 40" src="https://user-images.githubusercontent.com/789159/71520723-23f33b00-28c6-11ea-89de-b470b1227e41.png">

Because of this rule:

```
.so-widget-sow-social-media-buttons-flat-4f40679f3e8a .sow-social-media-button .sow-icon-fontawesome {
    width: 1em;
    height: 1em;
    display: inline-block;
}
```

And given the `em` base in Corp, if the icon is wider than `30px` it'll be outside of the centered container.

**Comment by AlexGStapleton** [comment]
I can replicate this issue. Simply removing the `width` will break Image Icons so special consideration is required to ensure that doesn't happen.

**Comment by Misplon** [comment]
Thanks. Yeah, agreed. Not sure how to resolve yet, will investigate further.

**Comment by Misplon** [comment]
Looks good, you can see this PR in action on the demo page here https://demo.siteorigin.com/premium/social-widgets/.

**Comment by Misplon** [comment]
In my local install I see a difference between develop and master.

develop

<img width="387" alt="01" src="https://user-images.githubusercontent.com/789159/72091483-f15f2e80-3318-11ea-8ab8-470128594cce.png">

master

<img width="528" alt="02" src="https://user-images.githubusercontent.com/789159/72091486-f45a1f00-3318-11ea-829e-ad85e85cc809.png">

layout used

[classic.json.zip](https://github.com/siteorigin/so-widgets-bundle/files/4041742/classic.json.zip)

icon used

![icons8-customs-officer-26](https://user-images.githubusercontent.com/789159/72091548-1653a180-3319-11ea-8882-4daddf87d207.png)

**Comment by braamgenis** [comment]
Ah... that's an image, not an icon. OK, will see what I can do about those.

**Comment by Misplon** [comment]
It looks like there several other differences in the layout though.

**Comment by Misplon** [comment]
<img width="1071" alt="03" src="https://user-images.githubusercontent.com/789159/72095090-7ac62f00-3320-11ea-8035-25b3532ca9bf.png">
<img width="803" alt="04" src="https://user-images.githubusercontent.com/789159/72095092-7ac62f00-3320-11ea-9b4f-56e4ad6fb56f.png">

Not several but yeah, not the same.

**Comment by braamgenis** [comment]
@Misplon Please check again.

**Comment by Misplon** [comment]
Solved, thanks.
