### ISSUE TITLE
Image Widget: srcset validation error

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-widgets-bundle#95]
We've had a report that the image widget is causing the following validation error

> When the srcset attribute has any image candidate string with a width descriptor, the sizes attribute must also be present.

Worth investigating.

**Comment by m1ndmaker** [comment]
Any news on this issue?

**Comment by reachdigitalaus** [comment]
Any news on this?

**Comment by arodesign** [comment]
Any news/fix for this?

**Comment by braamgenis** [comment]
Fixed since 6ad1b65c2d0171949915a3b9d660fe2f6aec9776
