### ISSUE TITLE
Testimonials: Image size isn't applied to square images

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#953]
When Image shape is set to Square, Image size doesn't appear to be functioning.

**Comment by AlexGStapleton** [comment]
I can't seem to replicate this anymore. Was this indirectly fixed by #952?

**Comment by Misplon** [comment]
Perhaps. 

However, when I test now, my square image is 58 x 58 when the size is set to 50 x 50. When I switch to round, the image is 50 x 50. Do you see the same issue?

**Comment by AlexGStapleton** [comment]
As in the literal dimensions of the image, or how large the image appears on the frontend? If the latter, I suppose I could force the image dimensions.

**Comment by Misplon** [comment]
Here is a test page:

https://demo.siteorigin.com/corp/testimonial-demo/

When round, 50 x 50 is exactly adhered to. When square, 50 x 50 is not exactly adhered to. Is this expected? It doesn't seem right.

**Comment by AlexGStapleton** [comment]
Gotcha. It's the latter. The round image is a background image with clearly defined dimensions, while the square container is an HTML image and only the width is considered. I don't see any reason not to make this change.
