### ISSUE TITLE
Paragraphs around shortcodes (SiteOrigin Editor)

### ISSUE THREAD

**Issue by jordif** [siteorigin/so-widgets-bundle#97]
Hi!

It seems paragraphs are added around shortcodes. 

Example: if you add a video shortcode using the SiteOrigin Editor, paragraph tags are added. If you add the same shortcode using the default wp editor (page builder disabled), paragraphs are not added.

It seems changing the following line:

https://github.com/siteorigin/so-widgets-bundle/blob/develop/widgets/editor/editor.php#L68

to:

$instance['text'] = do_shortcode( shortcode_unautop($instance['text']) );

would fix the issue.

Thanks

**Comment by gregpriday** [comment]
Thanks for letting us know @jordif - I'll test out your fix shortly.

**Comment by braamgenis** [comment]
Added in 87263694ba2ee997b70c089fbcba4b9f01e1d170
