### ISSUE TITLE
Provide list of used images to Yoast Sitemap 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#979]
We should provide Yoast Sitemap with a list of the images added using SiteOrigin Widget block. This can be done using the `wpseo_xml_sitemap_img` filter.

https://kb.yoast.com/kb/images-in-the-xml-sitemap/

**Comment by Misplon** [comment]
@AlexGStapleton Is this resolved by https://github.com/siteorigin/siteorigin-panels/pull/769 ?

**Comment by AlexGStapleton** [comment]
Yes.
