### ISSUE TITLE
Layout Slider: Pause on hover

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#982]
Consider adding a new setting to the Layout Slider to pause on hover.

**Comment by AlexGStapleton** [comment]
How does this sound?

Label: Autoplay pause on hover
Description: If enabled, the slider won't change slide while the user is hovering on the slider.

**Comment by Misplon** [comment]
The label is good. Do you want to try this one without a description? We're using the word slider a few times in the proposed description. An alternative is perhaps "Pause autoplay while hovering over the slider." That's pretty similar to the label. Should we try with just the label?

**Comment by AlexGStapleton** [comment]
Let's try with just the label.

**Comment by Misplon** [comment]
Sounds good, thanks.
