### ISSUE TITLE
HTML Added Using SiteOrigin Widgets Block Will Break If Page Cloned Using Duplicate Page Plugin

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-widgets-bundle#984]
<img width="535" alt="2020-02-10_01-01-01" src="https://user-images.githubusercontent.com/17275120/74104497-f2e27780-4ba0-11ea-8052-be9559f4b7af.png">

The [Duplicate Plugin](https://en-au.wordpress.org/plugins/duplicate-page/) is used on over a million websites. This issue only occurs while using the Block Editor.

To replicate this issue, add SiteOrigin Widgets block and select Editor. Switch to the Text mode and then add the following HTML to that block:

```
<div>
	This is a test SiteOrigin Editor widget. The problem happens when there's HTML present. So to make it really visible, I'm going to add a bunch of HTML.
	<p>
		This is a paragraph.
	</p>
	<ul>
		This is a list.
		<li>1</li>
		<li>2</li>
		<li>3</li>
	</ul>
</div>
```

Save, and then click **Duplicate This** (it's next to the Publish/Update button). Open the duplicated page and you'll notice that the HTML is no broken in both the preview.

**Comment by gregpriday** [comment]
I've been chatting to the new developer I'm hoping to get on board to handle most of the fixes and updates for all SO plugins in the future. He's had a look over some of the GH issues we have, and for this one he says it's actually a user configuration error. So the user needs to manually set that they're using the block editor.

![settings](https://user-images.githubusercontent.com/1126859/75018845-7ef57880-5498-11ea-99a7-7266a628ecee.jpg)

Once that's properly set, this issue no longer happens. Can either of you confirm, and if so, we can just document this and let our users know when they come across it.

**Comment by AlexGStapleton** [comment]
I can confirm that works. Nicely spotted! Strange that's not automated.

**Comment by hungnguyen1407** [comment]
i've got a trouble with html verify my site! https://reviewxiaomiwatch.com/blog/danh-gia-dong-ho-xiaomi-amazfit-gts . 
Humm
