### ISSUE TITLE
Hero: Add a new setting to vertically align contents

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#986]
@AlexGStapleton Can you please, take a look at the widget and let me know a suggested location and wording for the setting before you get going on this. Thanks mate.

**Comment by AlexGStapleton** [comment]
Setting Name: Vertically Align Slides (checkbox)
Location: Just after Responsive Height setting in the Design and Layout settings group

This location should reduce the number of people using "the old way" of centering the contents using padding - something that would actually break the vertical alignment. It might be a good idea to add a description to the setting that mentions padding being factored in, but I'm drawing a blank on how to word that and have it make sense.

**Comment by Misplon** [comment]
Super, thanks. How about tweaking the setting label wording to:

**Vertically align slide contents**

Location sounds good.

Let's see how it works, we can then work on the description sentence wrt. to explaining padding.
