### ISSUE TITLE
Contact Form: Add a new setting to set field max-width

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-widgets-bundle#988]
We have a setting to set the label width. Let's consider adding a setting to set field max-width. The use case is for when your form container is wider than you'd like your field width to be.

**Comment by Misplon** [comment]
If the Label width setting is in fact a max-width then consider renaming that setting label to Maximum Width to be clearer.

**Comment by AlexGStapleton** [comment]
Label width setting is `width`.
