### ISSUE TITLE
Error message when previewing with the Editor Widget

### ISSUE THREAD

**Issue by aequitascs** [siteorigin/so-widgets-bundle#994]
With WP_DEBUG and WP_DEBUG_DISPLAY on, the following message is displayed when previewing a post containing the Editor Widget:

Notice: Trying to get property 'ID' of non-object in /Users/andrewf/EclipseProjects/so-wordpress/wp-content/plugins/so-widgets-bundle/widgets/editor/editor.php on line 118

To reproduce the problem:

Create a new post
Add an Editor Widget
Enter some text
Click _Preview_

If WP_DEBUG is enabled, the error will occur.

This was discovered while investigating #984.

**Comment by Misplon** [comment]
Thanks for logging @aequitascs. I have confirmed.

**Comment by aequitascs** [comment]
Further investigation shows that this message occurs in two circumstances.

1. When previewing a new post that has not yet been saved to the database.

2. When previewing the contents of the TinyMCE editor using the embedded preview button, under all circumstances.

This is because the $post object itself is _null_ under those conditions.

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/so-widgets-bundle/pull/996.
